MACHINE
  id_uye( id_cwk )

CONSTRAINTS
  not
    (!(id_lvt, id_htb, id_tsq, id_ggh, id_qfj, id_xmz).
     (!
        (id_snl, id_xmv, id_zpv, id_nhf, id_orz, id_qal, id_gom, id_tgr,
         id_tno).
      (#(id_ilg, id_mih, id_wbt, id_mrx, id_dqp, id_oel, id_bem).
       (not
          (not
             (#
                (id_wfj, id_rfi, id_api, id_sms, id_efq, id_eyr, id_kac,
                 id_lkk, id_wnl).
              (NATURAL1 /= str_tup)))))))

SEES
  id_mig, id_dtj

INCLUDES
  id_icq (
    [rec
       (id_rnh:
        struct
          (id_vpa: str_skd,
           id_npr: arity([str_jao$0, MININT]),
           id_fzm: str_zjb,
           id_fei: str_sgn,
           id_ufi: str_tvt,
           id_ijm: str_rob),
        id_cfx: str_dyz),
     (str_xtg$0 --> str_nec),
     struct
       (id_ubk: str_poo,
        id_qgx: "str_vyn",
        id_dzz: str_zdb$0,
        id_ynv: STRING,
        id_yqm: str_zzq)],
    rec
      (id_uaw: FALSE,
       id_bge:
       [{}, str_cry$0, str_gac$0, FALSE, str_nea, str_gfs$0, str_vnd$0,
        str_doo$0],
       id_jlo: str_jfr,
       id_hxj:
       rec
         (id_uid: str_nnq,
          id_fzc: str_wtl$0,
          id_lcx:
          %
            (id_opn, id_ybg, id_jrn, id_jrb, id_mtf, id_fhy, id_bpn, id_gce,
             id_xvx, id_zxg).
          (NATURAL /= str_smt$0| str_kiu$0),
          id_uny:
          { id_zfx, id_euo, id_gzv
            |
            not(MININT >= str_pou) => str_elh /<<: INT },
          id_uav: str_sbp,
          id_blt: str_wwf$0),
       id_ezz: [],
       id_uuo: NAT1),
    ([str_cdj, str_kln$0, str_aqu$0] |->
     size
       ([{BOOL, NATURAL1, NATURAL, NATURAL1, str_wng$0, NAT1, str_fyb},
         struct
           (id_ser: (str_yen |> str_psr),
            id_ljt: str_xqd$0,
            id_oxu: str_ztz,
            id_qhl: str_why),
         str_wzb,
         MAXINT]))
  ),
  id_xon (
    bool
      (not
         ({ id_jlb, id_zzv, id_zey, id_cvn, id_ojg, id_npz, id_rzr, id_cmj,
            id_riu, id_bip, id_pmz
            |
            !(id_bde, id_rbz, id_owf, id_mzj).(STRING = str_ycl) } <=
          {str_hrw$0, str_vmz$0}))
      'id_zwo,
    UNION(id_fyl, id_rue, id_xka, id_ybg, id_utt, id_tng, id_rik).
    (str_mvu$0 /\
     { id_plb, id_fjh, id_kuv, id_xtv, id_pnf
       |
       !
         (id_eky, id_lon, id_gde, id_lxw, id_pqt, id_qez, id_ybd, id_wso,
          id_pxn).
       (!
          (id_xpg, id_xyq, id_hcc, id_scx, id_fsm, id_svt, id_sgs, id_tdh,
           id_bpc, id_ehb, id_awp).
        (str_bpa < str_sxc)) } =
     str_jft =>
     str_vre /<<: str_rap|
     INTEGER)
  ),
  id_tsx (
    rec
      (id_zqr:
       {MAXINT,
        "str_cgh",
        struct(id_axk: INT, id_ewk: str_qye, id_ulv: str_qir),
        {}},
       id_jjt:
       {struct
          (id_ymd: str_oya,
           id_atd: 405,
           id_beo: str_orc$0,
           id_jik: str_phm$0,
           id_fsm: str_gpi$0,
           id_plx: str_fno,
           id_kju: str_ptm,
           id_bak: str_eyz)
          'id_aqg},
       id_icw: str_bob$0,
       id_oly: NAT1'id_pko,
       id_cxr: [],
       id_aen: str_ime$0),
    bool
      ({ id_ble, id_qhf, id_zep, id_hjj, id_ins, id_kpr, id_ksi
         |
         str_kal : TRUE or NAT : str_woy } /<:
       bool(str_joq /: NATURAL1) <<| bool("str_qdr" < str_ych)),
    { id_crz, id_zrx, id_woc, id_dlh, id_msh, id_onw, id_fpa, id_cmi, id_pen,
      id_wdf
      |
      not
        (str_fyb /=
         id(struct(id_lus: [])) >+>
         SIGMA(id_xdi, id_fgz, id_env, id_qcs).
         (str_gwf$0 <<: str_jlc| str_ufe$0)) }
  ),
  id_xbs,
  id_bni (
    [[NAT, str_ami, postfix(str_fzw), NAT1, str_idf$0],
     (str_lzv$0 -->> {{}, [], bool(str_nmq$0 /: str_sfd), FALSE}),
     bool({} <= str_tli$0)],
    {}
      [%(id_vyg, id_dmv, id_gmf, id_nmy).
       (str_ybr$0 : STRING|
        { id_hsr, id_xct, id_idg, id_veo, id_zzw
          |
          str_aaj$0 =
          { id_yxw, id_ojm, id_kto, id_wgm, id_zhj, id_cmf, id_epi, id_ley
            |
            !(id_mjm, id_bwt).(str_vcu$0 <= str_sqs$0) } })]
      'id_owv
  ),
  id_baj (
    struct
      (id_cqx: NAT,
       id_ovv:
       bool
         ({ id_pag, id_nte, id_wza, id_aog, id_qeu
            |
            not
              (#(id_dqb, id_xbn, id_zrw, id_dxh, id_klx, id_ory).
               (str_ujg$0 /<: str_zdl)) } >=
          str_vvr$0),
       id_xpv: str_lbt$0,
       id_mvz: (str_yrx$0 - str_sna$0),
       id_wlm: str_ocv$0)
  ),
  id_btx (
    { id_npz, id_brq, id_awb, id_fap, id_jjj, id_hdn
      |
      UNION(id_fjm, id_bvh, id_adv, id_cdw, id_nwv).
      (str_mrp /<: str_epy$0|
       rec
         (id_eag: [BOOL, str_iau$0, FALSE, NAT, str_huv],
          id_hgm: str_uqf,
          id_lzz: MININT,
          id_aql: rec(id_ddc: STRING, id_sth: {}),
          id_mug: str_dcj$0)) /=
      { id_qva, id_qpb, id_bss, id_cwd, id_qjg, id_nax, id_lst, id_qlc,
        id_jbz, id_ejm, id_avu
        |
        TRUE < NATURAL } },
    {str_nmq,
     PI
       (id_nry, id_bfn, id_qln, id_zoa, id_grz, id_qfc, id_bbz, id_ybz,
        id_uqh, id_xps, id_dqw).
     (not
        (not
           (INT >
            struct
              (id_eqp: str_koh,
               id_chp: { id_lxh | str_kyr < [] },
               id_cga: INT)))|
      str_thp),
     {},
     str_rty,
     str_oyi,
     str_frg$0}
  ),
  id_bfo (
    { id_zrx | not(NATURAL1 /= rev(str_evg >+> left(str_lsx))'id_dxq) },
    { id_ctu, id_oda
      |
      str_jrr /<:
      struct
        (id_fgg: str_rkq,
         id_faf: str_gkn$0,
         id_bhc: str_jsu$0,
         id_tfz:
         { id_kmf, id_vqv, id_gsf, id_trj, id_qnd, id_ycp, id_vmc, id_hdf,
           id_eud, id_cje
           |
           str_dab /<: str_dez$0 },
         id_yde: str_sus,
         id_ofh: str_hhx) <=>
      !(id_krk, id_sig, id_ufi, id_lnm, id_bqn, id_mfg).
      (!(id_sdu, id_sco, id_pfg, id_rpr).(NATURAL : NAT)) },
    {bool(str_gvf /: "str_lpx"),
     [],
     str_mrh,
     bool(str_rmy : str_vsw$0),
     [(-str_kmv),
      [struct(id_ddr: MAXINT, id_zch: str_ppx$0, id_npj: str_zzi), str_fdb$0]],
     BOOL,
     NAT}
  ),
  id_ryo (
    rec
      (id_kpu:
       (("str_tmu" ** str_zwz$0) <<|
        { id_jlb, id_gwk, id_gkm, id_cgm
          |
          !(id_qvn, id_sok, id_poa, id_tet, id_kgt).
          (#(id_oqd, id_ghs, id_gtn, id_kkm, id_aaa, id_lsy, id_uyn).
           (INT : TRUE or str_bzj <: TRUE)) })),
    %
      (id_njn, id_hli, id_pee, id_kaf, id_jrj, id_nbz, id_hqb, id_kro,
       id_wzb, id_mkl).
    (str_myt /<: str_kai$0|
     ((struct(id_uqj: str_oco, id_gfc: str_ycu, id_mvd: str_nlq) mod str_aty)
        'id_zqi >->
      str_bgp$0)
       'id_sqn)
      'id_dsb
  ),
  id_qje (
    struct
      (id_gfh: str_phu,
       id_epy: str_ofe,
       id_yvv: str_hsc,
       id_meq: NAT1,
       id_uta: [],
       id_ngn: father(str_hgg),
       id_qdk:
       PI(id_kon, id_jfb, id_mih).
       (#(id_hof, id_pzz).(!(id_aws, id_plq, id_sov).(NAT1 < str_qit))|
        (str_nsj$0 <| str_xcm) >+> str_bcm$0)),
    btree
      (id
         ({INTEGER,
           {str_yag},
           struct
             (id_ihj: bool(str_ulc /: str_ifb),
              id_jew: MININT,
              id_sga: str_rlq,
              id_sgs: NATURAL,
              id_hjq: str_gbp$0,
              id_fbg: str_kmc$0,
              id_qjz: str_dca),
           str_tdz,
           INT,
           [],
           MININT,
           MININT}))
  )

PROMOTES
  id_gyd, id_udk, id_rne, id_skk

EXTENDS
  id_yap (
    PI(id_qmn, id_tjf, id_bma, id_gml).
    (PI(id_lmg, id_btv).
     (#
        (id_yfh, id_mxv, id_ote, id_pox, id_fbx, id_ira, id_vdt, id_gxa,
         id_whg, id_sor, id_ihm).
      (#(id_dex, id_xsk).(str_eex$0 <<: str_xct))|
      str_bgl$0) /<<:
     FIN1(str_bmz$0) <<| str_meo|
     str_cjr$0),
    (btree
       (rec
          (id_lml:
           { id_wtu, id_yea, id_okw, id_iwh, id_vjz, id_glf, id_oub
             |
             NATURAL /<: NAT },
           id_gjx: POW(MAXINT),
           id_ffr: {FALSE, str_txk})) >->
     struct(id_bxg: str_bbs$0, id_cgd: str_gxv))
  ),
  id_ict (
    [struct
       (id_acz: str_wqw,
        id_lrb: str_tkh$0,
        id_pmv:
        {NAT,
         str_vxe$0,
         { id_yuk, id_tqp, id_cma, id_wxe | not(str_ufl : str_oyt) }},
        id_gzb: FALSE,
        id_hwr: size(str_odr$0),
        id_mkk: str_loq,
        id_ojp: str_geg),
     str_byu$0,
     str_otc],
    bool
      (not
         (#
            (id_pqh, id_fdc, id_amk, id_mgu, id_rhw, id_epf, id_dhf, id_aio,
             id_ugs, id_kir, id_hfv).
          (not
             (!(id_elk, id_mvz, id_dzs, id_fjs, id_him).
              (#(id_yue, id_ifu, id_yjw, id_kjb, id_rig, id_fij, id_khb).
               (not(str_dey <: "str_cty")))))))
  ),
  id_gil (
    rec
      (id_zhr: str_hrx,
       id_ocv:
       [str_qoe,
        str_prj,
        UNION(id_otb, id_wmg, id_uql).
        (BOOL >= str_oyt'id_fzs| str_xks$0'id_eze)],
       id_ezb: str_bll$0'id_nnm,
       id_dpc: str_ijx$0,
       id_ljn: str_ehn),
    SIGMA
      (id_ixo, id_wkh, id_zxd, id_dix, id_nuk, id_jrb, id_byd, id_bxe,
       id_dts, id_skt).
    (#(id_nbk, id_tpk, id_cep).
     (#
        (id_qqn, id_xzt, id_zii, id_nqg, id_oem, id_nlt, id_sww, id_nje,
         id_daj, id_ukp).
      (str_nke'id_kjc : TRUE) =>
      !(id_gwj).(BOOL > NATURAL))|
     str_dld$0),
    {rec
       (id_zyy: str_ujx$0,
        id_oah: str_vmo,
        id_xqn:
        [str_khy,
         UNION
           (id_mrv, id_nla, id_xre, id_myj, id_han, id_ueq, id_dug, id_utj,
            id_iwi, id_fmt, id_wzd).
         ("str_nbz" > STRING| STRING),
         str_egx,
         str_sgo,
         rec
           (id_qmu: BOOL,
            id_vsp: str_hse$0,
            id_nnj: str_xxk$0,
            id_fxl: str_sca,
            id_arv: str_srr$0),
         str_wqy$0],
        id_apg: bool(str_xkf /: str_lao$0)),
     rec(id_twh: NAT)}
  ),
  id_ihb,
  id_nkq,
  id_gaz (
    {{str_aqz,
      str_ere$0,
      str_pko$0,
      str_rwv,
      UNION
        (id_vnz, id_azm, id_qkp, id_djv, id_bjn, id_ojd, id_hkx, id_odn,
         id_dle).
      (#(id_tsq).(str_rok$0 <= str_eni)| bool(str_iku$0 <= str_gib))
        'id_qea,
      str_swn$0,
      str_cec}
       'id_ype},
    struct
      (id_gpp: str_gtv$0,
       id_oob:
       %
         (id_rmx, id_pyp, id_yru, id_hmp, id_wkd, id_wnu, id_urb, id_ubn,
          id_yem, id_jjc, id_qqw).
       (!
          (id_zwe, id_hfr, id_jht, id_yga, id_shd, id_cpb, id_fkk, id_ioy,
           id_kvn).
        (#(id_kin, id_hak, id_aso, id_jtm, id_mza).
         (#(id_xfd, id_uvo, id_gst, id_zdn, id_yeh, id_uvh).
          (INTEGER /= str_yop)) &
         str_big$0 <<: str_lzx)|
        str_tgm),
       id_ibu: str_joa$0,
       id_vdu: "str_nll",
       id_mdu: str_hqr)
      'id_hen,
    INTER(id_nnj, id_voh, id_hpz, id_gis, id_umd, id_hjh, id_ofv).
    (not(not({str_wwa, TRUE, str_hbo$0, str_hjm$0, INT, BOOL} > INTEGER)) &
     not(str_ubl <= STRING)|
     "str_xih")
  ),
  id_srf (
    bool
      (not
         ({ id_tcl, id_bal, id_bph, id_ozi, id_qzg, id_bim, id_vjw, id_cmj
            |
            str_spt$0 <: str_fwx$0 } >=
          str_wgo$0 &
          (str_try$0 = TRUE <=> NATURAL <<: str_oig$0)))
  ),
  id_nzu (
    rec
      (id_nfe:
       struct
         (id_bio:
          top
            (rec
               (id_qpl: str_okg,
                id_lpc: TRUE,
                id_mpd: str_kss$0,
                id_lks: str_aff)),
          id_cug:
          UNION(id_nxu, id_trb, id_azb, id_jbq, id_avz).
          (str_scp <: "str_jvb"|
           rec
             (id_fyo: str_zwf,
              id_ifi: str_vtz$0,
              id_qgg: BOOL,
              id_prn: str_htu,
              id_kin: str_rvr$0,
              id_hok: NAT1,
              id_koc: 6201,
              id_alm: str_iph$0)),
          id_cvy: str_kzb,
          id_htx: NAT1)),
    (bool(NATURAL1 <<: "str_ngu") ;
     UNION(id_hxd, id_ics, id_gfg, id_vbb, id_yva, id_cws, id_dev).
     (not
        (#(id_aai, id_xfs, id_ucr, id_mud, id_ddm, id_hfx, id_zpm).
         (#
            (id_eps, id_odz, id_rpc, id_fsb, id_hdx, id_gxq, id_pyb, id_tjl,
             id_pna, id_rim).
          (str_ihl /= NATURAL <=> str_mgk <: str_xpw)))|
      str_npg$0))
  ),
  id_ufc (
    struct
      (id_ber: iseq1(str_lvb$0),
       id_hmr: str_xwl$0,
       id_omp:
       [SIGMA(id_dgn, id_fvs, id_wfg). (str_zfo$0 <<: str_dva$0| str_xjz)],
       id_cts:
       struct
         (id_nww: TRUE,
          id_kla: struct(id_mpp: str_xch),
          id_bel: str_nht,
          id_rbo: rec(id_jpr: str_ses$0)),
       id_tyk: str_qyb$0),
    bool
      (#(id_cof, id_arj, id_vev, id_xtf, id_wbj, id_sbj).
       (#
          (id_ioh, id_gnc, id_vlr, id_pfh, id_rtt, id_law, id_crd, id_ovr,
           id_jts, id_fkg).
        ((str_vrr$0 < str_acv & not(str_onk <<: str_euv)) or
         (str_gxo <: str_ydo$0 or str_ioc >= str_bhs$0))))
  ),
  id_qhf (
    (max(FALSE) ;
     rec
       (id_hgr:
        {MININT,
         str_shc,
         ("str_cpa"~),
         str_kgd,
         str_npd$0,
         rec
           (id_omn: str_elp,
            id_nre: str_pok$0,
            id_gqi: str_hiq,
            id_ipx: str_xbp,
            id_ltd: str_glo$0,
            id_gtp: str_raz,
            id_hcq:
            rec
              (id_pyf: str_urf$0,
               id_tqx: str_wdt$0,
               id_mfh: str_atq,
               id_inm: str_dav$0,
               id_ykw: NATURAL1)),
         str_rny,
         str_mog$0},
        id_cjm: INTEGER,
        id_eew: TRUE,
        id_ppo: str_sbo$0)),
    rec
      (id_jnp: str_pcj,
       id_rib: str_jxy,
       id_ewi: str_xzt,
       id_ckg: str_zsm$0,
       id_rzk:
       rec
         (id_xsb: str_boz$0,
          id_dch: str_mov,
          id_uge: str_sqc$0,
          id_htk: str_rad,
          id_itl: STRING,
          id_ioy: []),
       id_trt:
       struct
         (id_ild: BOOL,
          id_njm: str_gxz$0,
          id_hrs: INT,
          id_gxp: {},
          id_uzg:
          { id_udb, id_yld, id_cdv, id_bbr, id_vjt, id_kgy, id_yhc
            |
            not
              (#
                 (id_cot, id_den, id_ydu, id_hak, id_maw, id_rxc, id_alp,
                  id_atb, id_ias).
               (not(str_psf <: str_kbx))) }),
       id_tes: str_jcu,
       id_oyf: {})
  )

USES
  id_hje, id_bxq, id_ppe, id_pat

SETS
   id_pth = { id_pdc, id_gnf, id_snq, id_pfm, id_zov, id_uqb, id_rdo } ;
  
    id_mtf
    =
    { id_hqm, id_qld, id_pqp, id_xuu, id_mvy, id_oty, id_lvf, id_zfx }
  

CONSTANTS
  id_jmg, id_cog

ABSTRACT_CONSTANTS
  id_qou, id_irm, id_uwc, id_qvi, id_qae, id_zdi

CONCRETE_VARIABLES
  id_ugz, id_duz, id_nau

VARIABLES
  id_qzu, id_njl, id_qyx, id_pzi, id_jac, id_mbe, id_tsl

INVARIANT
  !(id_lxs, id_gfd, id_aye, id_gsk).
  (not
     (not
        (not
           (#
              (id_agc, id_cqx, id_rgs, id_wyi, id_nyv, id_ife, id_eyr,
               id_qen, id_nsn, id_kxa).
            (str_dze$0 >= NATURAL1) <=>
            not(INTEGER >= MAXINT)))))

ASSERTIONS
  not
    (#
       (id_sqj, id_cob, id_zze, id_tbj, id_bkp, id_kuo, id_xqq, id_qmn,
        id_slq, id_hhf).
     (#(id_fli, id_qbd, id_vxi, id_wup).(NAT1 /= str_szn$0) or
      !(id_tzo).(str_usv /: INT)) or
     #(id_tuz, id_zip, id_djp, id_bwr, id_cti, id_zbn, id_pgg).
     (str_ete$0 /: []));
  !
    (id_uan, id_nzc, id_nbx, id_jhd, id_age, id_gkq, id_awk, id_lbn, id_hzc,
     id_gbf, id_jyi).
  (#(id_ysp, id_zmi, id_cbw, id_pac, id_cid, id_hku).
   (not
      (!(id_dtp, id_leq, id_itw, id_zfp, id_cfc).
       ((str_tvx <+ str_mzc$0)'id_gad >= str_azc$0))));
  card(str_cbn$0) =
  "str_lgu" >+>
  struct
    (id_her: NATURAL1,
     id_mrl: str_qvl,
     id_hzr:
     {NAT1,
      BOOL,
      str_xtf,
      { id_cly, id_kvs | str_nec : str_vwc$0 },
      NATURAL,
      NAT1,
      str_tlb,
      FALSE}
       'id_qnw)

OPERATIONS
  id_ccd <-- id_mxl (id_tbz, id_plm, id_nin, id_uce, id_itp, id_nge) =
  CASE
    { id_iku, id_pjm, id_ytp, id_xza, id_pby, id_aip
      |
      str_iih =
      struct
        (id_roy: str_ttq,
         id_vuj: str_itp,
         id_oii: "str_pob",
         id_cvd: str_ovb$0) =>
      not(#(id_ohf, id_uyp).(INTEGER <<: str_yoa$0)) }
    OF
    EITHER
      rec
        (id_bis: str_qbx,
         id_tms: str_jmk,
         id_uao: str_zso$0,
         id_zxk: FALSE,
         id_idl:
         {bool
            (#(id_lna, id_qzg, id_ivz, id_xje).
             ({ id_vqe, id_gjg, id_azk, id_ysp | NAT1 : NAT } > INT))},
         id_gil: str_zea'id_tfz,
         id_vyy: {})
    THEN
      id_waf, id_mpv, id_rwx, id_kad, id_jdv, id_dra, id_sgb
      ::
      {(str_zfw ** str_hbd$0),
       struct
         (id_scy: [str_hdp$0, NAT'id_krh, 229, {}, str_kfq$0, str_lfp],
          id_ryg: {str_cyr, str_kiy$0, str_vwy}),
       str_dyb,
       struct
         (id_azy: str_wvv,
          id_myh: str_zwf,
          id_jkn: INTEGER,
          id_ocj: str_enm$0,
          id_ozi: str_urv$0,
          id_vpm: str_wlq,
          id_hyb: str_zmj,
          id_rot: str_ssi$0)}
    OR
      UNION(id_nzd, id_zkc, id_wag, id_xlu, id_lze, id_uth, id_kbw).
      (#(id_vwt, id_ikl, id_vha, id_qvu, id_qau, id_pkf).
       ([str_jpe$0] > MININT~)|
       mirror(str_bbd$0'id_ggl))
    THEN
      ANY
        id_abg, id_rqy, id_ngo, id_owb, id_gsl, id_rmv, id_dti, id_qod
      WHERE
        str_slf /= NAT &
        (not
           (#(id_jfy, id_kab, id_sml, id_bnr, id_rvw, id_vqt, id_gfm, id_uhj).
            (str_frf$0 /<: str_gsg$0)) <=>
         not
           (!(id_dhm, id_uze).
            (!
               (id_ifn, id_mnh, id_jxj, id_pfh, id_xtn, id_mej, id_dxu, id_vao).
             ([] > NATURAL1))))
      THEN
        id_qed'id_xer
        :=
        rec
          (id_kfd: INTEGER,
           id_zqa: { id_zpz, id_dtw, id_gaf, id_cda | STRING <<: str_igm },
           id_pkc:
           bool
             (str_stx$0 :
              struct
                (id_hsi: MAXINT,
                 id_fgs: MININT,
                 id_txv:
                 {str_yew, str_pex, STRING, MININT, NATURAL, str_goy, []},
                 id_jfe: str_ghk$0,
                 id_mwh: str_aqd,
                 id_pxq: str_uww,
                 id_chd: str_equ$0)))
          'id_cut
      END
    OR
      rev
        ([front
            (bool
               (#(id_ohu, id_sie).(str_ozm$0 /<: str_ujk$0) =>
                str_jju <: str_iuv)),
          str_hph,
          str_amb$0])
    THEN
      id_cvy, id_nov, id_ibi, id_qqz, id_oex, id_icc, id_wdi, id_qmh, id_hhj,
      id_wfq
      ::
      bool
        (rec
           (id_izx: str_zci,
            id_nof:
            struct
              (id_ssm: MININT,
               id_yxj: str_ifu,
               id_tjw: str_spo$0,
               id_tet: str_dkk$0,
               id_isc: str_mfv$0,
               id_tgv: str_zyt$0),
            id_sns: str_mid$0) >=
         { id_rlt, id_tbt, id_bvf | {} /: str_rca$0 }'id_vnn <=>
         str_nxp <: str_xoo$0)
    OR
      [rec(id_grw: INTEGER, id_mcn: INTEGER, id_zih: str_goi$0),
       BOOL,
       str_iop$0,
       front
         ((struct
             (id_xgf: NAT,
              id_wwv:
              %(id_cmk, id_nmn, id_juv, id_eiy). (MAXINT /= str_hgc| str_ctv)) ||
           BOOL)),
       TRUE,
       %(id_uyx, id_egl, id_lsg, id_hqj, id_esp, id_rns).
       ([] /= str_xge$0| str_vbn$0),
       NAT,
       str_aqa$0]
    THEN
      skip
    OR
      SIGMA(id_gcz, id_szk, id_dvh, id_ewf, id_mqm, id_kdv, id_grt, id_brq).
      (#(id_zrk, id_zxy, id_bpu, id_naq, id_ghz, id_vuk, id_djo, id_xpu).
       (!
          (id_jjn, id_fvw, id_zjv, id_ont, id_dow, id_tnv, id_ejc, id_yqt,
           id_rrg, id_xze).
        (#(id_fdx, id_frg, id_bkt).(STRING /<: str_bzv$0)))|
       %(id_bvv, id_ucu, id_wrh, id_xey, id_zxn, id_fcu).
       (not(INTEGER = str_haf$0)| str_pkj$0))
        'id_qjv
    THEN
      id_haz, id_dlj, id_iyc, id_hgi, id_lge, id_wwq, id_ssd, id_ilq, id_ylz,
      id_sab :(
        !(id_jzf, id_swi, id_rau).
        (#(id_fqc, id_vho, id_ram, id_yqn, id_mwg, id_meq, id_fcb).
         ({ id_iyi, id_wiv | not(str_ugf < str_jse) } <= str_knz |> str_crs))
      )
    OR
      [bool
         (#
            (id_eyd, id_ujk, id_zyl, id_khp, id_qeo, id_ayu, id_jsy, id_nsw,
             id_rbz).
          (str_ncl <= NAT1 <=> 20 = str_nwn$0)),
       INT,
       str_nxk,
       rec
         (id_mrl: INT,
          id_azh: str_izh$0,
          id_txg: str_ljg$0,
          id_kee: NATURAL1,
          id_alu: BOOL,
          id_wqr: BOOL),
       str_hmx$0,
       str_bip$0]
        [NAT1]
    THEN
      id_ksa, id_bhk, id_pkh, id_gap, id_kyi, id_vhy, id_iii, id_pab, id_vqj :(
        not
          (str_djg /<:
           seq
             ({str_cgb,
               str_xlr$0,
               str_pxt$0,
               NATURAL1,
               MAXINT,
               str_jeq,
               { id_ppe, id_sip, id_tnk | !(id_fme).(str_uon <<: FALSE) }})) <=>
        str_zyj$0 <= str_gkc$0
      )
    OR
      rec
        (id_pny: BOOL,
         id_ogm: str_jda,
         id_irt: NAT,
         id_muu: str_ogl,
         id_dfa:
         {[str_brx, bool(BOOL : str_mav$0), bin(str_beq'id_emz)],
          rel(str_sfw$0),
          NAT})
    THEN
      id_oli, id_xgs, id_kce, id_asx, id_uef
      :=
      rec
        (id_xdr: str_jjt$0,
         id_bmh: str_sdb$0,
         id_bae: str_dch$0,
         id_ctd: NAT,
         id_ehs:
         [str_imy$0'id_sji,
          str_cxq$0,
          bool(str_jux /<: str_nvc),
          UNION
            (id_rxw, id_rbw, id_giv, id_rdw, id_awo, id_jmy, id_vce, id_adb,
             id_tkx).
          (not(MAXINT < [])| {str_gxp, str_wpn, str_yte$0, str_txo})],
         id_kmh: {},
         id_tnc: str_aru,
         id_jtc: str_mys$0)
    OR
      [INTER(id_tox). (str_cut$0 >= NAT1| str_ojo),
       [str_kzp],
       str_ztz,
       first
         (UNION
            (id_tgo, id_wog, id_ylp, id_vew, id_clm, id_zlz, id_erj, id_uxt).
          (str_til$0 <<: str_hup$0|
           struct
             (id_iiw: str_nnn$0,
              id_eeg: str_aow$0'id_iat,
              id_top: str_vqm,
              id_aqx: str_gcd,
              id_gta: str_ree$0,
              id_olw: str_svk)))]
    THEN
      LET
        id_cde, id_ojt, id_jbd, id_ozv, id_sab
      BE
        id_ihk
        =
        PI(id_rle).
        (not
           (!(id_xue, id_cbj, id_kwc, id_uub).(BOOL /= str_lkp$0) <=>
            (str_skq >= TRUE or str_xov$0 < str_hpl))|
         front(str_cbe$0))&
        id_dek
        =
        %(id_alj).
        (#(id_pzw, id_bsp, id_mes).
         ({} : str_ixa &
          not
            (#
               (id_zgz, id_gbj, id_xwg, id_uxl, id_ndh, id_ywh, id_tzu, id_uxk).
             (str_atw /<<: INT)))|
         str_qco$0'id_ipq)
      IN
        CASE
          [str_wyj,
           str_dfx$0,
           SIGMA(id_csj, id_oks).
           (#
              (id_mtv, id_nzx, id_fkw, id_kps, id_hpw, id_kvq, id_muu,
               id_ypk, id_pwc, id_hqm, id_jxg).
            (str_sqs <<: str_nbv$0) or
            str_cvu /<: str_fws$0|
            struct
              (id_lqb: str_yxl,
               id_dau: str_obb,
               id_vcd: str_oqa,
               id_vgs: str_lhc$0,
               id_cwh: INTEGER,
               id_npl: str_amk$0)),
           str_iye,
           str_vru]
          OF
          EITHER
            rec
              (id_zal: str_gtq$0,
               id_tcx: str_ewu$0,
               id_tua: INTEGER,
               id_odd:
               struct
                 (id_eik: str_doj$0,
                  id_fvs: BOOL,
                  id_wpx: (str_fai$0 +->> 6),
                  id_ncf:
                  %(id_esc).
                  (str_wlq /<: str_wpr$0|
                   rec
                     (id_sfb: BOOL,
                      id_sbq: str_biz$0,
                      id_xmz: str_tpq,
                      id_nts: str_jow$0,
                      id_zeu: INTEGER,
                      id_mvv: str_gzw$0,
                      id_zty:
                      struct
                        (id_oul: str_xmq,
                         id_pxx: str_uqk$0,
                         id_kmv: str_jsd$0,
                         id_awv: str_ytn))),
                  id_ctv: (str_xmi$0 <<| {}),
                  id_ddh: str_emj,
                  id_bih: "str_ojv",
                  id_aqy: str_och),
               id_tbd: str_igs,
               id_zwk: str_rcq$0)
          THEN
            SELECT
              not
                (rec(id_fdt: str_uih, id_mmy: str_rvd$0, id_inz: str_pmr$0) /=
                 {} =>
                 !(id_bzq, id_atj, id_par, id_irv).
                 (#(id_asj, id_ztq, id_ymp).(!(id_tzy).(NAT1 : STRING))))
            THEN
              id_mqk, id_izn
              ::
              last
                ({ id_umv, id_dne, id_dyt, id_mmf, id_puo, id_lhu, id_uxp,
                   id_ryv, id_ghn, id_mnp
                   |
                   !(id_ztc, id_tqb, id_lag, id_ayz, id_sbv, id_goi).
                   (NAT1 < str_yyf &
                    !
                      (id_txu, id_qnm, id_try, id_ajl, id_gzk, id_wds,
                       id_zao, id_qik).
                    (!
                       (id_onl, id_etw, id_ufw, id_ngd, id_iyr, id_sjs,
                        id_xmf, id_lhh).
                     (str_ero$0 <<: str_nuo$0 & str_hrj$0 /= str_mfi))) })
            WHEN
              MAXINT /|\ rec(id_lti: card(FALSE)'id_elc) <=
              right(bool(str_wyn$0 /<<: str_dzx))
            THEN
              id_tpo, id_erk, id_rpm, id_cay, id_jrf, id_bkm, id_amg, id_qcb,
              id_nxd :(
                not
                  (not
                     (not
                        (#(id_wbo, id_evd, id_xnq).
                         (bool(str_tai$0 >= str_kyn) /<<: str_nlm =>
                          str_fkx /: str_zjm))))
              )
            WHEN
              #
                (id_ctp, id_hdg, id_vjs, id_auy, id_vbr, id_fuq, id_yqd,
                 id_glu).
              (not
                 (not
                    (#(id_agq, id_mue, id_xlr, id_tgk).
                     (str_qvc$0 /<<: str_wsk)))) <=>
              not(str_zjd /<<: [] or str_jyu : str_jzh$0)
            THEN
              skip
            WHEN
              #
                (id_qen, id_kww, id_xwa, id_kbh, id_hrl, id_ebe, id_edc,
                 id_akm, id_zei).
              (!
                 (id_qon, id_wkw, id_alx, id_iuy, id_drl, id_ovk, id_zun,
                  id_flz, id_ejj, id_ytw).
               ([] >=
                iseq
                  (bool
                     ((NATURAL /<: str_chz$0 => MAXINT /<: str_nph) =>
                      TRUE : str_pcp$0))))
            THEN
              SELECT
                #(id_dqa).
                (not
                   (str_zez$0 : str_syq <=>
                    (#(id_esy, id_jpw, id_jfm, id_aeb, id_bmy).
                     (str_ghj = str_xps) or
                     #(id_pzp, id_rag, id_dec).
                     (#
                        (id_xea, id_bph, id_woa, id_pcu, id_koy, id_jxi,
                         id_ksa).
                      ({} <= str_hmh$0)))))
              THEN
                id_fvi, id_jla
                :=
                bool
                  (not
                     (#
                        (id_rvu, id_rgu, id_jri, id_tfd, id_jey, id_gba,
                         id_hxa, id_jbj).
                      (rec
                         (id_yqc: INT,
                          id_mlq: str_ghz,
                          id_msd: str_vmy,
                          id_uzm: str_vaw,
                          id_gfh: str_xbp$0,
                          id_tfl: str_vrl$0) <:
                       str_urr or
                       str_bnw$0 : str_rva$0))) -
                str_kcj
              WHEN
                (#(id_ggm, id_rqn).
                 ({str_cbv$0, str_ssg, str_lnk, [], MAXINT} <:
                  SIGMA
                    (id_vnw, id_fwq, id_hgs, id_nue, id_kmh, id_voz, id_vyp,
                     id_xeu, id_fcn, id_cpq).
                  (str_yjb$0 : str_nzc| str_tdc)) =>
                 FALSE /: str_bsq$0) &
                (str_qlq = str_zhp => str_eci > str_mlk$0)
              THEN
                id_lzg, id_fpm, id_qsy, id_nfy, id_qmy, id_wni, id_qtq,
                id_rqd, id_dqn
                ::
                {rec
                   (id_dii:
                    {str_elq$0,
                     {},
                     NATURAL,
                     str_qoe,
                     str_vqj$0,
                     struct
                       (id_yni: "str_oae",
                        id_tlg: str_vei,
                        id_zpy: str_xqa$0'id_ywi,
                        id_yff: TRUE,
                        id_jdm: INT,
                        id_suq: NATURAL,
                        id_ast: STRING,
                        id_hdn: str_sau),
                     str_ltn$0}),
                 rec
                   (id_naa: str_nfa,
                    id_wly: {},
                    id_fnd: [],
                    id_qvi: str_dst,
                    id_ekc: TRUE,
                    id_ryf: str_jzm),
                 STRING'id_cdk}
              WHEN
                (str_clr$0 -> NATURAL) ..
                [str_sfp, NAT1, str_xio, str_yit, {}] /<:
                SIGMA(id_wyr, id_ykz).
                (str_gyb$0 /<:
                 UNION(id_jvs, id_uhw, id_pua, id_kta, id_exj, id_cjk).
                 (str_elb < str_hlz| MININT)|
                 str_dux$0)
              THEN
                skip
              WHEN
                #(id_pjw, id_ggt, id_htd).
                (#(id_vid, id_mjg, id_siv, id_fex, id_fsa, id_epz, id_dle).
                 (not
                    (not
                       (str_bqi$0 /<<: str_gik =>
                        !(id_tpt, id_alg, id_pgk, id_bpi).(TRUE /<: str_uln)))))
              THEN
                id_vpx, id_mfd, id_klu, id_kxl, id_csy, id_eki, id_rsh
                ::
                {STRING,
                 %
                   (id_quz, id_edi, id_aee, id_brh, id_oyr, id_vcg, id_yxf,
                    id_ujx).
                 (str_oua : str_aiq$0| str_qpb'id_azh),
                 (struct
                    (id_uyx: str_tnq$0,
                     id_dpk: {str_quy$0, str_pdu, NAT1, str_ejn$0, str_job},
                     id_rie: str_ubh,
                     id_mdc: str_bsn$0,
                     id_uwk: str_fhx,
                     id_roi: str_dgz,
                     id_cjk: STRING) /
                  (str_yru * MININT))}
              WHEN
                !(id_xnf).
                (!
                   (id_ved, id_znb, id_nxz, id_gkj, id_rfx, id_omf, id_qoz,
                    id_win, id_arg).
                 (not(not([str_qdf, str_kpb'id_cqc] <: INTEGER))))
              THEN
                id_neo, id_xwi, id_duq, id_tyc, id_vzd, id_okl, id_wvm,
                id_pjj, id_bhb
                ::
                [rec
                   (id_kyu: MAXINT,
                    id_jzm:
                    [FALSE,
                     str_lwb,
                     str_gib,
                     36,
                     str_aam$0,
                     str_swl,
                     str_qrx$0,
                     tree(str_agl$0)],
                    id_snl: str_qap,
                    id_mnx: str_hry$0),
                 str_nlo$0,
                 INTER(id_mti, id_xaq, id_ugw, id_cxe, id_lse).
                 (str_smg$0 : str_jff$0| str_bpl$0),
                 TRUE] <|
                [TRUE, str_psh$0, INTEGER, str_vtj, TRUE, str_mux, str_rta]
              WHEN
                BOOL <<:
                last
                  (top
                     ({rec(id_yec: str_kkb$0, id_abk: TRUE, id_sot: INT),
                       NATURAL,
                       "str_dwu",
                       str_wsj$0,
                       str_tag,
                       str_sae,
                       str_mss$0}
                        'id_mid
                        'id_pha))
              THEN
                id_mbx'id_xmd
                :=
                [rel(str_tdp),
                 str_bvz,
                 { id_mkh, id_ptv, id_rio, id_kvv, id_ejm, id_jok, id_mtj,
                   id_ndq, id_jut, id_uui, id_xrw
                   |
                   str_xqe$0 /: str_skq },
                 struct
                   (id_elk: str_svu,
                    id_kam: mirror(str_nzo$0),
                    id_wde: str_egt,
                    id_bmi: str_qpj,
                    id_tqq: MAXINT,
                    id_yyl: {}),
                 [str_fwp$0,
                  str_wcy,
                  str_zxe$0,
                  { id_gac, id_cjt, id_fjx, id_cup, id_icu, id_dln, id_sot,
                    id_hde, id_qfm, id_qks, id_men
                    |
                    str_kpf$0 <= str_dgj }],
                 str_ero$0,
                 str_gws$0]
              WHEN
                not
                  (bool(str_omh$0 = str_mcy$0'id_xdc or {} >= str_ewr) :
                   NAT1 .. str_rne$0)
              THEN
                skip
              WHEN
                #
                  (id_qcn, id_npx, id_nzn, id_iav, id_hoo, id_wca, id_zxo,
                   id_lvm, id_izo, id_itv).
                (not
                   (not
                      (!
                         (id_hsj, id_bkl, id_qis, id_iur, id_dbu, id_hot,
                          id_jyl, id_isi, id_nve, id_bwr, id_nti).
                       (([] /<<: str_huu$0 & str_awo$0 /<<: {}) =>
                        not(INTEGER /<: str_gbh)))))
              THEN
                id_mqg'id_qeh
                :=
                rec
                  (id_aug:
                   card
                     (rec
                        (id_xbo: str_jdj'id_tms,
                         id_dvz: str_zed,
                         id_chf: str_acd$0,
                         id_nkc: str_pgs,
                         id_kkx:
                         bool
                           (!
                              (id_gnf, id_bck, id_uec, id_ywd, id_udz,
                               id_nxj, id_psr, id_hwl).
                            (MININT /<<: str_ohf)),
                         id_jaa: str_ypx,
                         id_kwe: str_eao$0,
                         id_zox: NAT1))
                     'id_rpg)
              ELSE
                skip
              END
            END
          OR
            rec
              (id_gbv:
               rec
                 (id_jfz:
                  [NATURAL,
                   STRING,
                   MININT,
                   INTEGER,
                   rec
                     (id_vef: str_zts,
                      id_bjf: NAT1,
                      id_mdo:
                      {rel(str_hkm),
                       str_tfd,
                       str_ejb$0,
                       str_fwm,
                       str_fdb,
                       str_dhn$0}),
                   "str_zni"])
                 'id_wgb,
               id_aop: str_iqx,
               id_bxp: str_nwo$0,
               id_raz: str_oyb,
               id_wex: str_rjz)
          THEN
            WHILE
              bool
                (!(id_vfi, id_hbl, id_mcj, id_nwr, id_tmh, id_rrf, id_jso).
                 (not
                    (not
                       ((NAT /= MININT <=> str_frj >= NATURAL1) or
                        str_zev : MININT)))) /:
              MININT
            DO
              id_url, id_qrq, id_lpc, id_xpt, id_kah :(
                struct
                  (id_ppu: [BOOL, str_rkb, MAXINT, {}, []],
                   id_peq: str_qcz,
                   id_dkd: (NATURAL1 <+ FALSE)'id_zqd,
                   id_wfm:
                   struct
                     (id_uoo: str_hmi,
                      id_ura: str_atw,
                      id_bjx: str_nuf,
                      id_bjk: NAT1,
                      id_guc: NAT,
                      id_qeh: 346'id_wqe,
                      id_nwx: str_uod$0),
                   id_gll: str_pjy,
                   id_ivu: str_nac$0,
                   id_ppp: STRING) /<:
                INT
              )
            INVARIANT
              #(id_iaj, id_rdt, id_pjs, id_dbu, id_ekp, id_cnw).
              (#(id_pwj, id_vuk, id_lbr, id_znj).
               ({{[FALSE, str_tvj, str_ebz, str_kxf$0, str_pzn, str_mdt$0,
                   NATURAL, {}],
                  89}
                   'id_tkd,
                 str_pjy,
                 str_qzi,
                 INTEGER} :
                str_ttn$0))
            VARIANT
              [bool
                 (id(str_jsc +->> str_sce) <:
                  INTER(id_trj, id_bov, id_fke, id_fra).
                  (str_rkr /= str_saf| str_puj$0)),
               INTER(id_tbe, id_tgk, id_gmx, id_sjf, id_qal, id_tvo, id_puv).
               (str_bmm <: TRUE| str_gup)]
            END
          OR
            [id(bool(str_efo <: str_sni)'id_ooq),
             ([] <+ MININT),
             str_rba,
             { id_dex, id_izw | MAXINT : str_ggc$0 }'id_wko]
          THEN
            id_qwe, id_cxu, id_ltg, id_rtg, id_ast, id_nbl, id_ard, id_bxx,
            id_unz, id_mhf, id_mvl
            ::
            ({ id_peq, id_kmc, id_lba, id_jsd, id_fxz, id_qdo, id_lkm,
               id_bez, id_vhn, id_awq, id_qpk
               |
               %(id_nsn, id_nei, id_uez, id_dlf, id_lhl). ([] : {}| BOOL) /<<:
               rec
                 (id_uxq: str_bvi$0,
                  id_fvg: str_jxm$0,
                  id_eeq: str_jbs,
                  id_qqn: str_msw$0,
                  id_ftr: iseq1(MAXINT)) } ||
             { id_vax, id_puc | str_xix$0 >= MAXINT })
          ELSE
            skip
          END
        END
      END
    ELSE
      id_eeq, id_ebh, id_yef, id_jic, id_xwm, id_fha, id_twq, id_edg, id_kdz,
      id_uzd, id_vbg
      ::
      bool
        (not
           (!
              (id_vmi, id_epq, id_mlw, id_wcg, id_kqx, id_sfi, id_rrl,
               id_lph, id_xml, id_bxh, id_dse).
            (INTER
               (id_zzo, id_pgz, id_veq, id_rfh, id_hlb, id_hon, id_zqy,
                id_ofj, id_jsv, id_ctz).
             (str_epj$0 <: str_nhf$0| str_irs) :
             { id_hrb, id_anf, id_wgo, id_nxn, id_fte, id_dqc, id_dwn,
               id_gqr, id_avk, id_rls, id_xfi
               |
               not(str_tvl$0 <: NATURAL) })))
    END
  END;

  id_bel, id_lfa, id_dol, id_xvc, id_llw, id_dtj, id_tuw
  <--
  id_yqh (id_bps, id_bfd, id_qot, id_tod, id_dap)
  =
  PRE
    !
      (id_zru, id_nwc, id_zok, id_fig, id_exa, id_efa, id_rcx, id_csp,
       id_lej, id_rdq, id_yvf).
    (!(id_jsb, id_mnc, id_vsk).
     (iseq(str_phz$0) <<:
      struct
        (id_kyi: str_ikr$0,
         id_bmw: str_kxo$0,
         id_vco: str_tmr$0,
         id_yxs: str_dja$0,
         id_vec:
         [str_ras$0, str_sii, str_wma$0, str_orc$0, str_jvp, NAT1, str_fky$0,
          str_fgp]
           'id_bxr)))
  THEN
    ASSERT
      not
        (struct
           (id_jtj: INTEGER,
            id_wxd: str_zsx$0,
            id_ntj: INT,
            id_yox: str_tok,
            id_umk: str_avb$0,
            id_ipp: str_jjr,
            id_mnv: str_aju,
            id_mlu: NAT1) =
         UNION(id_pwm, id_fkj).
         (str_ixj$0 /<: STRING|
          [str_brq,
           str_xwe$0,
           str_qnr$0'id_erl,
           [MAXINT, NATURAL, str_pki, str_mpf$0, str_cpa$0, str_sbz, FALSE,
            str_baf],
           FALSE]))
    THEN
      SELECT
        !(id_vmu).
        (!(id_bre, id_ztu, id_dcl, id_ira, id_iry, id_czv, id_cex, id_oen).
         (bool(str_ctr$0 <= FALSE) <:
          UNION(id_nar, id_jjj, id_xrh, id_wkc, id_xte, id_slf).
          (str_dug /<: str_svs| str_pap)) <=>
         str_ful /= str_nmj)
      THEN
        ANY
          id_xcy
        WHERE
          #(id_tgn, id_lro, id_enb, id_sbk, id_iup, id_wbh).
          (#(id_yzo, id_veu, id_ihw, id_wah).
           (#(id_lsh, id_fxr, id_veo, id_czx, id_qng, id_aaz, id_ykp).
            (!(id_hci, id_okc, id_tnf, id_ghh, id_bgw, id_kfl).
             ((#
                 (id_vxr, id_ryw, id_ijz, id_pax, id_bri, id_qai, id_hdw,
                  id_otz, id_bnp).
               (str_ckn >= str_yhi$0) <=>
               "str_ikt" <= NAT) <=>
              str_fck$0 < NATURAL))))
        THEN
          ASSERT
            not
              (#
                 (id_wwh, id_zcm, id_xpa, id_irr, id_onc, id_pdj, id_unr,
                  id_mam, id_mlk).
               (str_kxu'id_puc <<:
                [str_wmw$0,
                 NAT,
                 FALSE,
                 TRUE,
                 str_qpz,
                 str_bzt$0,
                 struct
                   (id_qaw:
                    { id_qrh, id_bjq, id_cyj, id_xel, id_sif, id_qea, id_uos,
                      id_kfk, id_xuk
                      |
                      str_ymc$0 <= str_mjt },
                    id_mrd: [],
                    id_qwk: NATURAL,
                    id_mmb: str_xei,
                    id_int: str_iyp,
                    id_bcy: BOOL,
                    id_emj: str_but,
                    id_gir: INT),
                 STRING]))
          THEN
            PRE
              !(id_phg, id_irw).
              (not
                 (#
                    (id_rva, id_fqg, id_yso, id_ogn, id_nvr, id_zvf, id_ezv,
                     id_agh, id_xkw, id_xtp).
                  (not
                     ({str_hee$0,
                       { id_fup, id_uur, id_fzg | str_dny /<: MAXINT }} >
                      str_csm))))
            THEN
              ASSERT
                str_cof /<: STRING =>
                rec(id_lzs: NAT1, id_ece: NATURAL, id_ozy: FALSE) :
                str_szs /\
                {{ id_lmc, id_ppy, id_sng, id_gzy
                   |
                   !
                     (id_jis, id_wwy, id_tea, id_yjp, id_itl, id_kdf, id_sub,
                      id_hri, id_eeh, id_zzn, id_srf).
                   (NATURAL /<: str_oxi$0) }}
              THEN
                id_wfk, id_rxu, id_kfw, id_ciu, id_cdm, id_std, id_mvo
                <--
                id_qol
                  ([bool
                      (!(id_mnv, id_vdw, id_tsd, id_eqg, id_pzn, id_atv).
                       (str_yrh$0 <<: str_tsu)),
                    (NATURAL1 ^ str_alj$0),
                    str_tpz$0,
                    [{ id_wwt, id_ppu, id_gql, id_gog, id_nfx, id_fci,
                       id_yql, id_fko
                       |
                       MAXINT < MININT },
                     str_ldz$0,
                     str_msp$0],
                    str_zlz$0,
                    bool(str_yfh <: str_oap$0)],
                   (min
                      (iseq1
                         (INTER
                            (id_psg, id_fue, id_ldf, id_yph, id_mbu, id_bus,
                             id_mpo, id_bjj).
                          ("str_yqm" < str_cwb$0|
                           INTER
                             (id_cww, id_shk, id_lcu, id_gzj, id_jgl, id_hnj,
                              id_hza).
                           (str_kqu : TRUE| 1))))
                      'id_hog <|
                    seq(str_gqt)),
                   %
                     (id_tgo, id_omd, id_ilu, id_iui, id_qbs, id_ida, id_ldw,
                      id_nvg, id_hgm).
                   ({} < MAXINT|
                    [UNION
                       (id_uzh, id_ojm, id_ywj, id_gpc, id_pnx, id_yxt,
                        id_gkn, id_wvt).
                     (str_qpn$0 <: str_tzn|
                      { id_qre, id_ixo, id_tbt
                        |
                        str_pdg$0 <=
                        %
                          (id_zxt, id_zid, id_jyl, id_tzx, id_nmu, id_fbs,
                           id_blf, id_brn, id_jnz, id_hfv).
                        (str_uet <: 88| str_nlc) }),
                     BOOL])
                     'id_kqg)
              END
            END
          END
        END
      END
    END
  END;

  id_vkn, id_nlw, id_iqm, id_jxo, id_wwp, id_meq
  <--
  id_tkc (id_jhi, id_mfn, id_foa)
  =
  PRE
    { id_nvp, id_zyu, id_tyz | str_bbj$0 >= str_wed } ><
    [str_scw$0,
     str_qwk$0,
     ({BOOL, str_vnf$0, str_yfu, str_mgo, {}} +-> str_kxb$0)] >=
    str_stb
  THEN
    SELECT
      bool(str_hab$0 <= FALSE) /<:
      rec
        (id_whu: (str_ied <-> str_phh$0),
         id_cvx: 488,
         id_eou: str_jud$0,
         id_vaf: NAT1'id_fwh,
         id_qrf:
         [str_zws,
          INT,
          str_nss$0,
          INTER(id_kib). (FALSE /: str_azm$0| str_kwk$0),
          str_hbl$0])
    THEN
      id_ivq, id_qop, id_skc, id_trt, id_icx, id_vam, id_isr, id_qcq, id_lkk,
      id_jwj :(
        {NATURAL1,
         ran([str_pat$0, MAXINT, BOOL, STRING]),
         str_xtk$0,
         { id_kjj, id_zfs, id_ugf, id_jej, id_jwh | str_sbi /: str_qcl$0 },
         rec
           (id_rwu: str_efr$0,
            id_rgx: FALSE,
            id_odr: [str_hny, str_jhp, 890, str_tvb, str_wno, str_axn$0],
            id_jji: str_lib$0)} /<<:
        NAT
      )
    WHEN
      not
        (str_phh <<: INTEGER or
         #(id_acr, id_ona, id_peq, id_evu).
         (not(NATURAL1 /= "str_sbn") =>
          !(id_oev, id_epy, id_kdh, id_vxe, id_fbs).([] /<<: BOOL)))
    THEN
      SELECT
        bool
          (#(id_guh, id_lkc, id_chd, id_afa, id_ssi, id_kcz, id_pei, id_ddj).
           (#
              (id_ubs, id_ncb, id_rjd, id_zpa, id_oct, id_fcf, id_qgs,
               id_pmq, id_dlp, id_bdv, id_glw).
            (#(id_tdd, id_koh, id_koj).
             (#
                (id_ted, id_ogy, id_uhg, id_mdg, id_kxu, id_xlv, id_eiq,
                 id_anh).
              (str_uts /<: str_yvh))))) >
        str_ruc$0 >+> NAT
      THEN
        id_tkm, id_xaa, id_xlt, id_drl, id_vus, id_gad
        :=
        (SIGMA(id_abf, id_lce, id_bsg, id_mml). (FALSE >= str_lyq| str_akt)
           'id_rki ><
         {str_nde$0,
          bool(str_vvs$0 = str_anl),
          %(id_huh, id_gbb, id_jey, id_hzx, id_bzt, id_cpg, id_hcj).
          (str_csp$0 <<: str_mol| str_hpj),
          str_lgw$0,
          str_qdq,
          str_nez$0,
          str_zax,
          str_zoj})
          'id_ymv
      WHEN
        #
          (id_alz, id_qtc, id_gxl, id_oax, id_zcq, id_dcl, id_iav, id_rhd,
           id_hie).
        (str_yuf /= MAXINT &
         #(id_jgf, id_vgn, id_kon, id_crf, id_qst).
         ((str_lib$0 /<<: NAT1 &
           !
             (id_yjs, id_vqm, id_ulx, id_hbs, id_qgo, id_neo, id_ecm, id_igo,
              id_ppy).
           (str_xaz : str_knf)) =>
          str_iyn$0 > str_kvr$0))
      THEN
        id_bpk, id_dee, id_qrw
        <--
        id_qrl
          ((bool
              (bool(not(not(NAT1 : MAXINT => STRING <: str_stp$0))) >=
               str_xvv) *
            NAT),
           ({struct
               (id_vgu: INTEGER,
                id_wou:
                min({bool(str_imr = str_zxg), str_whf$0, INTEGER})'id_ojn)} -->>
            NAT),
           UNION(id_opx, id_lyh).
           (!(id_fdo).
            (#(id_brd, id_iqh, id_xti).
             (#(id_kis, id_sas, id_lae, id_exp, id_wmi, id_mmf, id_cjh).
              (not(str_tuf >= str_cgj$0) or
               #
                 (id_ugy, id_kgz, id_htb, id_zpq, id_owm, id_fft, id_ytx,
                  id_rdk).
               (str_bim <<: str_vda))))|
            TRUE),
           perm
             (rec
                (id_wwc: str_naz$0,
                 id_bkk:
                 rec
                   (id_bhg: {str_uoz$0, str_pwp, INT, str_fbg$0, NATURAL},
                    id_cjv: str_rbt$0,
                    id_zlv: str_ggn,
                    id_iqu:
                    SIGMA(id_avj, id_dzb, id_nrj).
                    (str_scp$0 /<: str_xsc| str_ovm$0),
                    id_hhi: str_lba),
                 id_yub: str_jyz$0,
                 id_djv: bool(str_bep$0 /<<: []))),
           rec
             (id_teo:
              ({ id_mbx, id_msu, id_eno, id_aka | not(NAT /= []) } ||
               [BOOL,
                str_usz$0,
                INT,
                SIGMA(id_vvo, id_tiu, id_kgq, id_hjb, id_jye, id_kby).
                (str_fkh <= str_jhh| TRUE),
                str_kuq]),
              id_cxm: str_fch),
           POW
             (%
                (id_bkq, id_bjj, id_uhy, id_phf, id_keb, id_hje, id_wmj,
                 id_ibb, id_sic, id_dgq).
              (not(NATURAL >= str_rzs$0)|
               PI(id_lpj, id_yxm, id_unk, id_kiu, id_mxz, id_mxj, id_wky).
               (not
                  (!
                     (id_thl, id_kdt, id_iiz, id_nvl, id_eed, id_avr, id_gst,
                      id_rfz, id_xld, id_xdl).
                   (str_swn$0 : NATURAL))|
                str_bpt$0))),
           {INT,
            TRUE,
            str_ryt$0,
            struct
              (id_tnp: 50,
               id_orz:
               (NAT <|
                { id_tqn, id_ynp, id_cfy, id_cfu, id_xwi, id_sjs, id_hgq,
                  id_vcr
                  |
                  str_vee$0 <<: str_osj })
                 'id_ypc,
               id_mqu: str_mhs,
               id_xxg:
               SIGMA(id_oks, id_qoz, id_ckq, id_coq, id_idm).
               (FALSE /= str_hqx| NATURAL1)),
            1,
            { id_gsa, id_kfq, id_nlw, id_gby, id_tjr | "str_dwc" <: INTEGER },
            MAXINT,
            str_zsb$0},
           rec
             (id_kjz:
              bool
                ({ id_nqa, id_zod, id_zbl, id_ran, id_spt, id_bsj
                   |
                   3 /<: [str_aon, str_aaa$0] } >=
                 struct
                   (id_ipw: str_pgh,
                    id_tyu: str_awh,
                    id_xet: str_vdy,
                    id_bdb: str_hwl$0,
                    id_stc: str_qct$0,
                    id_dcg: 2204,
                    id_jof: str_yxq$0))),
           rec
             (id_acw:
              rec
                (id_vvq: ran(str_awv),
                 id_rpi:
                 [str_gxu,
                  str_sbf$0,
                  str_xot$0,
                  str_xaz'id_cig,
                  MININT,
                  str_ffq$0,
                  str_ptx,
                  str_one],
                 id_xoj: str_ife,
                 id_nvc: str_swg$0,
                 id_xie: str_sdw$0),
              id_jdb: (str_qrl$0 <<| STRING),
              id_yvi: str_hrn,
              id_txl: str_wfw,
              id_znw: (str_zeq$0 <| str_bkk$0)),
           [{str_eak, str_cat$0, str_fjy}'id_ccz,
            struct
              (id_xiw: infix(MAXINT /|\ str_xxt),
               id_vfu: MININT,
               id_mol: str_hxz,
               id_edk: STRING,
               id_hkt: str_vel,
               id_ifn: MAXINT),
            [str_ijm$0, str_rtj, str_tdh$0, INTEGER, [], str_jqo, "str_rkf",
             str_urz],
            str_bjr,
            str_xyp$0])
      WHEN
        { id_igj
          |
          !(id_waq, id_cbj).(not(TRUE /<: str_pjw$0) => NAT1 /<<: str_dnx) } /<:
        str_feh'id_cnz'id_yax
      THEN
        id_qvv, id_ouk, id_yyc, id_xvh, id_aay, id_qmw, id_nmv, id_imb,
        id_xvn
        <--
        id_apn
          (INTER
             (id_cbj, id_mke, id_nmw, id_tou, id_yjx, id_ykt, id_rkg, id_urd,
              id_kus).
           (str_dhq$0 <= str_ljv$0|
            [str_aht,
             BOOL,
             struct
               (id_nwg: INT,
                id_ood: str_soc$0,
                id_skz: str_lfb,
                id_ayl: MININT,
                id_buj: NAT1),
             bool
               (PI(id_htx, id_oax, id_olb).
                (not(str_kej /<: str_wrk$0)| str_yom$0) <=
                str_jsk$0),
             str_eha,
             str_lil,
             BOOL]),
           rec
             (id_bfx:
              { id_tqq, id_blr, id_wkt, id_cyy, id_ryg, id_rou, id_kbu,
                id_ogw, id_wnk, id_ebd, id_mlf
                |
                not
                  (!
                     (id_bmq, id_bbt, id_gds, id_xtl, id_lbp, id_rsv, id_vyw,
                      id_jfo).
                   (!(id_yzw, id_zcv).(TRUE = str_log))) },
              id_ajw: [str_yrx, str_iip, [[]]]))
      WHEN
        #(id_yks).
        (#
           (id_weg, id_wec, id_rqg, id_kra, id_hee, id_hih, id_zvy, id_kcn,
            id_yjw, id_nua).
         ((NATURAL <: TRUE <=>
           !(id_vjh, id_qkc, id_hqm, id_qbr, id_snx).(STRING /<: str_qiw$0)) &
          str_rmz < str_zfx$0)) =>
        (NAT1 <<: STRING or TRUE >= str_mtl$0)
      THEN
        IF
          struct
            (id_swe: str_ici,
             id_zkd: INT,
             id_rdd: MININT,
             id_xsf:
             PI
               (id_hlk, id_uac, id_ouk, id_mjg, id_xvw, id_rpc, id_afa,
                id_yhc, id_syj, id_ubl, id_pth).
             (str_fdo <= str_xry$0| NATURAL1),
             id_cec: NAT,
             id_enr: str_jjm$0) :
          struct
            (id_qqy:
             { id_fgi, id_yzi, id_iws, id_gbk, id_htj, id_cjk, id_tot,
               id_god, id_dnh, id_iam
               |
               !(id_rrf, id_pet, id_pdq, id_ssb, id_jrd).
               (str_unq$0 /<: str_vmx$0) })
        THEN
          id_ouz, id_ehx, id_los
          <--
          id_ikm
            (fnc
               (struct
                  (id_fjs:
                   {id
                      (rank
                         ([str_tng, MAXINT, str_skv, INTEGER, str_egu$0,
                           str_wzp$0]))},
                   id_zol: {str_cnf$0, str_zbj$0, {}, str_niq$0, str_okg},
                   id_nrh: NAT1)),
             rec
               (id_sms:
                {BOOL,
                 "str_jff",
                 str_vnx,
                 str_luy,
                 SIGMA(id_jve, id_ool, id_xiw, id_ucz, id_iet, id_nbb).
                 (str_umg$0 = MININT| NATURAL1),
                 str_fex$0,
                 bool(str_ciw$0 /: str_gjz$0),
                 str_iwo$0},
                id_yeo:
                rec
                  (id_jby: str_brs$0,
                   id_dxa: str_ldz$0,
                   id_hbk: str_vyy,
                   id_syh: [FALSE],
                   id_fri: str_mob$0,
                   id_vmg: str_ldg),
                id_qns: str_nbe,
                id_puh: str_qqj$0,
                id_duy: {str_jwn, str_pij$0, 1, INT, str_cvz$0}),
             {PI(id_fbj, id_xbi, id_imh, id_ift, id_bdw).
              (INTEGER /: str_xhf$0| str_rpv$0),
              seq
                ({ id_yqr, id_ecb, id_tdz, id_xgk, id_pqi, id_jln
                   |
                   !
                     (id_wkd, id_xan, id_kun, id_qmb, id_bps, id_grg, id_dkd,
                      id_okp, id_jpd, id_kqx).
                   (str_iil /= str_cnm or str_xlb$0 < str_cpx$0) }),
              bool(FALSE <: str_opa$0),
              str_hou,
              str_wwc$0},
             bool
               (!(id_ndz, id_uia, id_tre, id_tqj, id_clp).
                (NAT1 <:
                 struct
                   (id_ttj: str_bfh$0,
                    id_bmp: NATURAL,
                    id_dvd:
                    struct
                      (id_jkk: bool(str_boy$0 : str_ueu)'id_acu,
                       id_vcb: str_fyk),
                    id_jor: STRING,
                    id_dam: NAT1))),
             btree
               (%
                  (id_cwl, id_btc, id_ekd, id_clv, id_jlm, id_yga, id_xfy,
                   id_azb).
                (str_ldc /<<: str_bkp <=>
                 !
                   (id_ail, id_iir, id_sum, id_bpr, id_jdo, id_tco, id_iiq,
                    id_ejt, id_hug, id_ucw, id_lsb).
                 ({ id_kvt, id_uxa, id_ker, id_hzw | str_ryt /<: [] } >=
                  str_gah)|
                 str_vgq))
               'id_ncf,
             rec
               (id_ids: str_wzn,
                id_hzo: (str_sxh$0 |> MININT),
                id_rdv: str_spm,
                id_ydj: 4,
                id_vvi: str_cdw$0,
                id_nuj:
                struct
                  (id_yzt: max(str_gvj$0),
                   id_bmr: "str_xer",
                   id_frk:
                   UNION(id_phl, id_all, id_ukc, id_xdc, id_mxa, id_hfr).
                   (#(id_mns, id_omf, id_iuo, id_mou).(str_bww$0 /= NATURAL)|
                    INTEGER),
                   id_mgy: str_egg$0,
                   id_pky:
                   UNION
                     (id_jeh, id_kmv, id_not, id_txo, id_wrf, id_uko, id_axj,
                      id_uad, id_bjn, id_lqf, id_sll).
                   (str_eeq$0 <<: str_nqn$0| str_pok)),
                id_str: NAT1,
                id_dcp: str_akg$0),
             UNION(id_lgf, id_gtx, id_dgw, id_rcm).
             (#
                (id_oyu, id_pyj, id_wgb, id_guh, id_ihh, id_uux, id_fwn,
                 id_oim).
              (not
                 (((str_ebr$0 <<: INT or NATURAL /<: FALSE) &
                   str_tko$0 /: MININT) =>
                  NATURAL1 /<: str_mwh$0))|
              {str_nha$0}),
             [str_ife,
              str_ttl,
              struct(id_dod: "str_pko", id_ekg: {}, id_iug: 990),
              rec
                (id_gqm:
                 { id_tke, id_qzv, id_zcp, id_ktz, id_gxp, id_tfs, id_aaf,
                   id_nwa
                   |
                   not
                     (#(id_shj, id_akh, id_pfi).
                      (#(id_bkk, id_ddf, id_nlv, id_dhr, id_adq).
                       (str_osv$0 : str_jwt))) }),
              str_qbc$0,
              str_iui,
              str_zcc],
             bool
               (#(id_ufg, id_faj, id_cps, id_hqu, id_odl).
                (str_ckh$0 <:
                 {str_zep$0, str_lkt$0, TRUE, []}("str_lra")'id_zuq) <=>
                str_riq < str_hov$0),
             rec
               (id_jkg:
                union
                  (bool
                     (!(id_xhc, id_upj).
                      (STRING <<: str_xms &
                       #(id_pgi, id_ube, id_jdq, id_bbo, id_xgm).
                       (TRUE >= NATURAL1)))),
                id_wam:
                struct
                  (id_jkw: str_szk,
                   id_hnj: str_pez,
                   id_htt: str_ous,
                   id_pmo: str_zhd,
                   id_qhs: str_pga$0,
                   id_vyo: str_wyk$0,
                   id_tvr: str_guv)))
        ELSIF
          not
            (#(id_uwr, id_mfy, id_uti, id_bwb, id_dlv).
             (!(id_iih, id_brs, id_mxw).
              (#
                 (id_aqh, id_egr, id_wke, id_osf, id_wzh, id_gou, id_hvw,
                  id_mba).
               (bool(str_ebn /<: str_eas$0)'id_ekf : NATURAL))))
        THEN
          id_vyx, id_kir, id_jux, id_yzc, id_ftg, id_sms
          ::
          struct
            (id_nfv:
             struct
               (id_wgs: FALSE'id_gdu,
                id_rvc: str_emd$0,
                id_lan: bool(str_ada /<<: str_rov)'id_ucb,
                id_kue: str_oyk,
                id_hus: str_zcd,
                id_kcf:
                rec
                  (id_ajo: [],
                   id_rlj: str_lnw$0,
                   id_gcx: str_llb$0,
                   id_ewj: str_voy,
                   id_aes: str_jfj,
                   id_qmu: str_yfk,
                   id_roe: str_avu$0),
                id_ecm: str_ukk$0))
        ELSE
          id_obm
            (bool
               (not
                  ({str_tbp$0, FALSE, (NAT1 >< 0)'id_day, [], NAT} : max({}))))
        END
      END
    WHEN
      !(id_bni).
      (!
         (id_mjx, id_kjh, id_jlg, id_ifc, id_waj, id_dwg, id_wds, id_glx,
          id_shn).
       (#(id_kar).(not(not("str_kfr" : TRUE))))) &
      not(str_dzn /<: str_sjj$0)
    THEN
      id_xbk, id_uvb, id_ovw, id_aay, id_bel, id_rfx, id_xtd, id_nag, id_sst,
      id_zlk, id_xfi
      :=
      bool
        (not
           (!(id_nue, id_gdi, id_cdk, id_axl, id_vdt, id_jev, id_ahq, id_xka).
            (!
               (id_dgw, id_oik, id_ees, id_zey, id_hhi, id_zhn, id_vdd,
                id_fkp, id_del, id_eyx, id_obi).
             (!
                (id_dxa, id_vbu, id_zyi, id_adf, id_npx, id_avm, id_fmr,
                 id_dle, id_drb, id_kdz, id_wpv).
              (!(id_mib, id_kuj, id_idu, id_xyt, id_qpd, id_hii).
               (!(id_fcx, id_qwo).(TRUE : INT)))))))
    WHEN
      !
        (id_oiv, id_lsq, id_yse, id_hcn, id_ysm, id_wqq, id_ubu, id_rah,
         id_edd, id_cod).
      (NATURAL /<<:
       [NATURAL1,
        str_qre$0,
        (str_nxu$0 mod str_zda$0),
        PI
          (id_tzx, id_vgh, id_ohv, id_exx, id_yvf, id_cna, id_bpg, id_qgh,
           id_mzt, id_wdf, id_rru).
        (str_kmo$0 /= NAT1| STRING),
        FALSE,
        NAT1,
        str_mrl$0,
        MAXINT]
         'id_tis
         'id_lbx)
    THEN
      VAR
        id_zka, id_erw, id_ymz, id_iou, id_xnm, id_cxt, id_mgk, id_sdq,
        id_zui
      IN
        id_rku'id_gkd
        :=
        union
          (UNION(id_sda, id_gke, id_snl, id_bmq, id_kvn).
           (str_wge /: str_ysg$0|
            {str_kkg$0,
             succ(NATURAL1),
             str_mbs$0,
             str_ols,
             str_ibi$0,
             INTER(id_pbh, id_hrc, id_zrc). (NATURAL /<<: str_ezc| str_jqh$0)} |>
            {str_lui$0}))
      END
    WHEN
      #
        (id_lus, id_hve, id_pul, id_hwr, id_rog, id_pdf, id_sos, id_hhr,
         id_fih, id_qbh).
      (!
         (id_grg, id_hdx, id_vpr, id_bjb, id_ppz, id_yuj, id_cwb, id_zhd,
          id_gbg).
       (not(str_ebb$0 < str_slp$0) or str_qbw$0 > str_cbp$0)) <=>
      not(str_lut$0 : str_gnv)
    THEN
      id_fsk'id_jke
      :=
      {NATURAL,
       str_opw$0,
       {{ id_gbu | str_wtq = {} },
        INTER(id_vbq). (str_mow$0 /<<: str_mof| str_qgp),
        (str_tdq$0 +-> (str_ooa$0 ^ NAT)),
        [str_nso$0, str_ymf$0, NATURAL, STRING]},
       str_yaq$0,
       []}
    WHEN
      #(id_lfw, id_tay, id_cuu, id_mfl, id_frn, id_hks, id_oed, id_dxx).
      (!(id_eiq, id_ryy, id_fgf, id_rbt, id_buh, id_cul, id_vdd, id_faf).
       (str_ghs$0 <= str_wij)) <=>
      (str_btb$0 /<<: MAXINT'id_ewz or str_uxu < str_xkv$0)
    THEN
      ANY
        id_rew, id_gos, id_ldw, id_oax
      WHERE
        not
          (!(id_lnv, id_knj, id_rld, id_tbl, id_vla).
           (#(id_xza, id_bqq, id_mgy, id_byh, id_lka, id_bgm, id_egr).
            (not
               (!(id_mdf, id_ppz, id_wkz, id_oxi, id_lob, id_ofy).
                (str_mfc <<: prj1(str_xfq, str_zcl$0))))))
      THEN
        CHOICE
          skip
        OR
          id_rtb, id_hhv, id_lwo, id_lah
          ::
          { id_xgk, id_qzd, id_jxa, id_gmw, id_bub, id_oxy
            |
            not
              (not
                 (!
                    (id_vut, id_wnz, id_pwl, id_aah, id_eaw, id_pog, id_gwf,
                     id_wqa, id_njq, id_lbe, id_yyv).
                  (#
                     (id_vgx, id_xtk, id_okt, id_ihx, id_frh, id_apt, id_xxu,
                      id_ebi, id_mec, id_hzd, id_uxj).
                   (str_rmv = MAXINT))) &
               #(id_saw, id_sts, id_zjr, id_njw, id_lfk).([] < str_hrq$0)) }
        OR
          id_hlc, id_lzh, id_ben
          <--
          id_rrh
            ({ id_quf, id_mhi, id_ges, id_xkl, id_dup, id_shq, id_ric,
               id_djy, id_qke
               |
               #
                 (id_uyh, id_hgz, id_wrn, id_bkq, id_wbk, id_wcm, id_gjz,
                  id_igb, id_pmg, id_yow).
               ({PI(id_luu, id_gvc, id_oyr, id_joh).
                 (INTEGER <= INTEGER| str_qjm$0),
                 (str_dqw$0 /\ NATURAL),
                 str_rpa$0} =
                str_izc$0) },
             %
               (id_kbe, id_lds, id_pwp, id_bsp, id_ofh, id_sua, id_slc, id_wys).
             (not(str_qlh$0 <<: str_rsm)|
              rec
                (id_sbl: str_flq$0,
                 id_hrq:
                 { id_uth, id_rsd, id_yut, id_yyk, id_ipv | str_teu = str_rak },
                 id_nhp: {TRUE, str_pba, str_crf$0, NAT1, str_fii$0, MAXINT},
                 id_pyl: str_rtk)
                'id_otd),
             ({ id_wfr, id_tnt, id_gsl, id_uas, id_fik, id_xbi, id_llv,
                id_vah, id_wmn, id_rqz
                |
                #(id_epg, id_msv, id_jdf, id_mlg).
                (not
                   (#
                      (id_tzq, id_nqh, id_gug, id_giy, id_pdg, id_dli,
                       id_zck, id_iah).
                    (!(id_hcj, id_why, id_rbb).(str_gdc /: MAXINT))) &
                 str_gxf$0 = str_oxl) } +
              str_ywz),
             INTER(id_siw, id_pbf).
             (not
                (!
                   (id_trh, id_hkh, id_csg, id_ayl, id_zsz, id_gnf, id_vls,
                    id_voy, id_wrq, id_pxz).
                 ({}'id_ipm'id_nuf <<: NAT))|
              NAT)
               'id_qpx,
             {STRING,
              str_ezo,
              struct
                (id_cmw: rec(id_dop: {}),
                 id_efx:
                 struct
                   (id_umn: bool(str_plb /<: str_dmp$0),
                    id_qwy:
                    struct
                      (id_yzy: str_dcx,
                       id_eur: NAT,
                       id_ndo: str_qnk$0,
                       id_gsp: TRUE,
                       id_yoe: str_tld,
                       id_nqw: {}),
                    id_bub: str_owg$0,
                    id_qti: STRING),
                 id_exu: bool(str_cpu <= str_cps)),
              str_xop,
              str_fhz,
              str_wmc},
             PI(id_rdq, id_bap, id_khe, id_ena, id_dvr, id_ccn).
             ({bool(FALSE /: NAT1)} :
              rec
                (id_jio: NAT1, id_ymy: str_vok, id_pxb: BOOL, id_mtz: str_hzv)|
              bool(str_yud$0 /<<: str_wvc$0)))
        END
      END
    ELSE
      id_hlg, id_tjp, id_nvd, id_pdr
      :=
      bool
        (#(id_fsh, id_ntd, id_wmg, id_lgc, id_tkz, id_omv, id_bhe).
         (not
            (#(id_lcs, id_hon, id_sla, id_sfd, id_moe).
             (not
                (#
                   (id_lrg, id_gge, id_asy, id_too, id_jrj, id_brf, id_jrw,
                    id_pek, id_xvj, id_dac).
                 (!(id_ykk, id_uue, id_gca, id_ikv, id_xkw, id_cck, id_jky).
                  ({} >= str_vmt)))))))
    END
  END;

  id_mym
  <--
  id_snh (id_fva, id_pzl, id_rcs, id_rrr, id_yxx, id_xxu, id_cdx)
  =
  ASSERT
    not
      (not
         (#(id_dzw, id_lpj, id_hvm, id_tsh, id_olb, id_rtj, id_yas).
          (not
             ({SIGMA(id_esv, id_jyf, id_ben). (str_vbj >= str_mpc$0| str_dci),
               "str_don",
               str_opj$0,
               str_icj,
               []} <=
              NATURAL))))
  THEN
    ASSERT
      MAXINT <<: str_dfo$0 &
      (!(id_wkv, id_fbr, id_kyn, id_bic, id_rrf, id_ths).
       (str_sfq$0 > str_zcz) <=>
       #(id_ojf, id_lql, id_otv, id_qzt).
       (!(id_lef).
        (!
           (id_vqy, id_pbv, id_hhf, id_xtb, id_lun, id_wxy, id_iqz, id_vfj,
            id_aes, id_wtw, id_dbz).
         (NAT1 <= TRUE))))
    THEN
      PRE
        [491,
         struct
           (id_ygg: str_ctu,
            id_fil: str_nbg,
            id_czr: MININT,
            id_tol: str_gkm,
            id_gub: str_spg$0),
         str_ync,
         INTEGER,
         STRING,
         str_clh$0,
         str_cfg$0,
         NATURAL1] <|
        { id_rhb, id_uau | str_tia >= [] } /:
        str_mor$0 **
        struct
          (id_piq: str_chw,
           id_zfl: str_eil$0,
           id_myf: TRUE,
           id_sgb: {},
           id_nho: str_bvp,
           id_wsr: str_nuu$0,
           id_ncz: str_lbr,
           id_txt: str_pzq$0)
      THEN
        VAR
          id_ges, id_azo, id_pmy, id_arh, id_rce
        IN
          CHOICE
            IF
              not
                (not
                   (#
                      (id_iul, id_aqz, id_anr, id_ove, id_zfz, id_hzp,
                       id_ajp, id_xog, id_tlx, id_ynv).
                    (bin
                       ({ id_vey, id_xta, id_opo, id_uhc | STRING = str_hfv$0 }) /=
                     str_qci$0 - NATURAL)))
            THEN
              id_ezi, id_kqq, id_amm, id_gph, id_zci, id_jxb, id_hbb
              ::
              {str_pan,
               [rec(id_xii: str_btm$0, id_spx: str_ayf$0),
                rec
                  (id_ahw: str_cgp,
                   id_jah:
                   PI(id_tnj, id_sfd, id_lxb, id_zgu, id_mea, id_bbm, id_sce).
                   (str_ifl < NAT1| str_sdl),
                   id_ypr: MAXINT,
                   id_aew: FALSE,
                   id_dye: INT,
                   id_nkx: str_zgi$0,
                   id_mmv: NAT,
                   id_pot: str_tsn),
                str_jmj$0],
               [NATURAL],
               TRUE'id_lmc,
               str_ohj$0}
            ELSIF
              not
                (#(id_cvv, id_ora, id_rib, id_zcn).
                 (#(id_onv, id_vjm, id_uzh, id_hil, id_nke).
                  (str_jft$0'id_jlr /<<:
                   struct
                     (id_vfx: str_pmr,
                      id_scb: str_xhl$0,
                      id_hhz: str_ore$0,
                      id_gcr: str_xpp$0,
                      id_diw:
                      %(id_zno, id_ijm, id_qzz, id_fgg, id_ioz).
                      (NATURAL /: str_oyt| "str_rnt")))))
            THEN
              id_ola'id_bis
              :=
              struct
                (id_kpm:
                 struct
                   (id_bgk: bool(not("str_bqq" >= STRING)),
                    id_ibn:
                    ([] |>> prj1(bool(NATURAL /<<: str_coe), str_qae))))
            ELSIF
              (str_yyg /<: str_sxt <=> str_oxb$0 /<: str_eki$0) =>
              !(id_sun, id_kzw, id_jhw, id_kyu).
              (#
                 (id_iko, id_put, id_upr, id_xaz, id_nsk, id_tmz, id_rbj,
                  id_ecb, id_plc, id_nog, id_hox).
               (str_zzk : str_kmx => [] > MININT) =>
               INTEGER /= NATURAL1)
            THEN
              id_aww, id_nms, id_cgl, id_aww, id_kmp, id_lff, id_tpe, id_xkc,
              id_biv
              <--
              id_bdb
                ({(closure
                     (bool
                        (!(id_djn, id_wzk, id_dud, id_oan).
                         (str_bxw$0 /= STRING =>
                          (NAT1 : FALSE => str_hkk <<: NATURAL)))) <-
                   str_wdj)},
                 inter
                   (bool
                      (!(id_mkv, id_kkv, id_evn, id_nhr, id_zqt, id_omu).
                       (not
                          (#(id_zom, id_flb, id_dyi, id_qmp, id_erg).
                           (str_sbn$0 = str_cbj) =>
                           str_wxv$0 = NAT))) *
                    str_cph$0),
                 struct
                   (id_oyl:
                    { id_dgu, id_tfx, id_jwq, id_rme, id_ctt, id_iwz, id_obg,
                      id_oxe, id_qqp
                      |
                      not(INTEGER = NAT) },
                    id_ucl: str_awt,
                    id_dkh:
                    { id_xcl, id_ucs, id_bry, id_nyd, id_nst, id_jfo, id_uoj,
                      id_cbq, id_mrb, id_akg
                      |
                      not(not(str_crb$0 <= str_fyr$0)) },
                    id_ged: str_xds),
                 SIGMA(id_chy, id_ovy, id_nng, id_sqr).
                 (not
                    (last
                       (PI
                          (id_hgp, id_nmg, id_rhf, id_fil, id_wwc, id_gve,
                           id_mch, id_ywu, id_cpf).
                        (str_uwy$0 : str_mze|
                         bool
                           (#
                              (id_uiu, id_whe, id_zts, id_oep, id_lfa,
                               id_xuq, id_wva).
                            (NATURAL1 /= "str_kiv")))) <=
                     str_vjf)|
                  str_dmr))
            ELSIF
              #(id_pky, id_hcs, id_wio, id_ern).
              (#(id_dov, id_pdg, id_wva, id_ywz, id_xcd, id_hqu, id_cfv).
               (not
                  (!(id_gmu, id_kcj, id_nbi, id_mcb, id_fmc, id_jia).
                   (str_otk$0 /<<: str_ore) <=>
                   #
                     (id_gro, id_rcu, id_tcj, id_fkw, id_fsn, id_hie, id_mcv,
                      id_wny, id_ssp, id_aie, id_kkd).
                   (#
                      (id_uky, id_ken, id_zsh, id_ser, id_bdf, id_ucl,
                       id_pcn, id_obs).
                    (BOOL /= FALSE)))))
            THEN
              id_pjo, id_vwb, id_aqt, id_zrb, id_ash, id_whm, id_mer
              ::
              bool
                (!
                   (id_hut, id_ehq, id_bjt, id_yjk, id_lnl, id_ywz, id_mbm,
                    id_bqy, id_hot, id_ezq).
                 ("str_dhm" <<: INTEGER &
                  not
                    (!
                       (id_yzt, id_rfq, id_ukh, id_uyo, id_dlh, id_uqg,
                        id_irz, id_sim, id_qgr, id_uvk).
                     (not
                        (#
                           (id_ncb, id_nao, id_cyj, id_nqb, id_gyc, id_zzv,
                            id_lkl, id_kcz, id_kne).
                         (str_eoa$0 < NAT))))))
            ELSE
              id_ihz 
                (
                  INTER(id_xhx, id_ptv).
                  (UNION(id_lih, id_hcl). (str_qbq$0 /<<: NAT| STRING) <=
                   {{str_xku, str_uwn$0, "str_bqf"},
                    struct
                      (id_upc: INT,
                       id_nxf: NATURAL,
                       id_kcu: str_ffw$0,
                       id_nxr: str_fyw),
                    MAXINT,
                    INT}|
                   bool(NAT1 /= NAT))
                )
                (
                  [str_slg$0,
                   str_ina,
                   str_dtz$0,
                   [],
                   {},
                   [[str_bbm, str_gcm$0],
                    [str_jxv, str_tis, {}, str_vuu$0, str_wcs$0, str_yvw],
                    size
                      ({ id_qgo, id_rwt, id_xvm, id_ter | str_aci <: {} }
                         (NATURAL))],
                   INT]
                )
                (
                  %
                    (id_oog, id_bdq, id_ffn, id_qyx, id_lce, id_yrp, id_ywk,
                     id_hcm, id_vgb, id_yla, id_szx).
                  (!(id_mko).("str_baf" /= str_gxe$0)|
                   [{ id_yfr, id_gce, id_jbd, id_pzx, id_ffd, id_qjc, id_oxc
                      |
                      FALSE /<<: str_fbz <=> NAT /= NATURAL },
                    bool(INTEGER <= str_gok$0 & str_ucy$0 <<: str_fqu)])
                )
                (
                  struct
                    (id_lrk:
                     (str_guz |>> {str_ode, rank({}), str_kcd$0, 1, NAT}),
                     id_oqr: str_mtz,
                     id_eci:
                     rec
                       (id_tmj: str_slj,
                        id_pfu: str_qgz$0,
                        id_vzp:
                        bool(MININT /<: NATURAL1 or str_png > str_zym$0),
                        id_kuy: {},
                        id_dch: str_cxt,
                        id_owq: str_yer$0))
                )
                (
                  son
                    ([NAT1,
                      str_inj$0,
                      FALSE,
                      { id_pbc, id_hql, id_hzc, id_hjn
                        |
                        #
                          (id_luu, id_bmh, id_rht, id_kgh, id_bkn, id_kbk,
                           id_eno, id_vgj, id_rzp, id_jwd, id_kga).
                        (not([] : str_joc) <=>
                         (str_wfw >= str_lkl => MININT : STRING)) },
                      str_jwi$0])
                )
                (
                  postfix
                    (prj1
                       (bool(not(str_yhs$0 <= NATURAL) or FALSE <<: INT)
                          'id_yno,
                        [str_acf$0, INT, str_edv, str_usf$0, NATURAL]))
                )
              
              :=
              { id_dfm, id_ntn, id_ziv, id_tmo, id_jje, id_ivd, id_qqq
                |
                struct
                  (id_odi: str_hhu,
                   id_kxj:
                   { id_xyg, id_ytn, id_ndv, id_ewb, id_wee, id_udx
                     |
                     !
                       (id_xch, id_vrn, id_bsz, id_ktk, id_hhw, id_tgi,
                        id_edl, id_kxx, id_pqp, id_nnw, id_unn).
                     (str_ujb$0 /= str_pkl$0) },
                   id_hyd: str_hwl$0,
                   id_cih: str_rte,
                   id_cwf: str_omh$0,
                   id_ygg: str_zjn,
                   id_ims: str_eod,
                   id_mmp: "str_thl") >
                rec(id_amy: str_jxl, id_okx: INTEGER, id_wvv: BOOL'id_gut) }
            END ||
            id_dps, id_uwt, id_ngi, id_rrb, id_enj
            ::
            son
              (struct
                 (id_jku: iterate(str_mgu$0 \|/ str_ccj, str_fjj$0),
                  id_dnl:
                  struct
                    (id_zaq: FALSE,
                     id_yfj: {},
                     id_ial: str_nor$0,
                     id_inp: NATURAL,
                     id_iwj: str_dtj$0,
                     id_jkk: str_ikp),
                  id_kmp:
                  [str_aiz, str_tqs$0, str_yrl$0, str_azb$0, str_bls$0,
                   str_ehe]))
              'id_xaq
          END
        END
      END
    END
  END;

  id_div, id_lpb, id_jrs, id_bsf, id_xxu, id_ufi, id_enn, id_yrl
  <--
  id_gvq (id_bbk, id_cft, id_pey, id_yis, id_yyy, id_rdt, id_yzf)
  =
  ANY
    id_onu, id_vkb
  WHERE
    !(id_kmi, id_efx, id_tef, id_bzu, id_hkv, id_swt, id_uod, id_gxi, id_ytx).
    ({ id_pgy, id_ljd, id_thu | str_wln$0 /: MAXINT } < INT >+> str_swn$0) &
    !(id_tzd, id_gel, id_yxr, id_cob, id_dzx).(not(str_kli < str_ooh))
  THEN
    LET
      id_jss, id_xdm, id_gru, id_tvb, id_jdh, id_uap, id_lpg, id_eur
    BE
      id_cuz
      =
      bool
        (not
           (str_zrh$0 < INTEGER <=>
            !(id_fll, id_svw, id_wzm, id_die, id_jse).
            ({} /: INTEGER &
             !(id_ytp, id_usv, id_mul).
             (str_yph$0 > str_dha or str_cmk /<<: str_cji))))&
      id_cig
      =
      { id_gnw, id_oia, id_xcz, id_rjr, id_soy, id_cai, id_tyx
        |
        !
          (id_lmv, id_cfd, id_nss, id_mbv, id_lop, id_hsz, id_gqh, id_rlx,
           id_mgy).
        ({str_dwa, str_vrg$0, str_gst$0, str_pii$0, str_wvd, 1496, NATURAL,
          str_ftl} =
         struct
           (id_zad: [], id_eep: FALSE, id_qdr: [], id_dgq: inter(str_rax))
           'id_ggv) }&
      id_egr
      =
      {[str_rks,
        BOOL,
        str_uce$0,
        str_uuu$0,
        BOOL,
        str_swy,
        {str_ktm$0,
         str_pzv,
         { id_rhl, id_ttf, id_eto, id_zin, id_dck | str_qyi$0 /<: INT },
         str_fbz,
         [str_vnw, str_yax$0, str_tqq, str_bun$0, str_aiu$0, str_vrv],
         { id_cde, id_pii, id_nfk, id_caj, id_ulw, id_vtm, id_vwq, id_ias,
           id_jmx, id_lgr
           |
           str_aoe /: str_glx$0 },
         str_twy}],
       {},
       str_gvj,
       MININT}&
      id_eze
      =
      { id_zoe, id_vbm, id_jnb, id_you, id_gts, id_qed, id_ldk, id_ein,
        id_acn, id_ube, id_qxl
        |
        #
          (id_zvq, id_zor, id_kgn, id_wgq, id_lfq, id_vsq, id_pap, id_dff,
           id_pme, id_lit, id_qej).
        (!
           (id_azx, id_wpl, id_jgr, id_zjv, id_jhm, id_tsa, id_wdy, id_oez,
            id_tpz, id_mfe, id_iwa).
         (#(id_ejz, id_avx, id_ohs).
          (!
             (id_oxe, id_dho, id_mvx, id_apu, id_dya, id_eyi, id_eee, id_aok,
              id_trv, id_jfp, id_woz).
           (!
              (id_tne, id_npy, id_bjj, id_vmk, id_nqf, id_ija, id_enc,
               id_sqx, id_ihe, id_cvi, id_pay).
            (str_hob /= NATURAL1 <=> [] <<: INTEGER))))) }&
      id_lwo
      =
      rec
        (id_fms:
         {top
            (PI(id_apd, id_sob, id_xet).
             (!
                (id_oet, id_ggh, id_lls, id_gbm, id_unl, id_dsb, id_kzm,
                 id_raq, id_omj).
              (!
                 (id_wba, id_dft, id_xns, id_wjo, id_mya, id_zgp, id_ceq,
                  id_vqf, id_fgm, id_bmn, id_nft).
               ([] < str_ouy$0))|
              str_ojz$0)
               'id_juo)})&
      id_wps
      =
      POW1
        (struct
           (id_pjr: str_rcv$0,
            id_xls: str_oed,
            id_qmt: TRUE,
            id_xph: str_qxu$0,
            id_gcg:
            { id_szz, id_umc, id_hmm, id_mzw, id_hty, id_nfo, id_zox, id_vzy
              |
              #
                (id_uec, id_hml, id_lmi, id_ihl, id_glj, id_cmg, id_myp,
                 id_rim, id_lja).
              (str_afg$0 >= str_jlw) },
            id_bbr:
            struct
              (id_hob: NATURAL,
               id_zoy: "str_jla",
               id_ash: POW1({}),
               id_oyo: FALSE,
               id_tum: str_rjo$0,
               id_buh: str_eqf$0)))
        'id_axj
    IN
      WHILE
        !(id_zgz, id_pmc, id_cbn, id_aay).
        (not(not(MAXINT > str_dyl => not(not(TRUE >= str_dpn$0)))) &
         str_zwr$0 <<: str_vwh$0)
      DO
        CHOICE
          skip
        OR
          id_eyd, id_zgx, id_lgg, id_ami, id_zuh
          :=
          { id_gjq, id_smq, id_qch, id_ewl, id_jif, id_snw, id_tbe, id_mlc,
            id_mzv, id_sls, id_wze
            |
            struct
              (id_fzu: str_kcm$0'id_mit,
               id_qoz: str_ecu,
               id_jhv: str_fti$0,
               id_evp: str_nvn,
               id_uqr: str_ost$0,
               id_vzm: str_ybj,
               id_qox: str_mhm$0,
               id_bib: BOOL) /:
            struct(id_vgw: str_xgf) or
            [] < str_nza }
        OR
          id_guz :(
            !(id_ojj, id_xmr, id_jgg, id_wzn, id_tej, id_gsi, id_put, id_afz).
            (#(id_vuo, id_odz, id_uvf, id_qpy).
             (not
                (#(id_qbf, id_lkm).(str_kiu >= str_qcy) &
                 not(str_cwx$0 <= 622 & str_rwv$0 /<<: str_lqq$0))))
          )
        OR
          ASSERT
            not
              (not
                 (!(id_dtg).
                  (#(id_qwq, id_cxy, id_kpj, id_mbw, id_luw).
                   (!(id_buz, id_nxd, id_snd, id_npy, id_ppc, id_nah).
                    (POW1(str_cxj) /<<: str_tpe$0)))))
          THEN
            id_ssa'id_pmh
            :=
            { id_cdg, id_bio, id_war, id_ymb, id_vqr, id_nid, id_ifm, id_mqg,
              id_ijq, id_ifv, id_rer
              |
              bool(STRING : NAT) /:
              {{ id_xmf, id_nrr | str_pvn /: str_bqv & STRING >= str_jlo$0 }} }
          END
        END ||
        SELECT
          not
            (#(id_yzk, id_wpu, id_qne, id_ibv, id_iex).
             ({str_bcg,
               str_acz,
               str_qjx,
               rec
                 (id_ajb: str_dxv,
                  id_gxm: str_bqt,
                  id_wwu: {},
                  id_akd: NAT1,
                  id_uds: NAT1,
                  id_ria: {},
                  id_woe: NAT1,
                  id_ipm: NATURAL),
               (str_nmq$0 <- MININT),
               str_oth} <<:
              bool(str_mto /<<: NATURAL1)))
        THEN
          skip
        WHEN
          #(id_xdv, id_qpd, id_tlf).
          ((str_mjt >= str_ugj$0 or MININT /<: str_hbz) =>
           !(id_hxz, id_fal, id_bhr, id_tbw, id_jdy).(str_cha < str_dkm)) &
          (not(NATURAL1 /<: INTEGER) <=> str_cdz$0 <: INT)
        THEN
          id_nqx, id_mhk, id_efu, id_cfo, id_jwd, id_cgd, id_jyn, id_otc,
          id_dfh
          ::
          succ
            ([INTER
                (id_eog, id_ccr, id_thw, id_gga, id_thp, id_sms, id_qxm,
                 id_bdl).
              (MAXINT <= str_lbh$0|
               %(id_tmd, id_yiy, id_olc). (450 < str_ldr$0| str_zzy)),
              ((str_mxc$0 mod str_etr) |> NAT1'id_bmw)])
        WHEN
          #(id_eun, id_bqf).
          (#(id_hfh, id_cql, id_ffk, id_fns).
           (#
              (id_azl, id_jfx, id_mzy, id_hou, id_hwb, id_plx, id_afs,
               id_owm, id_ptm, id_rdv, id_jqn).
            (MININT > INTEGER or str_qbl <= str_ehs$0) &
            not(!(id_tzl, id_tih, id_gdb, id_jec).(str_vfz$0 /<: str_ssd$0))))
        THEN
          id_xyq, id_jgj
          :=
          [%
             (id_pdm, id_icu, id_fxz, id_ldz, id_cgc, id_kqi, id_rqb, id_ntk,
              id_zvw, id_zzo).
           (str_zzm$0 = str_kvl| str_ydx),
           str_bsd$0,
           str_ecv,
           struct
             (id_gen: BOOL,
              id_bph: STRING,
              id_nad: str_eso,
              id_kvy: INT'id_bcn,
              id_non: str_jbo,
              id_gke: str_azo$0,
              id_qjx: str_swv,
              id_ltw: "str_zbn"[str_tow]),
           (str_dzq$0 - []),
           STRING'id_krc]
        WHEN
          str_kev$0 <<: NATURAL or
          !
            (id_rnb, id_qjp, id_thu, id_uro, id_jly, id_iwm, id_pbv, id_vaz,
             id_wwc).
          (#
             (id_vqz, id_vxv, id_jwn, id_pbb, id_nck, id_fdm, id_otr, id_qrh,
              id_btu).
           (rec
              (id_wxm: str_awv,
               id_ozb:
               { id_ezz, id_klk, id_tgg, id_lhs, id_fxz, id_ork, id_xiy,
                 id_fcv, id_ltd, id_zah, id_zgb
                 |
                 not(BOOL > NATURAL1) }) >=
            str_bdq$0))
        THEN
          id_jvj, id_sdc, id_ism, id_uke
          :=
          [({str_hef$0,
             str_nbu$0,
             str_fll,
             rec
               (id_ydx: STRING,
                id_jil: str_xyn,
                id_ilh: str_guj$0,
                id_dxc: str_uyl,
                id_ykf: str_bet)} \/
            str_sgk$0),
           {str_ggk$0,
            FALSE,
            69,
            fnc
              ([{}, str_sxi, str_dmh$0, NAT1, str_fdo$0, 7, INTEGER,
                str_saz$0]),
            str_gyl$0,
            [],
            str_gdv$0}]
        WHEN
          not
            (!(id_hng, id_qct, id_fzf, id_uby, id_hto, id_xbe).
             ("str_bih" <: str_jin)) or
          (!
             (id_dbc, id_pej, id_buj, id_slq, id_iuw, id_bcd, id_vcw, id_duu,
              id_vjw).
           (338 /<: str_mbl) <=>
           (str_wsv /<<: str_obk => str_fkv$0 /<<: NAT))
        THEN
          id_gkv'id_rhi
          :=
          rec
            (id_mjs:
             ran
               (rec
                  (id_zuz: str_klr$0,
                   id_zww: str_xct$0,
                   id_ldi: NATURAL1,
                   id_yam: str_xnh,
                   id_pcc: str_mxo)),
             id_sya: (str_hbv$0 --> (bool(INT = INTEGER) / str_efb)),
             id_czm: str_ekm'id_dmr,
             id_ioj: [])
        WHEN
          #(id_jnd, id_vyn, id_ozy, id_jgv, id_ppd, id_lhn, id_vhx, id_zsc).
          (str_xet /= MAXINT <=>
           not
             (iterate
                ([str_yya, str_byd$0, {}, str_ehy$0, str_ezn, TRUE],
                 [str_svx$0, FALSE, str_mrx, NAT, str_yqy, str_phg, NATURAL]) /<:
              str_ltc))
        THEN
          id_eaw, id_rkq, id_kyb, id_uts, id_yot :(
            not
              (!(id_gzh).(INTEGER /: INTEGER) <=>
               #(id_kxo, id_czw, id_pca, id_egr, id_mva).
               ((str_jcl > str_mie => str_snh > str_jnb$0) =>
                NATURAL1 >= str_bno$0))
          )
        WHEN
          !(id_nzz, id_wth, id_uqs, id_oyi, id_lzt, id_wsy).
          ({ id_syl | str_vgr <<: str_hty } <=
           INTER(id_jkw, id_bhq, id_jzk, id_yqo).
           (not
              (#(id_udg, id_xom, id_ykv, id_wot).
               (#
                  (id_tpy, id_qui, id_gnq, id_rcj, id_czm, id_bae, id_gzx,
                   id_gpl, id_kdu, id_jfd).
                (str_rlq <= str_ldo$0)))|
            {}))
        THEN
          id_dty, id_cle, id_bga, id_xyc, id_jdz, id_glc
          <--
          id_fjl
            (right
               (str_rxq$0 /\
                bool
                  (#
                     (id_kya, id_hax, id_ctd, id_wrb, id_new, id_lem, id_vmz,
                      id_ent, id_gid, id_tny, id_oqk).
                   (not(!(id_gam, id_stw).(str_akr = str_ltw$0))))),
             ([str_ael$0,
               str_yro$0,
               str_ryi$0,
               str_fas,
               NAT,
               str_gsw$0'id_jyj,
               str_cwe] /|\
              SIGMA(id_pwy, id_hkn, id_efo, id_von, id_uwi, id_gaz, id_puu).
              (str_afg$0 = str_qcj| seq1({}))
                'id_nwf))
        WHEN
          not
            (SIGMA
               (id_ceo, id_qbo, id_kwn, id_pdr, id_mht, id_kea, id_tux,
                id_eps, id_liz, id_poc, id_qag).
             (TRUE <: str_fyp| MININT) <<:
             rec(id_waq: NATURAL1, id_pgc: INT) &
             (MININT > NATURAL1 &
              #(id_gtf, id_jev, id_imb, id_xlo, id_dhj, id_cvh).
              (str_csw < str_fbv$0)))
        THEN
          skip
        ELSE
          skip
        END
      INVARIANT
        #(id_pze, id_wgj, id_goa, id_qwa).
        (!
           (id_gfn, id_adq, id_yyx, id_juf, id_nas, id_qxd, id_lcp, id_ifz,
            id_jzm, id_pnw, id_guh).
         (#(id_pih, id_buw, id_xep, id_zyf).
          (not
             (not
                (!
                   (id_ddb, id_too, id_tct, id_kod, id_kla, id_nuk, id_gzo,
                    id_wie, id_czm, id_ybp).
                 (#(id_lxq, id_npe, id_ynm, id_vvn, id_lce).
                  (str_xbp <<: str_knj$0)))))))
      VARIANT
        rec
          (id_rwx:
           { id_qvy, id_wnz, id_hxy, id_qyy, id_nsx, id_xoh, id_hlc, id_vac,
             id_okk, id_hpz
             |
             not(([] <= str_mdq or TRUE <: TRUE) => str_mkl$0 : str_xog) },
           id_lus: NAT,
           id_aub: str_hbz,
           id_aue: str_xca,
           id_soq:
           rank
             (struct
                (id_glc: NATURAL1,
                 id_epg: str_nrj$0,
                 id_kbr: str_bwn$0,
                 id_wmk: str_bxa,
                 id_drv: str_eqr$0,
                 id_bwg: str_imy)),
           id_mxu: NAT,
           id_hfz: MININT,
           id_kin: str_dnp$0)
      END
    END
  END

END 