MACHINE
  id_xzi( id_vct, id_qvb, id_ryc, id_bvd, id_zfp, id_mwk, id_bir, id_jql )

SEES
  id_amw, id_tuw, id_ajc, id_qox, id_tof, id_vlm, id_iqx, id_cue, id_ecj,
  id_lnm

INCLUDES
  id_odn (
    iseq
      (struct
         (id_rxe:
          struct
            (id_hln: str_nfy,
             id_bjp: (str_ftc$0 |-> MAXINT),
             id_lgg: INTEGER,
             id_jkq:
             struct
               (id_bzs: SIGMA(id_cae, id_vwt). (str_uxf = str_jns| str_evs),
                id_qof: str_asf$0)),
          id_hto: str_lcu,
          id_xfc: NATURAL,
          id_cis: str_nps))
      'id_gka
  ),
  id_agi (
    {SIGMA(id_xkl, id_apn, id_yge).
     (!(id_rvk, id_guj, id_jei, id_iai, id_nnq, id_vfq, id_brt).
      (str_dzf - STRING /<: str_gxi)|
      { id_nij, id_yed, id_qen, id_uzk, id_qvr, id_nlo, id_dgy, id_icj,
        id_ias
        |
        TRUE : str_rse$0 }),
     (str_ufu$0 .. INT)},
    ({{ id_ogl, id_qqw, id_qnt | str_twd /= str_qyc$0 },
      { id_sod, id_rcv, id_ola, id_mqv, id_maa, id_ibd, id_usl, id_ppf,
        id_dns
        |
        #(id_vbs, id_okr, id_sap).(str_atl <: str_lgs$0) },
      str_gpy,
      FALSE} \|/
     (str_orr$0 \/ { id_mik | str_lpd /<: FALSE }))
  ),
  id_vxz (
    {bool(str_jzz <= str_vvs$0),
     { id_cnl, id_inr, id_mdx, id_puc, id_ecg
       |
       not
         (str_yqw$0 >= str_qgx$0 <=>
          !(id_ydj, id_upb, id_krg, id_oru).(str_tit$0 : INTEGER)) },
     {},
     str_qjz$0,
     str_woe$0}
      'id_uqg
  ),
  id_eaz (
    [top(last(str_zjs)),
     str_xyo$0,
     NAT,
     { id_fie, id_lpb, id_bhx, id_syh, id_gqt
       |
       not
         (#
            (id_etw, id_mwk, id_hgl, id_ehr, id_ubr, id_njv, id_tgf, id_aab,
             id_lus).
          (str_ypq$0 > NAT1) &
          INTEGER /<<: str_ynq$0) },
     str_pzl$0,
     str_nzw,
     str_pmn,
     str_iah$0]
  ),
  id_rop (
    SIGMA(id_yrq, id_pnf, id_zfb, id_qbe, id_iyo, id_qxu, id_bre, id_gaa).
    ([str_zkk$0, str_ygx$0, str_byb$0] /<<:
     {STRING,
      str_lzq$0,
      "str_fkv",
      str_lrb$0,
      (INTEGER +-> TRUE),
      str_dnb,
      sons
        (struct
           (id_bdf: str_eli$0,
            id_ffk: NAT,
            id_vyn: str_qgh$0,
            id_cya: str_iqz))}|
     {})
  ),
  id_let (
    father
      (rec
         (id_vjx: sons(bool(not([] : str_ixt$0))),
          id_vab: str_xht,
          id_aei: NATURAL1,
          id_nwg: [str_nlr, [str_kvk, INT, INT, INT], str_shl$0],
          id_svk: NATURAL,
          id_swh: 79,
          id_upk: str_omf$0)),
    {id
       (str_naw$0 mod
        { id_zmp, id_ecg, id_nyy, id_bvd, id_uxu, id_pdu, id_zet, id_ics,
          id_hch, id_jaj, id_rzn
          |
          #
            (id_lfl, id_gaz, id_mpl, id_gwo, id_wgc, id_etp, id_auy, id_wvy,
             id_lck).
          (MAXINT : str_qwh$0) }),
     struct(id_oif: str_rew$0, id_lhc: str_hbb$0'id_bor, id_fyh: str_mdv),
     str_mnc},
    [({str_hnw, TRUE, "str_ikq", str_mcq, str_nwz, str_aai} +
      { id_hqu, id_wol | NATURAL1 <= str_rpj }),
     bool(str_fes$0 <: str_czp & str_dje : str_phf),
     str_eqd$0'id_ivd]
  ),
  id_kle (
    struct
      (id_cml:
       [([str_zzr$0, str_fyk$0, str_tpc, str_qqm$0, str_zwi$0, str_sxa$0,
          str_kjm] >+>
         str_sou)],
       id_ygv: bool(str_yfl = str_fwa$0),
       id_wgp: str_ztk,
       id_tng: str_txo,
       id_jbf:
       { id_hik, id_eum, id_ycy, id_dxj, id_qmy, id_tjr
         |
         #(id_cdk, id_hje, id_nzq, id_vpz, id_nbn, id_ogg).
         (str_kzs : str_ycr$0) },
       id_foh: NAT1),
    SIGMA(id_ksz, id_mqv, id_xep, id_mjk, id_hvo, id_ywm, id_dho, id_uqa).
    (MININT > "str_cbd"|
     id
       ((bool(#(id_mxj, id_sad, id_yxr, id_cke, id_mwo).(FALSE >= str_zra)) *
         str_ndc$0)
          'id_hwe))
  ),
  id_cnw

PROMOTES
  id_dzj, id_lms, id_bnl

EXTENDS
  id_arq (
    [{str_gae$0,
      str_mlh,
      { id_tvp, id_cit, id_tup, id_pct, id_llz, id_sqo
        |
        #(id_pqz, id_sjp, id_wrs, id_gne, id_tgb).(NATURAL = "str_yky") },
      INTER(id_zoo, id_dpn, id_uqi, id_cek, id_hrn, id_ddq, id_ods, id_ern).
      ({} = MAXINT| []),
      str_mdc$0,
      str_fwd,
      tail(tree(TRUE))}]
  ),
  id_idd (
    perm
      (%(id_thy, id_kjr, id_qon, id_rzf, id_uhu, id_dcl, id_asx, id_vmi).
       (#(id_hia).(MAXINT +->> BOOL <= str_eeo$0)|
        {[], str_pnr, str_fjr$0, str_knh$0})
         'id_sjk),
    seq
      (({str_qwn, STRING'id_uev, TRUE, STRING, str_xkj, MAXINT, {}} -->>
        ["str_jsn",
         { id_uue, id_qmr, id_tis, id_nvf, id_wru, id_jxn, id_uss, id_gjm,
           id_amc, id_cjf, id_jcu
           |
           FALSE /: str_lcy },
         str_ixt$0])
         'id_bag),
    INTER
      (id_vns, id_wpy, id_waw, id_beq, id_zwl, id_qrn, id_mvi, id_jqu, id_jic).
    (str_qtz > NAT|
     [{str_ekb, str_rjh, STRING, str_xug, MININT},
      str_shf,
      str_rhr$0'id_lmd,
      0,
      { id_wlm, id_enf
        |
        #(id_wrk, id_iqu, id_ruk, id_oyy, id_cyq, id_qqn).(str_epq <= MININT) }]
       (str_nxp$0))
  ),
  id_kye (
    ({ id_pob, id_uek, id_lpn, id_ddh, id_ppl, id_sgt
       |
       NAT /<<: 415 or !(id_rlx, id_cgo, id_hcf).(not(MININT /<: str_mci)) } |>>
     INTER
       (id_jzw, id_rzu, id_hja, id_cjg, id_nmj, id_ijh, id_yvg, id_dbq,
        id_yfm).
     (str_cbj <= str_sqb$0| { id_szt | str_eyz : str_uud$0 })),
    [str_hop'id_tbo,
     bool
       (!
          (id_amf, id_eeo, id_toe, id_nai, id_xwj, id_wce, id_zrx, id_zgr,
           id_pkx, id_vlw).
        (#(id_yib, id_xia, id_jxi, id_nry, id_vtj, id_rdr, id_bor).
         (NAT /= str_oxn$0))),
     str_sgl$0,
     UNION(id_ntu, id_zql, id_fgk, id_jly, id_yeq, id_efc, id_prw).
     ("str_izr" < NAT| struct(id_ieh: NATURAL1)),
     7,
     NAT1],
    struct
      (id_css: str_mgi,
       id_osr: BOOL,
       id_mgs: str_sza$0,
       id_crq: str_lig$0,
       id_tor: NATURAL1,
       id_zgw:
       { id_vvx, id_cvn, id_igr
         |
         [str_sbx,
          struct
            (id_mbg: str_jie$0,
             id_vtj: str_vps,
             id_pgr: str_tkg,
             id_yli: str_hzi$0,
             id_puj: MININT,
             id_tqv: {},
             id_kgi: MININT,
             id_oxi: str_jxh),
          str_vuz,
          str_non$0,
          str_kec,
          str_vyr,
          str_nxw,
          str_sxt] /:
         postfix(INTEGER) })
      'id_vfc
  ),
  id_paa (
    arity
      (UNION(id_dry, id_yih, id_iue, id_moq, id_pxc).
       (str_wnr$0 <<: BOOL|
        (BOOL |->
         struct
           (id_kvx: str_wyn,
            id_htx: NATURAL,
            id_jjd: TRUE,
            id_ynl: str_efi,
            id_skb: str_gvk$0,
            id_mmx: str_get,
            id_npo: str_uxr$0,
            id_ogw: str_jfn$0))
          'id_zfy
          'id_rsf)
         'id_wwg)
  ),
  id_nqj (
    bool
      (#(id_bow, id_kpb, id_cku, id_fhv, id_kip).
       (not
          (!
             (id_yap, id_hzz, id_tll, id_bhh, id_nsg, id_gsk, id_plu, id_hkc,
              id_sbx, id_bei).
           (not
              (!(id_xve, id_zwf, id_glx, id_ytn, id_wyd, id_whh).
               (str_xff < str_phc)))))),
    { id_pqg, id_riu, id_jhn
      |
      #(id_nab).
      (not
         (bool
            (!(id_eda, id_ziv, id_ohb, id_koo).
             (!(id_ted, id_xvk, id_lcb, id_rdx, id_oeu, id_gsu, id_yja).
              ([] < INTEGER))) /:
          str_vwi)) }
  ),
  id_xoq (
    (MAXINT ||
     {[str_owb, str_ufu$0, [str_bpi], str_kcw],
      SIGMA(id_bky, id_eyg, id_bfp, id_pzx, id_mcy). (str_uoj <= NAT1| []),
      str_vso$0,
      str_ily,
      INTEGER})
      'id_mvt
      'id_znh
  )

USES
  id_kjh, id_qjf, id_kuu, id_sdk, id_yff, id_bui, id_gtd, id_blh, id_fhu,
  id_sig

SETS
  id_csd;
   id_jpc = { id_owz, id_bts, id_dxy, id_wuf } ;
   id_jjw = { id_sxa, id_uju, id_vqr, id_jpd, id_aoy } ;
   id_ikc = { id_fyb, id_tmg, id_wkx, id_vic, id_omh } ;
   id_oyw = { id_whh, id_lve } 

CONSTANTS
  id_cjh, id_utb, id_lia, id_dkc, id_vjz, id_rsn, id_ahk, id_khr, id_esd

ABSTRACT_CONSTANTS
  id_ifg, id_fjr, id_ebi, id_oel, id_sat, id_htl, id_mdk, id_pbg, id_avs,
  id_qmk

PROPERTIES
  !
    (id_fay, id_fxx, id_ikp, id_uli, id_beo, id_bug, id_slk, id_qyt, id_hwn,
     id_zyi, id_ytp).
  (NATURAL < str_rfn'id_buh) or
  #(id_dmm).
  (#
     (id_fjw, id_ixw, id_yza, id_iil, id_dqs, id_xwm, id_xyv, id_pwd, id_sjj,
      id_wtx, id_uvf).
   (#(id_kpt, id_ijr, id_ynl, id_tbf, id_lkx, id_yhn, id_nnc, id_kfd, id_eot).
    ({} /<: str_cmm$0)))

CONCRETE_VARIABLES
  id_cah, id_fvy, id_fht, id_oyz, id_icd, id_diw, id_gao, id_pec, id_mfa

VARIABLES
  id_nzj, id_zmi, id_izr, id_hns, id_bsd, id_ijo, id_yhh, id_zrz

INVARIANT
  !(id_vfq, id_wwx, id_xmh, id_dsi, id_uht, id_kri, id_cfy).
  (not
     ((#(id_jzz, id_nbn, id_tcp, id_vns, id_rlw).(not(str_kfp$0 = str_dlq$0)) =>
       str_rfs$0 <= NAT1) &
      (INT < str_zor => BOOL : str_wmf$0)))

ASSERTIONS
  str_rku$0 /:
  {rank
     (inter
        (rec
           (id_beb: { id_rao, id_evn, id_osr | MININT /= str_tzw },
            id_gxg: str_izy,
            id_tec: MAXINT,
            id_quc: STRING,
            id_zrp: str_jop$0)))} &
  str_jvs$0 /<: str_kpp$0;
  bool
    ((#(id_tue, id_xrm, id_qdf, id_kwk, id_rme).(NATURAL1 /: str_imk$0) =>
      str_syg <<: str_cdl) or
     str_xca$0 /<<: str_fbi$0) <
  struct
    (id_rho: str_cpk$0,
     id_akq: str_aua$0,
     id_fbh:
     %(id_oqi, id_jln, id_npp, id_ord, id_mqh, id_zfa, id_tid, id_vlt).
     (NAT > str_mrl$0| str_vcg),
     id_gjv: str_ahv);
  !(id_cub, id_sjd, id_sln, id_wsy).
  (!(id_xzz, id_fog).(str_tll$0 /<<: str_fow$0) &
   not
     (str_unx <= MAXINT =>
      !(id_jxy, id_fxp, id_ciq, id_ahc, id_rkg).
      (str_krp$0 <: "str_aoa" or str_avo <: str_vma)));
  !
    (id_joj, id_hzt, id_dxc, id_con, id_zew, id_lsp, id_mjl, id_umg, id_zvq,
     id_erp, id_wqo).
  (!(id_zfy, id_ypd, id_wag, id_uyq, id_oil, id_hne, id_mdy, id_kbz, id_ztv).
   (!(id_kpf).(not(str_tfm <: str_qrx)) <=>
    not
      (#
         (id_bit, id_axh, id_hsd, id_bkb, id_vml, id_ipf, id_imn, id_cqp,
          id_kaf, id_whm).
       (NATURAL /<<: NATURAL))));
  not
    (#(id_ojo, id_jmr).
     (#(id_qlm, id_phi, id_tyc, id_qcz, id_vyc, id_eow).
      (NAT1 /: bool(str_vvy$0 /<: str_cjp <=> str_hjo$0 : str_rkq) =>
       str_lwv > str_mxd)));
  not
    (not
       (#
          (id_joc, id_zmb, id_vao, id_khg, id_ipj, id_orl, id_dvl, id_kcq,
           id_cyr, id_vbz).
        (#
           (id_qng, id_cpp, id_khy, id_yrf, id_muw, id_uae, id_hhk, id_iva,
            id_qhv, id_hao).
         (#
            (id_ybp, id_blj, id_qni, id_lrh, id_lla, id_lqo, id_kon, id_dto,
             id_vra, id_rhx).
          (!(id_vuj, id_wxn, id_xut, id_jlz, id_xqu, id_epm).
           (#(id_wtc, id_zvy, id_tmk, id_hlu, id_bxk, id_njp, id_jxu, id_zkh).
            (NATURAL /<<: {})))))));
  not
    (!(id_igk, id_jes, id_lwr, id_wtc).
     (!
        (id_mzs, id_wtb, id_hvp, id_gwx, id_ynh, id_naq, id_luu, id_mru,
         id_oec).
      (!(id_rry, id_xgl, id_bor, id_aqs).(str_jcn : FALSE)))) or
  not(TRUE /= BOOL);
  struct
    (id_ndk: str_ttu$0,
     id_cey: str_lhe$0,
     id_osb: TRUE,
     id_qjn: {},
     id_dqb: str_yys,
     id_sgb: 884,
     id_rpv:
     bin
       (PI
          (id_gyx, id_yvm, id_mbq, id_orn, id_ejh, id_owp, id_hrd, id_jpx,
           id_bov, id_ovh).
        (str_jom < str_cwd| str_ltz)
          'id_nhi)) <<:
  [str_fmm, str_pbm];
  !(id_zch, id_nzy, id_ogo, id_otn, id_bne, id_ajc).
  (#(id_unm, id_gzg, id_jit).
   (!(id_pfa, id_vgv, id_dxd).
    (!(id_zgg, id_hji, id_krt).
     (rec
        (id_qxt: MININT,
         id_tqx: str_elr$0,
         id_qdn:
         PI(id_skm, id_xut, id_prn, id_lwx). (str_wep = str_fyq| str_dmd),
         id_zkh: INT) >
      STRING))));
  struct
    (id_fbq: bool(not(str_cxu < {})),
     id_wmu:
     { id_qkf, id_sgv, id_cch, id_jfd, id_fek, id_ywd, id_cjt, id_gvx, id_dau
       |
       #(id_atu, id_fuh, id_yfp).(str_fkm$0 /= str_ohe) }) /=
  { id_sfp, id_jge, id_ipc, id_eit, id_yjg, id_ihw, id_ixw, id_skk, id_xog,
    id_kwj
    |
    NAT /= str_vpr }

INITIALISATION
  BEGIN
    BEGIN
      id_acs, id_qaa
      :=
      struct
        (id_dfq: str_fsp$0,
         id_lju:
         struct
           (id_fem: INT,
            id_cbs: 9,
            id_rzt: str_say,
            id_gxt:
            rec
              (id_tlk: NATURAL1,
               id_sgx: str_pcy,
               id_asb: str_wds$0,
               id_yuy: str_hoy,
               id_yso: str_phl$0),
            id_zay: INTEGER,
            id_xse: STRING,
            id_zah: STRING),
         id_rin: str_hda$0,
         id_fkj: bool(str_uen /<: str_zwa),
         id_gmc:
         {str_cci$0,
          str_hcn,
          bool(STRING <= str_wbp),
          str_yhm,
          struct(id_mkb: "str_dgh"),
          str_elt$0,
          str_gnh}) ;
      id_czo'id_vgu
      :=
      front
        ({ id_xxk
           |
           #
             (id_xzn, id_lji, id_xuj, id_iqu, id_ozm, id_ffd, id_vor, id_fjr,
              id_qbp, id_wqv).
           (!(id_azo, id_qox, id_sgh, id_oww).
            (#(id_abd).(not(str_kjp >= str_wuo$0 or str_dkr <: BOOL)))) })
    END ||
    id_ofc, id_rgl, id_ujl, id_lhd
    :=
    bool
      (not
         (!(id_nhp, id_gws).
          (#(id_xit, id_xyb).(not(!(id_imp, id_doa).(FALSE /<<: str_idx))))))
  END ;
  LET
    id_aoi, id_amq, id_sdg, id_hhu, id_pwv, id_tys
  BE
    id_hep
    =
    {str_ftx,
     str_vmb$0,
     [rec
        (id_ter: INT,
         id_xyu: INT,
         id_gif: str_xvf$0,
         id_qsq: str_dfm$0,
         id_uqv: str_jkh$0,
         id_prv: str_bjt$0,
         id_svi: str_fps)
        'id_auq,
      str_pxc$0],
     str_bgw$0,
     str_mnq$0,
     bool(#(id_ngl, id_fkp, id_okp, id_abw).(BOOL : str_lrj$0)),
     MAXINT,
     str_xma$0}
      'id_zbk&
    id_dxv
    =
    {{},
     (NATURAL1 ^
      struct
        (id_jni: TRUE, id_iuf: str_mzx, id_snb: str_qrm$0, id_wxt: str_dlv)),
     str_flv$0,
     str_hio,
     str_kbf$0,
     max
       (PI(id_clf, id_mqd, id_zsi, id_npk, id_zme).
        (str_ujo$0 = str_ivq$0| str_alx)),
     bool(str_yvq : {})}
      'id_fel&
    id_mji
    =
    rec
      (id_jxn: str_ljv,
       id_qbn: INT,
       id_bxv:
       { id_kqz, id_iqw, id_mka, id_srv, id_lpf, id_hsc, id_lto, id_iso
         |
         !(id_omv, id_psp, id_rey).
         (#(id_dvh, id_yye, id_xjo, id_fls, id_hks, id_urc, id_dum).
          ((BOOL /: str_hqv$0 => str_bcm$0 > NATURAL) & not({} <= STRING))) },
       id_ivy: BOOL,
       id_hvb: str_sjq$0)&
    id_dhy
    =
    struct
      (id_jbd:
       bool(%(id_cbj). (top(str_qzt) <= str_ahi$0| INT) >= sizet(str_qem)))&
    id_fqq
    =
    closure1
      ({NATURAL, str_msw$0, 4, str_vps$0, str_cfm, str_euj, str_fgs$0}'id_rfl
         'id_rwo <<|
       [rec(id_qfb: {}), str_hjt$0])&
    id_hfs
    =
    { id_cor, id_oka, id_vmg, id_sjh, id_qtm, id_xgr, id_qxy, id_ifz, id_kgt
      |
      #(id_sqb, id_exb, id_tdv, id_mcy).
      (!
         (id_lli, id_voq, id_kcm, id_uff, id_gea, id_dcn, id_wer, id_wbg,
          id_pcd, id_bal, id_qch).
       (str_ysp >
        [{},
         struct(id_xqu: MAXINT),
         struct
           (id_rud: str_srt$0,
            id_roq: MAXINT,
            id_mtp: str_owy$0,
            id_dco: str_qiv,
            id_gmw: str_uob)])) }
  IN
    WHILE
      {struct
         (id_lla: str_ant$0,
          id_sjk: 7,
          id_ppt: str_zcr,
          id_zst: STRING,
          id_aio: str_tmu$0,
          id_wny: str_bev$0,
          id_pkk: {})
         'id_yjd,
       [str_btj, str_xnu$0, str_bfj, INT, {}, NATURAL1, NAT]} =
      father({ id_mbh | str_pbv$0 < 32 })
    DO
      VAR
        id_zhn, id_jzk, id_ogr, id_cbt, id_exj, id_way
      IN
        id_yxw'id_grz
        :=
        rec
          (id_vki: str_tth$0,
           id_gjd:
           %
             (id_tft, id_moq, id_not, id_gzl, id_wxc, id_duu, id_tuh, id_ywc,
              id_xzk, id_mcc).
           (INT >= str_nik| str_gtl),
           id_jjg:
           [str_cad$0,
            str_btb$0,
            str_rjf$0,
            str_ead$0,
            prefix(STRING),
            str_zql$0,
            FALSE,
            str_yga$0],
           id_ssv: POW1(STRING),
           id_gty: bool(NAT1 <<: str_fqh),
           id_bzf: str_cua)
          'id_vsq ||
        id_gqd 
          (
            INTER
              (id_awv, id_gew, id_wis, id_ukt, id_otr, id_rqc, id_qgr,
               id_bjo, id_axo, id_nsa).
            (str_yds : str_ndj$0|
             bool
               (!
                  (id_hwn, id_eko, id_abq, id_ycz, id_uyf, id_mdh, id_ivb,
                   id_srp, id_ulx).
                (not
                   (!
                      (id_hai, id_fat, id_gcl, id_aem, id_xad, id_dlb,
                       id_bri, id_ysu).
                    (str_jcz <= str_avn)))))
              'id_tra
          )
          (
            POW1
              ({str_sdu,
                [str_ajq$0, NAT1, MININT, str_srk$0, NAT, str_gyn, NAT,
                 str_avs$0],
                {{},
                 str_vxw,
                 "str_ogj",
                 str_goh$0,
                 MAXINT,
                 PI(id_vnc, id_mwc, id_iyh, id_bma).
                 (TRUE <: BOOL| { id_ilg | str_zcu > TRUE }),
                 NATURAL},
                [str_hbw, str_ekd, str_ptu$0, str_ldy$0, INTEGER, str_cyn,
                 str_aik$0]})
          )
          (
            bool
              (!
                 (id_vjd, id_vsc, id_ycw, id_hje, id_who, id_zur, id_nvc,
                  id_vfe, id_nct).
               (!
                  (id_yqz, id_vjm, id_kqq, id_jls, id_kdc, id_xle, id_psx,
                   id_lrf, id_chs).
                (!
                   (id_lje, id_eme, id_oxf, id_rwt, id_gqj, id_cef, id_xwj,
                    id_fow, id_urz, id_nrs).
                 (#
                    (id_oav, id_rhe, id_plm, id_dcn, id_brl, id_idx, id_cfp,
                     id_iun, id_qjw, id_qhx, id_hgs).
                  (str_vgd > TRUE => not(NATURAL <: str_nlq))))))
          )
          (
            {FALSE,
             { id_ion, id_ivj, id_dio, id_xwv, id_uei, id_req, id_ggx,
               id_mot, id_qsu
               |
               NAT1 /<<: str_idx$0 },
             bool(INTEGER /: NATURAL1),
             MAXINT,
             rec
               (id_qbb: str_fhm,
                id_kah: str_xxm,
                id_kan: str_sqf$0,
                id_swo:
                (INTER
                   (id_xnf, id_aml, id_qfo, id_lsl, id_jgw, id_cpo, id_aav,
                    id_jsc, id_mlk, id_ctj).
                 (str_dry < str_ulg$0| str_vdc$0) |->
                 str_kwn$0),
                id_yup: {},
                id_yby: str_ppb)
               'id_ssu}
          )
          (
            SIGMA
              (id_hky, id_jgi, id_eqj, id_zqt, id_bqu, id_fhf, id_ohn,
               id_tcj, id_rlt).
            (MAXINT = str_mml|
             {{"str_anw",
               { id_cjm, id_phm, id_xbq, id_mbr, id_yat
                 |
                 str_kbp$0 /<<: str_gox$0 },
               struct(id_ddx: (str_ivt$0 mod MAXINT)),
               str_cvh}}
               'id_yme)
          )
        
        :=
        struct
          (id_jqu: STRING,
           id_bwf: rec(id_hrp: rec(id_hue: rel(tail(str_gbj'id_mit)))))
          'id_sch
      END
    INVARIANT
      #(id_pmp, id_rni, id_xco, id_rmf, id_gir, id_bkf, id_efx, id_zes).
      (not
         (bool
            (!
               (id_xhh, id_ycp, id_qzl, id_ybe, id_tys, id_rtc, id_pou, id_ndd).
             (str_fan /= bool(str_ein$0 > str_fgz$0))) >
          str_qlk))
    VARIANT
      bool
        ({ id_xhi, id_yfe, id_nyh, id_ssf, id_wrm, id_bha, id_osc, id_qdw
           |
           str_qgp > [] } /<:
         str_dmv$0 =>
         conc(str_per -> NATURAL1) /: "str_aqa")
    END
  END

OPERATIONS
  id_wyx, id_fxd, id_olc, id_xkh, id_bts, id_ina, id_gbc
  <--
  id_dwm (id_znn, id_zxg, id_omf, id_bno, id_pnh, id_rte, id_zkh)
  =
  CASE
    {{MAXINT, INT, str_edk$0, {str_zqn}},
     str_iln$0,
     {NATURAL, str_krx, STRING, str_grw$0, str_gvz, str_wbv$0, str_blr}
       'id_rbs,
     { id_hxg, id_ouf, id_xuy, id_wdl, id_ypl, id_sxm, id_add, id_uit
       |
       INTEGER = str_aag$0 & str_obm$0 /: MAXINT }}
    OF
    EITHER
      son
        ({ id_lsg, id_rmz, id_rxt, id_let, id_nqg, id_xaz, id_hbe, id_kxm,
           id_nrc
           |
           str_gko =
           { id_juq, id_liu, id_ecp, id_mho, id_nij, id_oti, id_nsn, id_fgy,
             id_lcq, id_olf, id_hgd
             |
             str_vnw$0 /<<: str_ftz =>
             !(id_bnw, id_zbh, id_jsu, id_pno).(str_lys /: str_wda$0) } })
    THEN
      CASE
        [INT,
         {str_jzc$0, [], [], NAT, NATURAL1, str_dwx$0, top(NAT), str_bdx$0},
         PI
           (id_zvh, id_etb, id_ksc, id_nqb, id_xpr, id_zex, id_pty, id_mxv,
            id_rdp).
         (not(TRUE /<<: str_mff)| STRING),
         "str_yzn"] |>
        struct(id_iyl: FALSE, id_ptb: STRING, id_tas: str_ysu)
        OF
        EITHER
          { id_qgl, id_tze, id_ldb, id_kbx, id_ipm, id_efx, id_weo
            |
            !(id_kjv, id_qny, id_cdy).
            (!
               (id_bbb, id_ppe, id_yma, id_anj, id_jrt, id_zpn, id_bfq,
                id_gay, id_ywp, id_pmy).
             (bool(MININT /: str_nbm)'id_xpm < str_peo)) }
        THEN
          id_qwg, id_tgz, id_xlx, id_jin, id_gqx, id_rkh, id_lax, id_rop
          ::
          rec
            (id_ccz: MAXINT,
             id_xqv: NAT1,
             id_tiz:
             { id_vck, id_njm, id_zot, id_mbs, id_tlq, id_hlx
               |
               not
                 (not
                    (!
                       (id_zis, id_wpc, id_afz, id_akt, id_wzl, id_snl, id_ezz).
                     (#
                        (id_oyj, id_hyg, id_llp, id_fib, id_rrq, id_ait,
                         id_pqk, id_oti, id_pyz, id_hma).
                      (#
                         (id_qqb, id_zff, id_uot, id_uem, id_ujx, id_gmz,
                          id_rgg).
                       (INT > str_gqu))))) })
        OR
          [bool(not({} <: str_slp)),
           str_odz$0,
           INTEGER,
           BOOL,
           str_ynf,
           { id_dyk, id_wpj, id_fwy, id_xoq, id_mcd | FALSE <<: str_rts$0 },
           {TRUE,
            str_rsn,
            rec
              (id_nlw: NAT1,
               id_wak: 283,
               id_fpo: TRUE,
               id_jqy: str_khj'id_jts),
            str_yjp},
           str_qdz$0]
        THEN
          id_lad  ( bool({str_rlq$0} = [(prefix(6)'id_htu \/ str_sgm$0)]) ) 
          :=
          struct
            (id_cnc: [str_coj$0, str_fct$0, str_jca, str_hvk$0],
             id_pji:
             {SIGMA
                (id_wvh, id_plb, id_jav, id_exn, id_tom, id_ubl, id_akd,
                 id_yae, id_wrg, id_sfy).
              (str_qfs$0 < []|
               rec
                 (id_wwp: STRING,
                  id_ygy: str_bdk$0,
                  id_bgj: str_tbo$0,
                  id_iro: str_jvv,
                  id_uoq: MININT,
                  id_xrb: str_ckp)),
              str_kqa,
              "str_yme",
              struct(id_fyp: str_iii, id_ilx: str_qyl),
              str_ove,
              NATURAL1},
             id_jap: NAT1,
             id_nnf: str_cwl$0)
        END
      END
    OR
      SIGMA(id_tub).
      (not(not(str_lxp$0 : str_nxg))|
       rec
         (id_sjn: str_qnd$0,
          id_ssp: str_pri$0,
          id_qmh: str_rsn$0,
          id_ogn: TRUE,
          id_hlw: INTEGER,
          id_qwh: [son(str_udf$0'id_mkl), str_nez$0],
          id_ocm: str_bvx$0,
          id_mwh: str_fmd$0))
    THEN
      VAR
        id_nqx, id_xyh, id_zfl
      IN
        CHOICE
          WHILE
            !(id_cvz, id_noj).
            (INTER(id_qjc, id_dsz, id_ffo).
             (not(TRUE <= MININT)|
              SIGMA(id_hai).
              (str_owo /=
               {str_ovz$0, str_stj, str_gbo$0, str_sea$0, MININT, str_psd$0}|
               str_qcc)) /<<:
             str_yyi$0)
          DO
            ANY
              id_udv, id_whg, id_edu, id_gsb
            WHERE
              not
                (!(id_nmg, id_geg, id_tnq, id_cqt).
                 (not
                    (not
                       (!
                          (id_mqb, id_cra, id_zxb, id_zjk, id_ucf, id_ojr,
                           id_xne, id_qwf).
                        (not({} /<<: str_ett))))))
            THEN
              id_uaq, id_ddx, id_toh, id_sob, id_bpm, id_nwe, id_kpo
              :=
              (str_tdf$0 <<| rank(bool(str_dsu /<: {}) mod str_xqp))'id_vkd
                'id_cuj
                'id_sun
            END
          INVARIANT
            !(id_fie, id_sjy, id_nrk, id_iii, id_qnf).
            ({ id_bpw, id_esp, id_ccl, id_pfq, id_yag, id_bzk, id_lps,
               id_cww, id_gdf, id_mxd, id_ael
               |
               !(id_ugc, id_kib).(str_wvk <: str_hyy) } >=
             rec
               (id_gby: BOOL,
                id_ito: "str_rra",
                id_bmy: "str_iki",
                id_dfj:
                ran
                  (SIGMA(id_fpj, id_glv, id_hed, id_agq, id_ngv).
                   (str_afx$0 >= STRING| str_lcj)),
                id_iwm: MININT))
          VARIANT
            {str_nep,
             str_spz,
             rec
               (id_cht:
                rec(id_kkg: str_gcd$0, id_kan: INTEGER, id_jsu: str_yfp),
                id_ald: INTEGER,
                id_kbm: str_kaf,
                id_nbf:
                (rec
                   (id_raz: STRING,
                    id_hss: str_dtz$0,
                    id_zbo:
                    %(id_mtc, id_thp, id_xvm).
                    (INTEGER = str_jbw$0| str_iqt$0),
                    id_tyf: str_tie) ^
                 str_irf$0)),
             { id_zzs, id_axr, id_chw, id_lmd, id_soy, id_mvm, id_kyy,
               id_hku, id_jph, id_gfg
               |
               str_svv$0 <: str_pok },
             str_kyw$0}
          END
        OR
          id_tdf'id_jcx
          :=
          iterate
            (id
               ({ id_afq, id_wlu, id_kei, id_alv, id_dqj, id_sud, id_vck,
                  id_sio, id_wnm, id_hfe, id_nea
                  |
                  str_dld /= str_mtz }),
             bool
               (!(id_efn, id_wox, id_ipg, id_cgn, id_ohc, id_oqs, id_tow).
                (!
                   (id_aom, id_ftx, id_szd, id_xdu, id_xsa, id_ojq, id_wkn,
                    id_xqc).
                 (str_nwk$0 <<: str_sdk => FALSE <= str_yqn))))
        OR
          skip
        OR
          ANY
            id_vfg, id_daz, id_ygc, id_skd, id_evf, id_lck, id_dmd, id_mcg
          WHERE
            #(id_qtu, id_wzd, id_tbz).
            ({ id_lcl, id_mth, id_tzq, id_pyl, id_vlo, id_wlv, id_xfb,
               id_zit, id_jmo, id_pov
               |
               str_erv$0 <: str_lap } /=
             struct
               (id_wgr: right(INT),
                id_xyc: str_dwn$0,
                id_vpy:
                (INTEGER |->
                 { id_ejy, id_asd, id_zvw, id_oot, id_baw, id_iuu, id_lju
                   |
                   str_cje$0 <: str_oyr }),
                id_ede: str_vau))
          THEN
            id_kdh, id_hji, id_yco, id_pov, id_yxc, id_vse, id_mmh :(
              #(id_ixy, id_gya, id_xur, id_exo, id_xyh).
              (#(id_gls, id_eyw, id_czq, id_qap, id_fmr, id_ooq).
               (not
                  (FALSE > MININT <=>
                   not
                     (not
                        (!
                           (id_dte, id_xzm, id_usi, id_hhm, id_ylh, id_wgq,
                            id_cdc, id_pyc, id_nwq).
                         (NAT /: str_lgz))))))
            )
          END
        OR
          id_qcw, id_pmw
          ::
          struct(id_fsr: STRING, id_eaj: NAT1, id_vrb: str_vvg) -
          SIGMA(id_kds, id_hhq, id_lmt, id_olj).
          (str_hat <= str_twm|
           {str_ngz,
            str_vre$0,
            { id_hon, id_nhf, id_zux, id_ann, id_tkq, id_ncs, id_mdf, id_lkw,
              id_cwc, id_siv
              |
              not(!(id_imr).(str_hgc /= str_lsy)) },
            str_bsd$0,
            BOOL})
        OR
          id_uik, id_xcq, id_rhi, id_nlk, id_env, id_klf, id_vkj, id_pve
          <--
          id_ych
            (bool
               (struct
                  (id_paw:
                   max
                     (POW1
                        ([str_jth$0, str_ktg, str_aga$0, str_eog$0, MAXINT,
                          str_ust$0, str_uzg$0]))) <<:
                struct
                  (id_bzk: str_uah,
                   id_zmr: NATURAL1,
                   id_hga: str_hol$0,
                   id_xgc: {})),
             rec
               (id_wpl: str_eka,
                id_rvf:
                [struct
                   (id_gby: str_pcu$0,
                    id_ekg: str_bvn$0,
                    id_bca: str_gqz$0,
                    id_sre: str_ifw$0,
                    id_hds:
                    {str_ehx$0, str_fid, str_wtt$0, str_fcr$0, str_ulb$0,
                     str_stk, NATURAL, str_cst$0},
                    id_awc: str_dnd$0,
                    id_fkc: str_jrb,
                    id_zyt: (str_sox , bool(str_vqi$0 /<<: TRUE)))],
                id_nox: str_apn,
                id_knm: str_fuv$0,
                id_clm: str_bxx,
                id_omt: str_aaj$0,
                id_ehg: str_kas)
               'id_xpb,
             { id_qce
               |
               !
                 (id_yex, id_bme, id_kre, id_sct, id_uav, id_vfe, id_ggx,
                  id_wcb, id_bpz, id_ass, id_lef).
               (#(id_thn, id_bga, id_iph, id_ysg, id_oth).
                (!(id_mvz, id_brr, id_pco, id_xli, id_ctc, id_ubt, id_xgx).
                 (#(id_fso, id_khj).(MAXINT /<<: MAXINT) & TRUE <<: str_dfp$0))) },
             (inter
                ([str_rbc$0,
                  { id_unx, id_vat, id_bxt | str_ajq$0 < 7 },
                  str_yrs$0,
                  str_kkr$0,
                  str_ubj,
                  struct
                    (id_ysn: STRING,
                     id_ngn: str_dng,
                     id_uwl: NAT,
                     id_ftb: str_qlb,
                     id_iav: str_afg),
                  TRUE,
                  str_hkq$0]) <+
              bool(str_rjz$0 >= str_job & str_xsu$0 > str_jxn)),
             { id_fak, id_dml, id_ajx, id_rkz, id_qdd, id_jrg, id_pqv,
               id_jfc, id_tfq, id_sfg, id_gev
               |
               #
                 (id_cox, id_vse, id_cqv, id_ycn, id_bbg, id_cev, id_pfz,
                  id_fmm, id_kqx).
               (!(id_zdl, id_xev, id_ybe, id_bgu).
                (#(id_cyx).
                 (%(id_qta, id_ydz). (str_mcb$0 /: INT| str_fda) =
                  mirror(str_hig$0)))) },
             bool
               (!(id_fix, id_bck).
                (not
                   (!(id_jjl, id_bkw, id_fpp, id_rvq, id_fiu, id_wnl, id_uda).
                    (NATURAL /<<: str_guf$0) <=>
                    #(id_ktx).(not(str_rai >= str_vff$0))))),
             {(str_yyl$0 / str_obt),
              INTER(id_zgz, id_kyp, id_vni, id_rcq).
              (MININT > str_icd & (str_oan > str_ses or NATURAL1 <<: str_ilo)|
               {str_wmf$0, str_isn, str_eby$0, str_tbu, str_cec$0, str_mxw,
                MININT}),
              2})
        END
      END
    END
  END

END 