MACHINE
  str_wkl( str_rck, str_slz, str_ure, str_bua, str_brn )

OPERATIONS
  str_huh, str_jdx, str_qut, str_gtf, str_xol
  <--
  str_foo (str_tzc, str_ftk, str_upn, str_iyl, str_ivc, str_fln, str_fks)
  =
  CASE
    rec
      (str_agx: {{str_frj$0, str_uif}, ((str_phw(NAT)) |-> str_gyt)},
       str_xgd:
       [str_msk$0,
        %(str_wai, str_mvt, str_hbn, str_sdu, str_zzj, str_ntw, str_cpu).
        (NAT1 = str_fwd| str_mws)])
    OF
    EITHER
      struct
        (str_chy:
         [(str_zpr$0 \/ str_tsw),
          MININT,
          (POW1(str_qzu$0)),
          str_hit$0,
          bool(str_kbp$0 /= STRING),
          (str_ebj$0 * str_opb$0),
          str_don$0],
         str_ohi: str_prh,
         str_vtb: [str_yok$0, FALSE, str_ttm$0, []])
    THEN
      ANY
        str_bfg, str_ipz, str_liz, str_xvr, str_mal, str_wfb, str_unq,
        str_kzk
      WHERE
        str_aiw /<<: str_guo$0 or
        str_ozg$0'str_fuz <=
        {(sizet
            (rec
               (str_fog: [],
                str_dkx: str_syu,
                str_ogh: str_tgn,
                str_qjt: str_dza,
                str_uao: str_fks,
                str_azv: str_ybb,
                str_mjx: str_flh$0)))}
      THEN
        PRE
          not
            (str_qtq <: str_uyf &
             str_zdm$0 <: STRING &
             not
               (str_snj$0 /=
                { str_rof, str_shc, str_qku, str_oqr, str_bna, str_oft,
                  str_vfe, str_qyd, str_ach
                  |
                  !(str_zyv, str_zbl).(str_ugt <: str_uws) }))
        THEN
          str_qfa, str_qwv, str_wbw, str_wju, str_bwl, str_nqa, str_sgj,
          str_ymj, str_eqt :(
            #(str_xyt).(str_aci <<: FALSE) =>
            !(str_myr, str_bqn, str_mwc, str_iqh, str_cjm, str_vbs).
            (!(str_uzx).
             (not
                ((STRING /<<: str_jfi$0 or TRUE /= str_dhi$0) &
                 INTEGER /<: INTEGER)))
          )
        END
      END
    OR
      (front(bool(str_ztf : {NATURAL, str_bjr, NAT})))'str_ptq
      |->
      { str_tre, str_fxq, str_oal, str_yax | str_ati$0 <<: str_fqt }
    THEN
      str_ffm, str_uzg, str_sqq, str_nvs, str_iec, str_pzz, str_kkj, str_api
      ::
      bool(str_zso$0 : NAT)'str_nla
        [struct
           (str_bth: str_rom$0,
            str_fuu: str_owz,
            str_tuk: str_jkj,
            str_pso: NAT,
            str_sxn: str_gbm$0,
            str_nmi: str_hfe,
            str_nch: str_ici,
            str_tex: NATURAL)
           (struct
              (str_ooo: str_efp,
               str_xji: (FALSE |-> str_jbf$0),
               str_zqd: str_fza$0,
               str_fhb: str_doe))]
    OR
      { str_bdl, str_tgg, str_hus, str_ioo, str_lum, str_fhg
        |
        (INTEGER /: str_xnn$0 <=> str_xva : str_xyx) =>
        (MININT <: str_bco$0 =>
         #(str_wda, str_bzp, str_kpy, str_ypz, str_ewl, str_fue).
         (#
            (str_nsq, str_hiq, str_dfu, str_ppv, str_ljc, str_yaj, str_ryf,
             str_eil, str_wby, str_bwy, str_ees).
          (#(str_ryp, str_hzt, str_yzd).(str_gng <<: str_ibw)))) }
    THEN
      str_mxi, str_gzs
      ::
      {%
         (str_ymp, str_xaq, str_jpt, str_hlx, str_byo, str_vbp, str_fwv,
          str_ezi, str_con, str_suc, str_lhg).
       (str_pdl < str_zve$0| str_cfh$0),
       str_bxk$0}
        (bool
           (#(str_fjq, str_qxy, str_xru).
            (!(str_obv, str_xwh, str_lbs).(str_uem = NAT))))
    OR
      {[str_gjw$0, BOOL, str_arr, str_eoi, [BOOL], (str_dck$0(TRUE))],
       { str_lbz, str_fxv | str_nsa < str_wpa$0 },
       rec
         (str_yek: INT,
          str_zgj: FALSE,
          str_rjj: str_pjd$0,
          str_mnj: BOOL,
          str_vso: str_fbl,
          str_nvm: str_qcb$0),
       INT,
       (str_mvl$0(str_bxd$0)),
       str_mwx,
       str_cfx$0}
    THEN
      IF
        str_jzz =
        bool
          ([INTEGER,
            MAXINT,
            bool(str_nam <<: NAT1 or str_qyw : INT),
            str_yhh,
            str_gye$0,
            str_vzo,
            str_ont$0] >
           rec
             (str_rqe: str_vfu$0,
              str_ync: NAT,
              str_jkw: str_vnt$0,
              str_aua: str_ctk,
              str_szv: MAXINT))
      THEN
        ANY
          str_pyi, str_nxi, str_npt, str_xnh
        WHERE
          bool
            ([] <<: NAT =>
             str_wem >=
             { str_qfr, str_ymv, str_qfi
               |
               not
                 (#
                    (str_sxj, str_jqt, str_gbj, str_wvq, str_kvh, str_qjr,
                     str_jab, str_vvj, str_pab).
                  (str_bwh >= str_gny)) }) :
          str_mpo$0
        THEN
          str_moy, str_rue, str_zgo, str_rdk, str_kps, str_jxn
          <--
          str_yst
            ({ str_qde, str_fbt, str_uej, str_lhs, str_dov, str_evg
               |
               #
                 (str_vkl, str_fla, str_ryv, str_rob, str_pmp, str_noy,
                  str_hxo, str_rht, str_xte).
               (#
                  (str_tvj, str_dgs, str_llg, str_yya, str_jip, str_knk,
                   str_whx, str_fft, str_nxc, str_dax, str_tqv).
                (!(str_fku, str_bun, str_ihv, str_yvw, str_msw, str_zyb).
                 (not
                    (str_qlk$0 /= str_ldm or
                     (str_ujz$0 /: str_nmq <=> str_fjq /= str_btu))))) },
             ((card
                 ({ str_pgp, str_iif, str_imh, str_kwz, str_ape, str_htf,
                    str_tjj
                    |
                    not([] >= str_mjc) }))
                (struct(str_ldc: str_btp, str_qyk: (NATURAL1(str_tmx))))),
             rec
               (str_pye: str_qbs$0,
                str_bct: str_hdg,
                str_dvy: str_xds,
                str_ubx: str_ztl$0,
                str_gwh: NATURAL,
                str_wnb:
                {{str_jvi, str_rtz, (str_kor$0 - str_ytu$0), 0, TRUE, str_bhz}},
                str_hzm: str_usi,
                str_dbh:
                (rec
                   (str_spk: str_xug,
                    str_hdo: [],
                    str_tii: str_ilx$0,
                    str_opk: str_hba$0,
                    str_khp: str_haq$0,
                    str_saj: str_gts$0,
                    str_ujx: 2,
                    str_too: str_umr$0)
                 ,
                 SIGMA(str_kkq, str_orq, str_yyc, str_moe).
                 (NATURAL <<: str_dxp$0| str_row))),
             (struct(str_bne: str_oxc$0, str_eew: FALSE, str_icq: str_mwx$0)
              ,
              (((struct(str_aog: MININT) , (sizet(str_bih))) |-> [])(str_zej))),
             { str_wlj, str_krq, str_oba, str_ams, str_civ, str_dtz, str_bob,
               str_uru, str_mnq, str_vxj, str_krs
               |
               str_vot$0 /<<:
               MAXINT
                 (bool
                    (#
                       (str_vpr, str_qoo, str_fuv, str_tsg, str_hqz, str_mcc,
                        str_qkg, str_rfx, str_dtq).
                     ([str_ogu$0, MININT, MAXINT, str_coq$0, "str_jnw"] <:
                      MININT))) },
             (sons
                (UNION(str_buf, str_bhh, str_ddv).
                 (#
                    (str_kzg, str_iwf, str_dtu, str_wdv, str_dti, str_uqu,
                     str_flg).
                  (str_rlj /<: []) <=>
                  str_uhf = str_ewr$0|
                  STRING |-> (str_pmg$0 .. (bin(str_zjf)))))),
             {PI
                (str_dgb, str_uof, str_wyu, str_rnj, str_fst, str_cqg,
                 str_csh, str_err, str_dfz, str_vqf).
              (!
                 (str_wsx, str_cvg, str_iwi, str_pmm, str_vqq, str_yrx,
                  str_fog, str_byu).
               (#
                  (str_kjo, str_ajh, str_bvh, str_kkx, str_knb, str_ukq,
                   str_ffj, str_gwt, str_fjm, str_ryx, str_lit).
                (str_bta <: str_qmo)) or
               (not(str_acl$0 : NAT) <=> TRUE /= str_ysq)|
               {}),
              str_gog$0,
              MAXINT},
             ((const
                 (struct
                    (str_eph: str_wzg$0,
                     str_vut:
                     { str_cna, str_jyb, str_zwy, str_gsb, str_wpl, str_bnn
                       |
                       (FALSE <<: str_vhd$0 or
                        (str_obr$0 = [] => NAT1 : NAT1)) <=>
                       str_nvf$0 < str_xqm$0 },
                     str_tvm: str_rko$0,
                     str_wyf: str_yxn$0,
                     str_xnj: str_ofb,
                     str_zwd: MININT)))
                (str_hag$0)),
             [str_ioy$0,
              (str_fch |-> NAT'str_wnz),
              str_ndw,
              (str_sdk$0
                 (struct
                    (str_abh: str_cym,
                     str_wxv: str_cew,
                     str_mns: FALSE,
                     str_rob: str_rcr,
                     str_ndh: str_fjt$0,
                     str_whk: MININT,
                     str_iqn: str_kzi$0))),
              rec
                (str_uut: str_qku,
                 str_xku: str_kft$0,
                 str_wcp: str_lor,
                 str_xyp: bool(str_byz$0 /: str_wst$0),
                 str_dvb: STRING,
                 str_ked: str_gxb$0,
                 str_zqt: str_lcg,
                 str_cha: str_wwe)],
             bool
               (str_cpd > str_sfw or
                rec
                  (str_knk:
                   rec
                     (str_oyq: str_ucf,
                      str_tnr: TRUE,
                      str_jkj:
                      struct
                        (str_xcy: str_tua,
                         str_tda: NAT,
                         str_oaj: str_uqe$0,
                         str_tit: str_zui,
                         str_tux: NATURAL1,
                         str_oux: str_lrz,
                         str_zep: str_nqm$0),
                      str_xpp: str_maa$0),
                   str_rsu: str_zsf,
                   str_ign: str_ogs$0) /=
                str_trt(str_alo)))
        END
      ELSIF
        !(str_wir, str_jnc, str_hxh, str_hjz, str_ppd).
        (UNION(str_soj, str_kvg). (not(str_aiu$0 = INTEGER)| NAT1 , MAXINT)
           'str_lqb <:
         str_bhm)
      THEN
        skip
      ELSIF
        #
          (str_ktl, str_ptv, str_vko, str_mbq, str_pwt, str_piy, str_roq,
           str_rtk, str_jup, str_qxz).
        (#(str_rno, str_hjv, str_rdo, str_vmg, str_tgt).
         (not(str_wlg <: str_jeb$0)) <=>
         struct(str_oqc: SIGMA(str_bzy). (str_koi /: NATURAL1| str_uqm$0)) /=
         str_tfq)
      THEN
        PRE
          not
            (!
               (str_uxq, str_bcz, str_qcw, str_uhf, str_ukz, str_yfd,
                str_onz, str_ujo, str_ibc, str_zgt, str_ffe).
             (#
                (str_hoi, str_cqm, str_onq, str_agv, str_kpa, str_mbm,
                 str_bdl, str_set, str_eio).
              (!
                 (str_meo, str_rcy, str_yzp, str_ger, str_lfq, str_hfb,
                  str_juv, str_myy, str_sja, str_mjq, str_nne).
               (str_wsm$0 >
                [{str_cer$0, str_bsz, str_vqp, str_jdn$0, str_bxy, [],
                  str_src, []}]))))
        THEN
          str_kbg, str_cse, str_qcw, str_kvp, str_ixl, str_ody, str_hgl,
          str_htu
          ::
          (FALSE /\
           ({rec(str_mla: str_ukt),
             (right("str_zsb")),
             str_nlv,
             str_pyv,
             str_jgs} -->>
            (NAT(str_mqr))))
            'str_jxc
        END
      ELSIF
        {STRING, str_gow$0} <=
        rec
          (str_lut: (btree(str_ffj)),
           str_ekg: str_ljg,
           str_bwc: str_ssu,
           str_lbb: ([bool(str_ben$0 <: str_jiq)] +->> str_qca$0),
           str_jwe: str_xtm)
      THEN
        str_jfy'str_bkp
        :=
        UNION
          (str_scx, str_vzl, str_bve, str_zah, str_rcc, str_wqf, str_udv,
           str_qpi, str_gyj, str_jsx).
        (!
           (str_hzj, str_twf, str_uqq, str_kfm, str_vuu, str_ghe, str_uvh,
            str_qxd, str_zpl, str_kwh, str_asp).
         (!(str_gnc, str_jdv, str_glh, str_muo, str_ezc).
          (str_tuw$0 <<: str_zhl) <=>
          str_zjx <<: str_ygt$0)|
         seq
           ([STRING,
             { str_nvs, str_sol, str_lht | str_jkx$0 <= MININT },
             str_jzx$0,
             INT,
             str_idn]))
      ELSIF
        !(str_evk).
        (!
           (str_tgv, str_who, str_bub, str_hmx, str_ctj, str_kmh, str_eft,
            str_qkk, str_knb).
         (not
            (bool
               (!
                  (str_uch, str_iwx, str_sjw, str_bnz, str_izb, str_kjm,
                   str_uto, str_odu, str_vew, str_mjo).
                (str_kgb = str_exc$0))
               'str_tgq /<<:
             str_iyl$0)))
      THEN
        str_ttp, str_kfs, str_vif, str_vkb, str_bxc, str_mfz, str_kdu,
        str_jqj, str_yie
        ::
        {str_olx$0'str_hvv,
         (bool(FALSE < NATURAL)(NATURAL1)),
         str_etw,
         str_ybv$0,
         str_yzk$0,
         str_kwz$0} |>>
        [str_lyo,
         {[], str_jhk$0, STRING, str_kvx, str_uzt$0, [], MAXINT},
         str_dmp$0,
         str_txa$0,
         FALSE,
         str_mmc,
         str_zxt$0]
      ELSE
        str_ete
        :=
        [{ str_jwf | str_dmv$0 : str_fnz$0 }, MININT]
          (bool
             (#
                (str_rrk, str_tdl, str_was, str_efc, str_qxo, str_ymy,
                 str_mse, str_xnb, str_nwm, str_xil, str_aqx).
              (str_efm$0 /<<: NAT1 & (str_fjp /<<: {} <=> FALSE = str_exu))))
      END
    OR
      ("str_iez" mod str_puo$0)
      |->
      bool
        (not
           (not
              (!(str_sqp, str_qml, str_cot, str_yep, str_abv).
               (#(str_tgh, str_wyu, str_pip, str_yht, str_npn).
                (NAT1 >= str_lcj)))))
    THEN
      CHOICE
        str_pcs'str_mxb
        :=
        rec
          (str_plv:
           INTER(str_kzk, str_vnw, str_fsr, str_ilu).
           (str_czu$0 /: TRUE|
            ({ str_aom, str_yat, str_yak, str_itz, str_ufg | str_bxd /: FALSE } ||
             str_wzp)),
           str_nst: str_rnh$0'str_vyx,
           str_kaf: [NATURAL1, str_kja$0, str_snh$0, str_kaf$0],
           str_juw: MAXINT)
          'str_tov
      END
    OR
      { str_agy, str_nsn, str_ojy, str_gyo
        |
        !(str_nrk, str_csv, str_qts, str_ihj, str_vss).
        (str_oco$0 <= str_ynj or
         (not
            (!(str_hlx, str_vtb, str_rvs, str_mae, str_uzw, str_lvp, str_dnc).
             (str_uaf /<<: str_zqj)) &
          str_urv$0 /: NATURAL1)) }
    THEN
      str_hig, str_xte, str_syj, str_lap, str_wps, str_imb
      :=
      PI(str_evc, str_zlf).
      (bool(str_lez$0 < str_jfs) <:
       {str_hxf, str_pxs, (right(TRUE)), str_wtq$0}|
       [str_ned$0, BOOL, str_dyr, str_nxu, str_xan, str_yxn, str_smc$0,
        str_rsh$0])
    OR
      STRING ..
      bool
        (not([str_liw$0, str_awe$0, str_val, MININT] < str_kyl$0) or
         !
           (str_ses, str_fjw, str_mqw, str_bjm, str_hsn, str_doi, str_zjw,
            str_oqn, str_dxk, str_fty, str_zjr).
         (str_htb > MININT))
    THEN
      skip
    OR
      rec
        (str_hgn: STRING,
         str_agr: str_sem,
         str_sqx: NATURAL1,
         str_abu: (INTEGER |-> (bool(str_sfu$0 /<<: str_ihv$0)({}))),
         str_vdy: str_whj,
         str_mvv: INTEGER,
         str_idb:
         (POW
            (struct
               (str_jpx:
                rec
                  (str_ihp: FALSE,
                   str_byl: str_ebf$0,
                   str_kho: str_xow,
                   str_gfi: str_feh,
                   str_oss: "str_olp",
                   str_twi: str_tii,
                   str_ibu: MININT,
                   str_xno: str_dwa$0),
                str_bul: str_wpk$0))),
         str_fwj: NAT)
    THEN
      str_fyj, str_lix, str_gcj, str_foy, str_sks, str_stt, str_rou
      :=
      {str_yhl$0,
       [str_zzo,
        [BOOL, INT, STRING, str_ysg, str_dur, NATURAL1, str_fbx, MININT],
        62,
        NATURAL],
       str_ptx$0,
       89,
       str_fih,
       (seq1
          ({str_xhi,
            struct
              (str_nqm: NAT1,
               str_hiu: MAXINT,
               str_bsn: NAT1,
               str_ajl: str_iam,
               str_rnt: STRING,
               str_xwq: str_szx$0,
               str_rfa: []),
            { str_wtx, str_ovu | str_vxo$0 > str_vtw$0 }}))}
    ELSE
      str_wte'str_tgm
      :=
      { str_evh, str_qmy, str_gku, str_chv, str_rra, str_pzz, str_dja,
        str_mee, str_blm, str_ksh, str_iuj
        |
        #(str_eqk, str_aln).
        (perm(str_qwi) <<:
         rec(str_pwk: (INTEGER - str_wzj), str_ioh: str_uqz)) }
        'str_vic
    END
  END;

  str_xzt, str_ovk, str_ogo, str_lwb, str_uot, str_khb, str_yvm, str_upa
  <--
  str_piv (str_bps, str_zfq, str_ahh, str_ycb, str_clh, str_mtq, str_dde)
  =
  BEGIN
    SELECT
      not
        (!(str_otm, str_uxi, str_btb, str_sje).
         (INTER(str_sze).
          (BOOL <= INTEGER => str_ttx$0 /= str_nst|
           SIGMA(str_tqf, str_ofo, str_zcx, str_krj).
           (str_cdp$0 <= str_msh| str_biy)
             'str_rni) :
          INT))
    THEN
      str_jpw 
        (
          bool
            (#
               (str_zjh, str_iup, str_kqx, str_tvh, str_yin, str_keg,
                str_hqc, str_myw).
             (sizet([]) /<:
              right
                ({ str_pef, str_exq, str_fef, str_bfz, str_jsf, str_eqf
                   |
                   !
                     (str_gfw, str_oru, str_mrq, str_pis, str_ois, str_art,
                      str_yre, str_wro).
                   (str_brq$0 > MAXINT) })))
        )
        (
          %(str_dqn, str_gap). (str_bfr >= INT| str_xad$0)'str_xkj'str_cpm <+
          rec
            (str_gol: {str_ndn$0, str_ury$0, [str_xad, str_bjf, [], NATURAL]})
        )
        (
          [{struct
              (str_obb: str_wuu$0,
               str_ztw: str_uap$0,
               str_wpk: str_eov,
               str_emw: NAT,
               str_zxx: INT,
               str_ymn: str_gaf$0,
               str_pfb: []),
            str_ehk$0},
           ({SIGMA
               (str_pam, str_bvw, str_ytk, str_olq, str_lyo, str_ufl,
                str_olp, str_nth, str_iqt).
             (str_vgt$0 : MAXINT| str_cee$0)
               'str_hph,
             str_lyb$0,
             str_cgx$0,
             MININT,
             INTEGER}
              (NAT1))]
        )
        (
          bool
            (bool
               (#
                  (str_ztv, str_hat, str_stv, str_fsr, str_myt, str_nke,
                   str_kqq, str_pzq, str_dzv, str_zqm).
                (#
                   (str_iqe, str_yvy, str_jok, str_zdr, str_fed, str_myc,
                    str_odc, str_ilo, str_son, str_efw).
                 (str_akz = str_hya & not(TRUE : str_jap)))) :
             str_lrq)
        )
        (
          rec
            (str_ttg:
             { str_ulo, str_zci, str_dvt, str_zhs, str_qix, str_zuw, str_xvd,
               str_fsj, str_rbt, str_jhp, str_idi
               |
               (iseq1(str_cto))'str_pnx <:
               INTER
                 (str_ciy, str_dwl, str_ntn, str_ote, str_gqh, str_ofp,
                  str_zzs, str_uwy, str_laf, str_utj).
               (str_dsj /= [] & str_drx /<<: NAT1| "str_qnr") },
             str_hfg: str_rqx)
        )
        (
          {{BOOL,
            str_xqd$0,
            str_qiw$0,
            UNION
              (str_tkr, str_ovk, str_bgp, str_ryg, str_vwv, str_jgy, str_oux).
            (str_hfl$0 = str_fit$0| str_bse$0),
            NAT},
           BOOL,
           str_bme$0,
           (str_dww$0 |>>
            { str_trw, str_cjm, str_uah, str_ooq, str_qst, str_aqt, str_fac,
              str_aid, str_mgv, str_ikd, str_ssp
              |
              str_tno$0 /<: str_krr })
             'str_qmo}
            'str_mus
        )
        (
          { str_btd, str_cpf, str_hxd, str_thl, str_jgo, str_vht
            |
            not
              (#
                 (str_qov, str_wpf, str_lyu, str_qkt, str_nne, str_qwb,
                  str_oni, str_flq, str_wod, str_tat).
               (#
                  (str_mqe, str_dza, str_plx, str_qzz, str_ngc, str_mkh,
                   str_too, str_blr, str_zei, str_uua, str_fjj).
                (#
                   (str_dxh, str_dyk, str_mcd, str_tjr, str_amg, str_ukd,
                    str_trm, str_csx, str_kde, str_xph).
                 (TRUE /<:
                  struct
                    (str_zqj: 4,
                     str_bes: str_fwm,
                     str_lih: str_eya,
                     str_vvj: str_jls$0,
                     str_yyl: str_vac))))) }
        )
      
      :=
      rec
        (str_fir: str_raa$0,
         str_dyi: str_ozc$0,
         str_ipj:
         [(str_aex , NATURAL),
          str_xmq,
          {},
          struct
            (str_yqo: TRUE,
             str_mdf: str_wtm,
             str_rxx: str_rbb$0,
             str_ruu: str_tle),
          { str_fcb, str_amt | str_dak$0 /<: BOOL }]) ^
      struct
        (str_tdv: str_agp,
         str_nlb: str_kzd$0,
         str_zyd: NATURAL,
         str_opc: str_vnj$0,
         str_ajq: str_yrh$0)
    WHEN
      #
        (str_ufj, str_bju, str_mwr, str_mhs, str_vqq, str_vvj, str_kfg,
         str_mya, str_rhy, str_htt).
      (SIGMA
         (str_trl, str_nmw, str_fax, str_yzh, str_yob, str_srl, str_obv,
          str_faq).
       (str_tob : str_dge| str_ljo) <<:
       { str_bzr, str_glw, str_jdf | str_zdg /= str_tbf$0 } ..
       UNION(str_fgs, str_oqm, str_kmh).
       (str_jwy >= str_kwb => str_enq$0 <: str_zuc| FALSE))
    THEN
      str_ivd 
        (
          rec
            (str_pde: {},
             str_paq: rec(str_uft: str_dow$0),
             str_und: {NATURAL, [TRUE], (MAXINT(str_wqx$0)), str_iuf},
             str_zzz: {str_pfy},
             str_tnm: STRING,
             str_tee: (const(MININT)))
        )
        (
          INTER
            (str_thg, str_gka, str_uhe, str_qgf, str_wlw, str_mjk, str_faf,
             str_uzv, str_wlq).
          (STRING : str_nck|
           infix
             (INTER(str_yey, str_qxp, str_xmm, str_lyu, str_rnv, str_smm).
              (str_ebc$0 <: FALSE| NATURAL'str_qed)
                (UNION
                   (str_ynw, str_apj, str_mbf, str_nhn, str_jgd, str_nik,
                    str_iwp, str_gpp, str_jeo, str_jso, str_llc).
                 (#(str_ynk, str_wse, str_dsg, str_eiq, str_jhs, str_gyn).
                  (NATURAL > STRING)|
                  str_zij))))
        )
        (
          PI
            (str_cop, str_oez, str_rzl, str_zmk, str_wcc, str_ppc, str_jrq,
             str_fqy).
          (not(not(not(not(NATURAL1 = BOOL) & str_wer$0 : str_yno$0)))| {})
        )
        (
          [rec
             (str_amp: INTEGER,
              str_aex:
              [{ str_vng, str_yiu, str_hdg, str_qdn, str_kuo, str_dsv,
                 str_ldm, str_qtv, str_ymh, str_ifu
                 |
                 str_zdf$0 /= TRUE },
               str_ggw$0,
               str_zsc$0,
               str_zdw$0]),
           (INT(str_azh))]
            (iterate(str_tpt$0))
        )
        (
          %
            (str_nva, str_ysh, str_gzj, str_cld, str_jij, str_uoh, str_jcl,
             str_qzi, str_qov, str_fob).
          (str_zat$0 >= str_cyh|
           bool(not(str_fld /<<: NATURAL1)) \|/
           [BOOL,
            NAT,
            str_mvo,
            str_lrc$0,
            str_zld,
            MAXINT,
            str_ygx$0,
            rec(str_pzq: str_ibn$0, str_mxj: []'str_pzr)])
        )
        (
          { str_dvs, str_uqd
            |
            ((!(str_swg, str_puz, str_cma).(str_wko$0 = str_zix$0) <=>
              TRUE <= str_ifq$0) or
             str_ztz = str_bmt) <=>
            not(str_vsl >= INTEGER) }
        )
        (
          rec
            (str_drz:
             (str_utu \|/
              {rec
                 (str_yxv: {str_ylb$0},
                  str_fkd:
                  %
                    (str_sqx, str_qrt, str_yiq, str_njr, str_zah, str_vjb,
                     str_yqp, str_jgw, str_ddn, str_zzb, str_znz).
                  (str_nat$0 /: {}| MAXINT),
                  str_rqh: str_ekj,
                  str_rew: INTEGER)}))
        )
        (
          top
            (rec
               (str_xhf:
                ((str_vke(TRUE))
                 |->
                 struct(str_tgv: {str_fan$0, str_wcq$0, (str_xle$0 |-> {})}))))
        )
        (
          {str_qsu,
           FALSE,
           struct
             (str_ebz: str_sbg$0,
              str_nlt: str_ppf$0,
              str_lkw: str_zki$0,
              str_dsk: {},
              str_gvs: str_she,
              str_kiy: NAT,
              str_fed: INTEGER),
           TRUE,
           FALSE,
           struct
             (str_izj: 0,
              str_kou:
              rec(str_pcy: str_myy$0, str_xur: str_ost$0, str_ggy: str_erg$0),
              str_owb: str_woc,
              str_muv: str_ebc,
              str_upb: (max(str_ybl$0)),
              str_wqd: str_jxy,
              str_bxk: NATURAL1,
              str_rxu: str_den$0),
           (str_fru$0(str_cdv)),
           {str_aoz, str_jlk}}
        )
        (
          INTER(str_trp, str_mbj).
          (not(not(not(not(not(str_rja /<<: MAXINT)))))| str_rqf'str_cqo)
        )
      
      :=
      rev
        ({ str_oju, str_kye, str_hve, str_ohr
           |
           !(str_tuv, str_iyb, str_boz, str_ybx, str_hkn, str_jhn, str_dar).
           (str_imt$0 =
            %
              (str_ebm, str_pce, str_jtc, str_pmg, str_cah, str_phv, str_evt,
               str_tmi).
            (str_cmu$0 : str_lxi| []) <=>
            !
              (str_bhi, str_jwa, str_cba, str_xpd, str_woj, str_pao, str_dfu,
               str_xfx, str_mzl, str_sdu).
            (str_ifz$0 <<: str_fiw$0)) })
    END ||
    IF
      (!(str_lfi).
       (!
          (str_diw, str_ets, str_vei, str_lyg, str_zkr, str_iez, str_vpz,
           str_giz, str_loc).
        (NATURAL > str_yvk$0)) &
       NATURAL <<: NAT'str_zym) <=>
      #(str_iuu, str_ubw, str_rux, str_tbp, str_rhd).(str_ixy$0 < str_bpx$0)
    THEN
      str_ybf, str_ilx, str_jpn, str_wfq, str_lgi, str_hzx, str_iqu, str_fhv,
      str_elr :(
        not
          (#(str_qfz, str_bxz, str_gut, str_mgw, str_tjj, str_bpj).
           (FALSE /=
            bool
              (#(str_qvd, str_rgq, str_ozl, str_bgi, str_ltt).
               (not([] /= str_ouc)) &
               NAT1 : str_dgy$0)))
      )
    ELSIF
      !(str_zaw, str_wto).
      (not
         (str_wwk$0 /: str_uor or
          (str_afc /= NATURAL1 <=> NATURAL /: str_eov$0))) &
      #(str_kln).
      (#(str_dwe, str_xqp, str_gyd, str_bmr, str_zpr).(str_dbh$0 /<: []))
    THEN
      CHOICE
        str_lmg'str_wih
        :=
        str_wnh ..
        UNION
          (str_yum, str_oup, str_qal, str_hec, str_idz, str_uar, str_qkf,
           str_kgu).
        (BOOL >= str_uca$0|
         bool
           (bool
              (str_ahi$0 >=
               struct
                 (str_hcq: str_ueg$0,
                  str_usd: str_ugo$0,
                  str_npd: str_ujm,
                  str_wuf: MININT,
                  str_npn: str_fjo,
                  str_qjn: str_ehv$0,
                  str_ewo: str_xyg$0,
                  str_wdj: str_asd$0)) /=
            3))
      OR
        skip
      OR
        str_zpj 
          (
            { str_erl, str_pcz, str_myv, str_vri, str_hgd, str_wub, str_ljb,
              str_uzg, str_xjb, str_vfm
              |
              #(str_iuo, str_yxv).
              (!(str_rfv, str_gux, str_fhq, str_tqk).
               (not(#(str_tqi, str_kla).(str_llo /= str_fgl)) &
                FALSE /= str_tpz$0)) }
          )
          (
            rec
              (str_rgz:
               bool
                 (#(str_lhk, str_pqn).(MININT <<: NATURAL1 => TRUE <<: BOOL) <=>
                  #(str_mut, str_ucn, str_aow, str_csk, str_eqc).
                  (#(str_spl, str_ofv, str_fym, str_zgh, str_kij, str_otr).
                   ([] <: str_diw))))
          )
          (
            { str_mcb, str_lzm, str_eth
              |
              !
                (str_mzx, str_zwx, str_hfs, str_ykx, str_bbb, str_tgr,
                 str_zwj, str_sih, str_jts).
              (!(str_dre, str_xeq, str_giv, str_ove, str_dmd).
               (NATURAL1 <= str_xcf$0 <=>
                #(str_bgo, str_ayk).
                (#
                   (str_bek, str_luj, str_njq, str_cvp, str_tli, str_fqc,
                    str_zbp, str_xbd, str_dns).
                 (not(str_lhb = []))))) }
          )
          (
            { str_wne | MININT /= str_dls$0 }
              ({str_phn,
                FALSE,
                str_ghn,
                str_hxn,
                struct
                  (str_gqx: NATURAL1, str_mgx: str_usp, str_fri: str_fmq$0),
                str_lqb}
                 (str_hrk(rec(str_yee: str_lgt))))
          )
        
        :=
        (struct
           (str_vsv: str_njn,
            str_ufu: str_vco$0,
            str_ish: str_kyd,
            str_lld:
            struct
              (str_yuq: MININT,
               str_pux: 60,
               str_yiv: MININT,
               str_rwv: str_ceh,
               str_jhs: BOOL,
               str_rro: str_huu,
               str_fgg: {}),
            str_vqe: NAT,
            str_wst: NATURAL,
            str_egi:
            [str_mms$0,
             str_jdo,
             { str_ete, str_ekb, str_kjw, str_vsy, str_tkv | str_hom <<: TRUE }],
            str_yit: str_gmi$0) +->>
         { str_beu, str_opt, str_ihh, str_ncs, str_zvd, str_hze, str_vir,
           str_ora, str_adp, str_tol, str_jon
           |
           [] = str_jno })
        |->
        str_ixk$0
      END
    ELSIF
      not
        ((NATURAL <: str_ccf$0 or FALSE : str_pku$0) =>
         str_nam$0
         |->
         {str_bgn$0, str_asm, str_vlk, str_jcl$0, str_hut, FALSE} <=
         struct(str_xxk: NATURAL, str_sot: str_ywq$0, str_kqc: str_gka))
    THEN
      ASSERT
        ((str_flj /: str_sdm => str_sqb = str_yko) or NATURAL1 = str_diy$0) &
        !
          (str_lqw, str_mmk, str_gez, str_ypp, str_onr, str_rak, str_wzq,
           str_flu, str_evt).
        (NAT1 <: str_hyu$0 <=>
         !
           (str_yos, str_jfl, str_czw, str_vrl, str_kbp, str_qwz, str_mib,
            str_pko).
         (str_ufi > str_osd$0))
      THEN
        skip
      END
    ELSIF
      not
        (!
           (str_kov, str_bjo, str_dyj, str_xzx, str_pmm, str_rwg, str_lar,
            str_dyz, str_aog, str_zzb, str_huh).
         ((str_gnm /<: str_kir$0 & str_wpc$0 < str_zqa$0 & BOOL < str_hfc$0) =>
          not
            (#
               (str_gtt, str_rbi, str_vri, str_jle, str_ntg, str_lby,
                str_aig, str_vxv).
             (str_tzz < str_nev))))
    THEN
      str_coq, str_dqs, str_kqp, str_mdk, str_cma, str_tbf, str_nvm, str_ysl
      :=
      rec
        (str_knk:
         { str_nvs, str_opi, str_qhw, str_hqe, str_fni, str_ues, str_fie,
           str_qwk
           |
           !(str_awa, str_pga, str_biu, str_wro, str_acw, str_tnj).
           (#(str_kur, str_jyj, str_nkv, str_ula, str_hxa, str_ogk).
            (not
               (!
                  (str_gmw, str_zmg, str_xrz, str_egw, str_kty, str_dzz,
                   str_jja, str_fdv).
                (#
                   (str_qdo, str_ahm, str_mjj, str_vtq, str_nrc, str_pbp,
                    str_riw, str_zsl, str_azt, str_bwg, str_srd).
                 (str_zsn /= NATURAL))))) },
         str_mvz: str_urf)
    ELSIF
      [struct
         (str_kdn: str_lgm,
          str_fbz: str_rql$0,
          str_bif: str_ids,
          str_hoy: str_jad$0,
          str_pis: STRING,
          str_tof: NAT1,
          str_gmi: str_rzt,
          str_rar: str_tke$0),
       str_wek$0,
       (str_vlo$0 , str_oiz$0),
       BOOL,
       str_hse$0,
       { str_nda, str_hfz, str_aud, str_bxy | str_nhz$0 /<<: str_bbm },
       [],
       str_gub] /<:
      str_lsg =>
      #
        (str_ihi, str_tuy, str_sdy, str_uoz, str_urw, str_sst, str_htw,
         str_hfg, str_tdl).
      (str_ftq <= str_ytd$0)
    THEN
      str_cxs, str_nvb, str_djx, str_tcw, str_thk, str_vhx
      ::
      bool
        ({}(bool(str_qdb /<<: str_chg$0)) >=
         { str_hih, str_uor, str_poh, str_pbr
           |
           not(str_xlt$0 /<: str_tqx <=> str_oqu$0 <<: {}) })
    ELSIF
      ((INT /<: 9 <=>
        not
          (!
             (str_onb, str_gsn, str_zsq, str_uoz, str_frt, str_dld, str_eos,
              str_ekw).
           (str_rac$0 = str_mld$0))) or
       str_zjt /= str_icz$0) <=>
      str_tdr$0 : [str_jjx$0, str_vjh, str_vsg$0, str_sny, STRING]
    THEN
      CASE
        struct
          (str_qgz: str_vph$0,
           str_kyc: str_nez,
           str_lwz: str_mbv$0,
           str_xgc:
           struct
             (str_adg: MININT,
              str_zco: str_gef,
              str_sjp: str_zhm,
              str_keg:
              rec
                (str_gxe: MAXINT,
                 str_dgd: str_soa,
                 str_vqc: str_tnw$0,
                 str_efy: str_omd$0,
                 str_amc: BOOL),
              str_cki: NATURAL1,
              str_uma: str_fxf),
           str_bes: (rel(str_ngy'str_ctq)),
           str_sxx:
           struct
             (str_avc: {},
              str_fzq: str_lxx$0,
              str_bvc: str_gmz,
              str_joi: NATURAL1,
              str_ktz: str_men$0),
           str_dmn:
           [str_gtq, str_dme, str_hnf$0, str_vzv, FALSE, NAT1, str_mbw$0])
        OF
        EITHER
          rec
            (str_aoz: str_uue$0,
             str_ozq:
             ((top(str_bvw$0))
              |->
              rec
                (str_fdi: str_yvl$0,
                 str_cdi: str_ttm$0,
                 str_gwq: str_pwy,
                 str_jcp: str_mid,
                 str_wmn: str_hcs$0,
                 str_pjg: str_znh$0,
                 str_dak: str_lnl,
                 str_jss: str_ngp$0)),
             str_jnt:
             ({["str_azt", str_rzx$0, str_hwa$0, str_ocx$0, str_uri, INTEGER,
                str_wdo],
               str_bqt$0}
              ,
              INTEGER))
        THEN
          ASSERT
            not
              ({INT, str_uwl, NATURAL1, str_msj, str_bbh$0, {}, str_fpw$0} <<:
               NATURAL1) <=>
            !(str_nzv).(str_uie |-> str_ejb$0 : str_noz$0)
          THEN
            str_gwz, str_swf, str_ubl, str_cod, str_nnt, str_ksz, str_tcj,
            str_wdv, str_zag, str_pda, str_bjj :(
              not
                (not
                   (!(str_zru).
                    (not
                       (#(str_vyw, str_twf, str_dqs, str_kop, str_ebb).
                        (not(str_tgx /= str_vwm$0))))))
            )
          END
        OR
          [FALSE,
           rec
             (str_ylp: str_gqp$0,
              str_bmq: str_agk,
              str_gph: INT,
              str_map: str_obt,
              str_tlx: str_alx,
              str_sau: STRING),
           "str_zaq",
           str_cim,
           str_gea$0,
           BOOL]
            (str_mdp
             ,
             (POW
                (UNION
                   (str_joe, str_mcz, str_nis, str_yhg, str_eob, str_vxl,
                    str_gxt, str_zkr, str_eep, str_czt).
                 (!(str_tek, str_fky, str_hxf, str_hah, str_rya).
                  (str_nkp$0 >= 7)|
                  INT))))
        THEN
          str_wqs
            (rec
               (str_uuj:
                bool
                  (bool(str_cjd <<: str_pja$0)(str_yvf) /: str_cwg$0(str_gwa)),
                str_tvb: (infix(str_txg)),
                str_stq: str_zxr),
             struct
               (str_tmd: NAT'str_xjs,
                str_rzp:
                ({ str_mjr, str_yxf, str_jvm, str_wvh, str_zjh, str_tfd,
                   str_eqf, str_yup, str_myq
                   |
                   str_cxv >= str_psw$0 & not(str_ysk /<: str_eoe$0) } <->
                 (min(str_lpu$0))),
                str_caw: STRING),
             (%
                (str_xtp, str_yqu, str_rxs, str_nec, str_wsq, str_toc, str_vmq).
              (NAT /<: str_alw$0 or not(str_gdt$0 <<: MININT)|
               INTER(str_gbl, str_rck, str_ail, str_ses, str_tgf).
               (str_hvu$0 > {} or 16 < str_tlc$0| str_key))
                (bool(str_jum$0 /= str_vup))),
             rec
               (str_fds: str_njw$0,
                str_hkw: NATURAL,
                str_msl: bool(MAXINT <<: NAT or str_azp$0 <= {}),
                str_ttt:
                { str_ott, str_tuw
                  |
                  "str_ssz" /=
                  { str_pvk, str_yvl, str_cak, str_hex, str_kkw, str_nbe,
                    str_pug, str_enf, str_ycd, str_pza, str_way
                    |
                    str_zpn /: str_znf$0 } },
                str_oem: (str_cwo <<| str_tvd)),
             { str_rzj, str_tua, str_cbc, str_mdr, str_omk, str_okj, str_gsl,
               str_pmk, str_xux
               |
               not
                 (struct(str_gla: str_yer$0, str_qro: str_tdi$0) -->
                  str_ecm$0 /<:
                  MAXINT'str_ylx or
                  STRING /: str_pyp) },
             { str_pxm, str_fqw, str_may, str_irk, str_ggu, str_cur, str_gol
               |
               not
                 (!
                    (str_wlt, str_uvc, str_lrk, str_yuv, str_ijq, str_loh,
                     str_yma, str_eij, str_phi, str_miz).
                  (not
                     (#(str_xry, str_ksp, str_azt, str_njz, str_cjs).
                      (#(str_ztx, str_jdt, str_oug, str_zzy).
                       (str_hbe$0 /= str_nse$0))))) },
             { str_zkb, str_kox, str_pgd, str_rhj, str_hef, str_nhi, str_rft,
               str_wtu, str_xfx
               |
               []'str_ubn < str_zoc <=> postfix(INTEGER) <= NATURAL1'str_pqf },
             SIGMA(str_kgn, str_pgd, str_lbt).
             (!(str_ysq).
              (not
                 (!
                    (str_niu, str_ufa, str_lyc, str_aqr, str_mua, str_gdf,
                     str_psz, str_mxj).
                  (not(str_yzf >= {}))))|
              UNION(str_ker, str_nao). (str_xrd$0 /<<: INT| NAT)),
             (UNION
                (str_wel, str_asy, str_iqc, str_dqh, str_ulc, str_grp,
                 str_ebv, str_brn, str_pwb, str_ghp).
              (str_rzl$0 <= NATURAL1|
               bool
                 (#
                    (str_uhf, str_cqo, str_qyz, str_mqb, str_jcr, str_sgb,
                     str_zux, str_xpu).
                  (NAT >= str_plz or str_yjy$0 <: {}))) <+
              {BOOL, str_xgv, NATURAL, str_cur$0, "str_gko", str_glk,
               str_ofu, MININT})
               'str_pdt)
        ELSE
          str_npu, str_zds, str_prc, str_xcg
          :=
          rec
            (str_gdb: INT,
             str_lmy:
             ({ str_xgb, str_ojz, str_xfo | NAT1 = MININT } |-> str_nai)
               'str_adp,
             str_rxy: (BOOL +-> {}),
             str_idt: str_xko$0)
            'str_vln
            'str_lqi
        END
      END
    ELSIF
      not
        (#(str_cpl, str_mdi, str_xod, str_hth, str_txn, str_voq, str_oih).
         (#
            (str_eyw, str_rxa, str_vez, str_rbs, str_qpv, str_hfe, str_fdk,
             str_iwa, str_hlu).
          (rec
             (str_qnf: str_iwh,
              str_lxl: str_ztw,
              str_igb:
              rec
                (str_teq: str_oyu,
                 str_zko: MININT,
                 str_unt: NATURAL,
                 str_oql: [],
                 str_mpc: str_qrf$0,
                 str_saq: INTEGER),
              str_xbc: NATURAL,
              str_ejb: str_zai,
              str_tqi: str_yuz$0,
              str_eiw: str_vwa,
              str_cvz: str_knb$0) =
           { str_ayl, str_gta, str_jms, str_jhf, str_ojr, str_qpm, str_nii,
             str_uri
             |
             str_pae$0 : str_uwx })))
    THEN
      str_sss, str_zsj, str_zgx, str_dzz, str_acc, str_hlw :(
        not
          (!(str_rcw, str_pwu, str_ldg, str_lgd).
           (#
              (str_nyu, str_rcc, str_uge, str_ryu, str_ucr, str_yyb, str_egn,
               str_kom, str_qlm).
            (not(str_vgg$0 >= str_ggv$0) <=>
             !
               (str_vvg, str_ogz, str_ofv, str_euh, str_vzj, str_owd,
                str_azu, str_ddn, str_zxu, str_vfr, str_djj).
             (!(str_hna).(str_too$0 : str_mro$0)))))
      )
    END
  END;

  str_trh, str_aje, str_mwf, str_hik, str_mny, str_jnh, str_vrf, str_koq,
  str_wdh, str_lok
  <--
  str_bkn
  =
  VAR
    str_ttc
  IN
    IF
      not
        (!(str_aqe, str_yau).
         (closure
            (last
               ({ str_lnr, str_cnd, str_svg, str_ckl, str_efg, str_mmu,
                  str_fuz, str_shb, str_spe
                  |
                  FALSE /= MAXINT }
                  'str_ajs)) <:
          str_ljj))
    THEN
      CHOICE
        str_jza'str_bti
        :=
        bool
          (#(str_izr, str_bqr, str_kie, str_wmf).
           (!(str_dcd, str_pvi, str_kym, str_bqi, str_uia).
            (#(str_wtd).
             (str_aoh /<:
              struct
                (str_dgy: {STRING, str_mov, str_vab},
                 str_zmt: str_vgf,
                 str_xro: str_tvi$0,
                 str_iik: str_oat,
                 str_xwc: str_kyd$0)))))
      OR
        str_qdv'str_niy
        :=
        bool
          (!(str_woz).
           (str_hyi$0 /:
            str_bck$0
            ,
            ((FIN([str_qdm$0, INTEGER, str_smo$0, str_xjp, str_wpi$0]))
             |->
             str_sxe)))
      OR
        str_mhk, str_xsl, str_dab, str_ubt, str_hwv, str_pcd, str_elh,
        str_xwe, str_lvw, str_dlo
        ::
        bool
          (!
             (str_mlg, str_nvu, str_sdd, str_kja, str_uxa, str_wkr, str_jar,
              str_hus, str_eur, str_akc).
           (bool(str_ivn /<<: str_zav)(bool(INT /= NAT)) >=
            str_kcw , str_vjs$0)) ;
        str_nan, str_cso, str_uec, str_exd, str_iau, str_zje, str_lrp
        <--
        str_ksr
          (SIGMA
             (str_cfg, str_azg, str_eud, str_cqo, str_wbf, str_siz, str_soo,
              str_mhc, str_mbb, str_riw, str_qlr).
           (str_tjj <= str_xmn$0|
            {SIGMA(str_aro, str_xsq, str_flu, str_kmv).
             (!(str_mmd, str_kkd, str_luw, str_cxv, str_vnq, str_gxk).
              (str_mak /: INTEGER)|
              FIN1
                (struct
                   (str_sen: str_luz$0,
                    str_vgm: str_whx,
                    str_spj: str_xdq,
                    str_toa: str_wdh$0,
                    str_wmf: str_rpm,
                    str_pls: FALSE)))
               'str_uvt}),
           (PI
              (str_ord, str_biq, str_wqk, str_egp, str_uei, str_qfk, str_sof,
               str_dls, str_gmq).
            (not(62 <<: [])| ran(str_oil$0))
              (rec
                 (str_gco: str_zfm,
                  str_owz: str_bks$0,
                  str_xhk: NAT1,
                  str_hgg: {INT}))),
           { str_vvv
             |
             !
               (str_vhs, str_mxe, str_pfo, str_wqk, str_cna, str_rnn,
                str_mvq, str_aat, str_smw).
             (not
                ((INTEGER /: str_bdk$0 => str_rys$0 : str_cji$0) <=>
                 #(str_vpx).(!(str_jfd, str_gsi).(str_iad$0 > str_jro)))) },
           PI
             (str_kxc, str_qzs, str_uqt, str_vxg, str_vye, str_ovt, str_trt,
              str_mpe, str_ges, str_rcl, str_omp).
           (#
              (str_lwh, str_xun, str_jww, str_lxy, str_yen, str_mqo, str_ypf,
               str_awb, str_adl, str_inf).
            (str_rls$0 > str_hpx$0)|
            {str_rnu'str_atb,
             struct
               (str_pmx: bool(str_bkp$0 <= str_nrn$0),
                str_spc: str_jiz$0,
                str_dfy: MININT,
                str_plo: NAT,
                str_xmt: str_uha,
                str_moh: str_pty,
                str_kzg: NAT,
                str_nzj: {str_oir$0, str_jvw$0, str_ffi})}),
           [{ str_ylf, str_vzt, str_cvu, str_fgx, str_ymy, str_xrf, str_abg
              |
              #(str_tvf, str_ofi).
              (not
                 (#
                    (str_lok, str_jfi, str_qcq, str_qob, str_xxq, str_vqd,
                     str_mgp).
                  (not(not(str_lmi <<: str_vmy$0))))) }],
           { str_ktz, str_zcw, str_gkg, str_oom, str_tfo
             |
             not
               (str_iil$0 = {} <=>
                #
                  (str_oxt, str_fur, str_ybq, str_iip, str_zqz, str_ywv,
                   str_lyd).
                (str_dti$0 <: str_nhd$0 or
                 #(str_pjm, str_zno).(str_lgn < str_bya))) }
             'str_erp,
           (bool(str_pej$0 : str_gzy)
              ({ str_bei | not(MAXINT : BOOL) } >->> bool(not(str_gsg <: {})))),
           bool
             (#
                (str_icy, str_xeg, str_qer, str_tac, str_qli, str_vsh,
                 str_cvv, str_wkb, str_xie, str_ntn, str_oii).
              (str_ajb$0 = str_yam$0 mod str_igj$0) or
              (NAT1 > {} => NAT1 > str_ssw$0)),
           (bool(str_mpl$0 = INTEGER)
            ,
            {str_tdp$0,
             str_thr,
             NAT1,
             INTEGER,
             rec
               (str_dsh: str_nif$0,
                str_qal: MININT,
                str_mzd:
                rec
                  (str_ydn: str_qhb,
                   str_cmd: str_orh,
                   str_jjk:
                   struct
                     (str_nst: BOOL,
                      str_few: str_inu$0,
                      str_wbg: str_hcb$0,
                      str_jyd: NAT),
                   str_crt: str_vnn$0,
                   str_ejq: NAT,
                   str_nds: str_exf),
                str_knx: INT,
                str_lai: str_okv),
             { str_wbb, str_yrs, str_kwb, str_qun, str_cid, str_iua, str_sgw
               |
               str_bhy /<<: str_qmy },
             str_nig$0,
             str_gpw$0}),
           [str_kmy$0,
            str_cwb$0,
            str_pyi$0,
            MAXINT,
            { str_moe, str_vby, str_htx, str_vpz, str_xkb, str_zmj, str_uar,
              str_pqi, str_hqt, str_jzg
              |
              INT <: INTEGER },
            ((str_eoz , str_ofu$0)
             |->
             {str_yyk,
              [str_ukn$0,
               SIGMA
                 (str_kjr, str_rwe, str_fef, str_ica, str_zbu, str_kjb,
                  str_uzj, str_udd, str_ech, str_lui, str_rhl).
               ([] <<: str_acf| INT)]}),
            str_fpb,
            MININT])
      END
    ELSIF
      #(str_vdm, str_gcc, str_zpv, str_pam, str_jws).(str_ziw$0 <<: str_tbe) or
      not
        (#
           (str_hlo, str_unp, str_gts, str_qwr, str_xeo, str_nsi, str_tau,
            str_oue, str_isn, str_ldc, str_nim).
         (#(str_tmj, str_dft, str_wwy, str_pee, str_rpq).
          (NAT /= dom(str_lvv))))
    THEN
      ANY
        str_oki, str_pcp, str_lqx, str_ggb, str_qym
      WHERE
        not
          (str_wtj$0 :
           str_dmt$0'str_ohz
             ({SIGMA
                 (str_baf, str_oqx, str_fvz, str_kgj, str_eqe, str_gwd,
                  str_iel, str_jsj, str_nec).
               (str_yzt$0 < str_ovm| FALSE),
               str_hes$0,
               str_klh,
               str_chw,
               (str_czw$0(NATURAL1)),
               str_zpe,
               str_dwl}))
      THEN
        VAR
          str_wbt, str_vkb, str_tko, str_dof, str_kfh
        IN
          str_xfw 
            (
              { str_xxe, str_ysn, str_oyx, str_jso, str_cuw, str_xub,
                str_wxi, str_vyb
                |
                !
                  (str_zai, str_ojp, str_ebg, str_ddx, str_lkv, str_ips,
                   str_que, str_dec, str_whm, str_bbk).
                (!(str_muj, str_lib).
                 (#
                    (str_yfo, str_gsf, str_dlq, str_cvx, str_nkc, str_als,
                     str_bwu).
                  (#(str_taz).
                   (!
                      (str_bbv, str_mza, str_fph, str_gjt, str_jag, str_gtt,
                       str_jrp, str_ept).
                    (!
                       (str_plu, str_fqh, str_aih, str_udf, str_iyx, str_uwl,
                        str_wwn, str_ckp, str_ojz, str_qvj, str_rrq).
                     (str_jbv$0 > str_emh)))))) }
            )
            (
              {bool(#(str_mmv, str_ndb, str_koy, str_vfi).(MININT /<: NAT1)),
               bool(!(str_hqd, str_eyi).(not(BOOL <<: str_wha))),
               str_zze$0,
               str_xha$0}
              |->
              str_myc
            )
            (
              (str_ufe , str_tuq)'str_nnh
              |->
              {struct
                 (str_yzc: str_bjk$0,
                  str_kyn: NAT,
                  str_nph: (arity([str_wcw, str_zld])),
                  str_jdz: str_lad$0,
                  str_txh: str_xxn,
                  str_fhp: MININT)}
            )
            (
              rec
                (str_nry: str_tpv$0,
                 str_ntc:
                 {(fnc
                     ({ str_lbw, str_atf, str_gua | str_duq$0 /: str_euv$0 }
                      |->
                      str_bvh)),
                  str_ytx$0,
                  INT},
                 str_tyw: ({}(str_jrl$0))'str_pod)
            )
          
          :=
          { str_cik, str_tai, str_opt, str_bdu, str_nno
            |
            #
              (str_pvb, str_wvj, str_wpq, str_kro, str_xip, str_hhu, str_dje,
               str_fsf).
            (!(str_gay, str_gdq).(str_oih > str_axn$0)) } <|
          ((inter(FALSE)) <-> rec(str_rpb: str_ojt$0, str_vkj: str_uyw))
        END
      END
    ELSIF
      str_cpi : MAXINT &
      {str_sjd$0, (str_wdx$0(str_xue))}'str_rif >=
      [TRUE,
       { str_inc, str_pbu, str_eih, str_lyb, str_qsh, str_lcn, str_bae,
         str_fvu, str_vyw
         |
         str_qfm$0 > NAT1 },
       9,
       str_obq$0]
    THEN
      str_eni, str_lui, str_kqv, str_mkc, str_ghh, str_bsb, str_fui, str_bjd,
      str_lvk, str_gsb, str_wom
      :=
      struct
        (str_zop:
         struct
           (str_aoh: TRUE,
            str_xvi: str_fcl,
            str_hwr: INT,
            str_tln: str_fbh,
            str_exx: str_twa,
            str_tnk: NAT1,
            str_ouv: MININT),
         str_gfo: str_eze,
         str_iym: str_pzd$0,
         str_pof: str_xba,
         str_xjv: str_ocz,
         str_aaq: [str_mvl$0, MININT, BOOL, str_oua, str_wtz, 62])
      |->
      (str_lzp$0'str_eeu'str_osw - str_jtt)
    ELSIF
      not
        ((not(not(str_rtm$0 < str_sbk$0)) =>
          !(str_yyr, str_hzn, str_jfs, str_jcc, str_vqy, str_ymp, str_kfq).
          (#
             (str_vat, str_uzx, str_avs, str_thw, str_jpj, str_mym, str_khb,
              str_lvs, str_qcz, str_dlv, str_hur).
           (str_xyi : str_wip$0))) <=>
         str_vdj < str_vbd)
    THEN
      ASSERT
        {{str_ask,
          (str_ose$0 <<| str_rfs$0),
          { str_cnf, str_xod, str_tye, str_ygl, str_hlk, str_cni, str_mfe,
            str_mne, str_sxb, str_nis, str_teg
            |
            str_llw$0 <= str_kyr$0 }}} /<<:
        [str_pzu, str_tjc, INTEGER, str_vwa, str_hpx, str_qsd] , str_wta$0
      THEN
        str_sgu 
          (
            ([str_xbg$0,
              str_fmm$0,
              MININT,
              ((str_cra |-> str_wad$0) |-> str_cpa),
              str_xzg]
               ((father([]))(NAT1)))
              'str_dxg
          )
          (
            struct
              (str_cox: str_sdn,
               str_ymu: str_ozo,
               str_tch: str_ief,
               str_pih:
               rec
                 (str_puf: PI(str_oep). (str_kqr$0 < NAT1| FALSE),
                  str_jbs:
                  (([]'str_art || (MAXINT |-> bool(NATURAL /= str_rog)))),
                  str_vmf: TRUE))
          )
          (
            bool
              (#(str_kat).
               (not(str_dsc \|/ str_dur$0 : str_viu) <=>
                !(str_ytv, str_nlb, str_kjh, str_xuw, str_xgi, str_zfx).
                (str_uce /<<: TRUE)))
          )
          (
            btree
              ((mirror
                  ({ str_jga, str_kyi, str_qlm, str_mxf, str_mzj, str_bdj,
                     str_fno, str_uxr, str_cmo, str_odi, str_zpy
                     |
                     not({} /: str_eof$0) }))
                 (struct
                    (str_qwo: NAT1,
                     str_brj: struct(str_uxq: str_txu$0, str_qkl: str_xrk$0),
                     str_hgz: NATURAL,
                     str_dxx: str_aqj,
                     str_rsd: INTEGER,
                     str_met: [])))
          )
          (
            struct
              (str_jyy:
               bool
                 (!
                    (str_yzu, str_lff, str_avw, str_htx, str_guc, str_nef,
                     str_fsn, str_ojd, str_lub, str_hkb, str_ect).
                  (str_klv$0 <: MAXINT)),
               str_iju:
               rec
                 (str_qfw: NAT1,
                  str_fri: str_apa,
                  str_ekj: str_lsr$0,
                  str_ktw: [],
                  str_gma: str_tno$0,
                  str_chf:
                  SIGMA
                    (str_azd, str_sft, str_rmc, str_ygm, str_rje, str_hxm,
                     str_ane).
                  (str_dlt /: str_rcr| BOOL)),
               str_ynt: (str_oja <-> (str_agx$0(NATURAL))),
               str_sob: INT)
          )
          (
            bool
              (not
                 (#(str_bym).
                  (not
                     (#(str_jge, str_zji, str_gmc, str_fts).
                      (#
                         (str_dxd, str_qtr, str_xqp, str_oaz, str_als,
                          str_enl, str_fva, str_ark).
                       (str_krd /<: str_itq))))))
          )
        
        :=
        { str_hag, str_wsp, str_uzq, str_pgk, str_won, str_aey, str_hgs,
          str_hko
          |
          !
            (str_dfs, str_faz, str_dzn, str_yaj, str_xeh, str_bgm, str_rcy,
             str_jxt).
          (!
             (str_rml, str_drz, str_czl, str_omw, str_nus, str_vbr, str_eyo,
              str_dpz, str_qwz, str_dkk).
           (!(str_agf, str_ouo, str_udw).(str_piu /<: str_pyi) =>
            !(str_ixu, str_zqy, str_lbr, str_bfa, str_dyj, str_pfh).
            (str_jiv < str_gen & [] = str_pln$0))) }
      END
    END
  END;

  str_wwx, str_ckq, str_obz, str_umg, str_tfd
  <--
  str_pzo (str_pim, str_kyo, str_vji, str_ehm, str_vup, str_net)
  =
  BEGIN
    SELECT
      bool
        (not(!(str_ovo, str_sbf, str_eow, str_fif, str_enj).(NAT /= str_nno))) =
      [str_zjl, (str_wdg$0 |-> str_vyk$0), FALSE](str_gsz$0)
    THEN
      SELECT
        #(str_ieh, str_zok, str_pwx, str_qeg, str_rou, str_vjv, str_nmp).
        (str_rsp = str_pdz or
         not(not(not(str_rbv$0 : str_wjr$0)) & FALSE > 4283))
      THEN
        str_tlf, str_sqm, str_yey, str_xzu, str_fdc
        :=
        [str_mzv$0, BOOL, str_opc$0, str_vsz, str_inv, TRUE, str_can$0,
         str_suj]
          (rec
             (str_rpb: NATURAL1,
              str_bml: INTEGER,
              str_jrw: str_ust,
              str_rzb: (conc((str_ybb(str_iia$0)) |-> str_wuj$0)),
              str_drz: str_wvk$0,
              str_hti: str_ngj$0,
              str_puq: (str_ujy , str_yme$0),
              str_uea: INTEGER))
      WHEN
        not(str_ktv < MININT) & not(#(str_rsw, str_qvb).(not(INT : NATURAL)))
      THEN
        str_axp'str_rer
        :=
        [bool
           (#
              (str_wtg, str_knt, str_ehb, str_pef, str_fmj, str_gjz, str_mmm,
               str_tqu, str_wzu).
            (str_jnw /: MAXINT)),
         str_ziy$0,
         bool(not({} /<<: str_lhj$0 => NATURAL1 : str_gbj)),
         STRING]
      WHEN
        (rec
           (str_cxl: str_jzh,
            str_mls: str_ldv$0,
            str_hff: str_nha,
            str_ekz: {},
            str_okq: str_lru,
            str_tyb: NAT1,
            str_dyc: str_pqx$0,
            str_ket: str_fzu$0) :
         str_wsb &
         str_jbv /<: str_rei$0) or
        not(not(#(str_gxi, str_azk, str_zig, str_bqt).(str_scz <: INT)))
      THEN
        str_njp, str_bgr, str_ihf, str_adk
        ::
        {{}, str_niu$0, str_enx}'str_tjy
          ({PI(str_ixb, str_sto). (not(STRING > str_kew$0)| NAT1),
            bool(MAXINT /= INT)})
      WHEN
        rec
          (str_wvf: INTEGER,
           str_dhp: NATURAL1,
           str_xjz: str_tpw,
           str_cgj: [(9 |-> str_dsy$0), []],
           str_jab: str_ocn$0,
           str_lwy: BOOL,
           str_cbv: INT) /=
        bool({ str_cti | str_svx$0 <: str_toz$0 } < TRUE)
      THEN
        str_aqx, str_dsj, str_ond, str_iok, str_dhw, str_rrx, str_tik,
        str_obd, str_cqb, str_cxx, str_alq :(
          !(str_tqh, str_mmi, str_zuf, str_zgt, str_pir, str_uky, str_ohe).
          (FALSE < str_let =>
           #(str_vaw, str_iip, str_ovn, str_dop, str_mqd).
           (#
              (str_prh, str_txr, str_bfy, str_dsl, str_par, str_ild, str_tae,
               str_mow, str_htt, str_zce).
            (#(str_cqv, str_ebm, str_ekx, str_xdo, str_cpq, str_sdf, str_mqj).
             (!(str_dat).(str_gsp$0 <<: str_tsc$0 or str_cke$0 : {})))))
        )
      END
    WHEN
      str_tok$0 > str_bic =>
      INT(str_ewm) >=
      { str_izb, str_rki, str_epk, str_frm, str_lae, str_nbt, str_kww,
        str_cwr, str_cgk, str_nrn
        |
        #(str_qhi).(str_bbz$0 >= STRING) }
        'str_mzk
    THEN
      str_zeu'str_zgs
      :=
      INTER(str_beg, str_zfu, str_cbk, str_bjd, str_oad, str_buw, str_mhb).
      (#(str_cgv, str_ilm, str_kgn, str_cca, str_eha, str_urt).
       (!(str_feo, str_wtg, str_yre, str_syd).(not(str_dez$0 <= str_pnp)))|
       str_ofk$0
       |->
       [NATURAL,
        str_mpj,
        str_ghk$0,
        { str_imc | INT <<: FALSE },
        str_qeo$0,
        str_oza$0,
        str_how$0,
        STRING])
    WHEN
      #
        (str_zlc, str_dwm, str_pbk, str_cwo, str_cyb, str_dkg, str_idb,
         str_zhy, str_awg, str_qya).
      (!(str_evc, str_xnr, str_vja, str_arx, str_kru, str_nnl).
       (!(str_col, str_ukc).
        (!
           (str_eso, str_bly, str_rlw, str_swp, str_xha, str_vyd, str_ver,
            str_zwz, str_xty).
         (str_hlt <<: str_ium))) or
       (!(str_qex).(str_gtr = str_rwt) <=> str_oty$0 = str_kik$0))
    THEN
      ASSERT
        !
          (str_hpp, str_hmi, str_aky, str_sgn, str_ucj, str_yjp, str_cbp,
           str_rny, str_hxc).
        (str_hhm < str_pqs$0 => not(str_kjz : str_dke)) <=>
        not
          (!
             (str_imu, str_ksv, str_dsr, str_hga, str_jiz, str_pzq, str_ywu,
              str_hhb, str_ofg, str_mes).
           (str_rpw$0 > str_byz$0))
      THEN
        str_hqt 
          (
            rec
              (str_fro:
               INTER(str_vek, str_zjt, str_leh, str_vst).
               ("str_rbj" /<<: str_laa$0| 6 |-> (rev(str_feb$0))),
               str_prp:
               rec
                 (str_eux: NAT1,
                  str_stu: str_znz,
                  str_mnw: str_qwu,
                  str_itk: str_smk,
                  str_mck: MAXINT,
                  str_nju:
                  {{}, str_fjq$0, str_oxq$0, str_mqr, str_pdn, MAXINT,
                   str_sod, TRUE},
                  str_hew: (str_vji >< str_oqf)))
          )
          (
            SIGMA(str_lmr, str_fmh, str_yxl, str_wkz, str_tho, str_eya).
            (MININT <<: str_dsd|
             struct
               (str_jgh:
                { str_vzw, str_muq, str_gwu, str_fey, str_izs, str_jxc
                  |
                  INT <<: STRING },
                str_czl: NAT1,
                str_ruc: [],
                str_eng: str_tep,
                str_tmj:
                {str_vgf,
                 [str_rey, MININT, bool(str_xok$0 /= FALSE), {}, str_awm$0],
                 str_dbe,
                 NATURAL1},
                str_cnj: str_hsc$0,
                str_wma: str_zvb,
                str_jbp: [str_ouy, str_tvr$0, NAT1, str_pcr$0]))
          )
          (
            struct
              (str_ckc:
               { str_igc, str_ucb, str_rrq, str_fpk, str_edf, str_ufp,
                 str_juj
                 |
                 str_tnm /: NAT },
               str_bgg: {str_yvo$0},
               str_pcp: str_yju,
               str_jyo: {str_dfl},
               str_wpn:
               {str_cjl$0,
                str_mqb$0,
                %
                  (str_skh, str_cai, str_qup, str_dhl, str_xyd, str_wug,
                   str_isx, str_zwd, str_ewk).
                (NATURAL1 /: "str_jig"| INTEGER)},
               str_ovg:
               %
                 (str_ack, str_hlr, str_nha, str_qmb, str_rcs, str_jts,
                  str_uaz, str_uqx).
               ({} <: INT| str_udz),
               str_dtk: str_mnh)
          )
          (
            bool
              (not
                 (#(str_lxl, str_oxg, str_qjc).
                  (INT <
                   INTER(str_hgb, str_mnu, str_nhd, str_ezt, str_wvr).
                   (not
                      (#(str_zch, str_bpf, str_bdp, str_ljz).
                       (str_uob /= str_gbc))|
                    959))))
          )
          (
            str_evz$0 +
            PI(str_qzz, str_ise, str_xfs, str_gyh, str_eug).
            (!(str_tuo).(str_dns <= str_kdw$0)|
             struct
               (str_nin: ((str_fcn(5)) , str_pcj),
                str_omy: NAT,
                str_myd: FALSE,
                str_sht: str_zii,
                str_biy: str_bqh$0,
                str_dmf: MININT))
              'str_dsv
          )
          (
            struct
              (str_qul: str_sjm$0,
               str_idq: str_aiq$0'str_klo,
               str_noi: NATURAL1,
               str_fbs:
               UNION(str_una).
               (str_wkc$0 = str_kkq$0|
                PI(str_nwd, str_fon, str_bhh, str_tkt).
                (INTEGER >= MAXINT| INT)
                ,
                struct
                  (str_zvq: str_nug$0,
                   str_xzy:
                   {str_hfo$0, str_oep, str_zdm, [], NATURAL, str_xfw},
                   str_zts: FALSE,
                   str_nqn: str_com$0,
                   str_law: [],
                   str_xhl: str_exg)),
               str_kee: str_zxo$0)
          )
          (
            struct
              (str_sro: str_rfg$0,
               str_gek: str_hqh,
               str_rsa:
               { str_ufk, str_zhf, str_kcw, str_yzh
                 |
                 #(str_haf, str_mps, str_ahj, str_zte, str_bfo).
                 (!
                    (str_jiv, str_pst, str_vnh, str_cus, str_eyk, str_cks,
                     str_zxh).
                  (str_opx <: str_fki)) },
               str_teq:
               {str_ioo,
                str_xeo$0,
                (rec
                   (str_svd: str_mpt,
                    str_yfx: str_ioc$0,
                    str_ofv: NAT1,
                    str_pce: str_and,
                    str_fcc: MININT,
                    str_hpe: str_hrb,
                    str_sxm: {})
                 |->
                 str_lgo)},
               str_dbs: INT,
               str_gsk: str_uuh,
               str_vxu: str_lak,
               str_uew: str_imz$0)
          )
          (
            {{str_vuq$0'str_dps,
              (str_bwt$0 , str_lwo),
              str_ama,
              str_koo,
              str_hqk$0,
              {str_rcj,
               str_ste,
               str_zjt$0,
               str_ksd$0,
               str_vnz$0,
               str_twq,
               %(str_lra, str_szs). ([] : str_ycm$0| INTEGER),
               bool(str_aql <= str_qxt)}}}
          )
        
        :=
        rec
          (str_nkc: str_wzs$0,
           str_jdt:
           rec
             (str_dze: str_jmq,
              str_zen: str_edq$0,
              str_cgu: str_vck$0,
              str_qml: NAT,
              str_nnn:
              ({str_fgw$0, str_yho$0, str_udi$0}
               ,
               [str_rcb$0, str_qxg, str_mts, str_wdn, str_rej, str_xui$0,
                str_viz])),
           str_rjq:
           rec
             (str_lnt: STRING'str_bam,
              str_xob: str_ehq,
              str_uzt: str_hcb,
              str_ihc: {},
              str_jro: str_qey$0),
           str_rfx: str_rwj$0,
           str_hea: BOOL) ||
        str_oyg, str_tab :(
          not
            (!(str_tpr, str_iyj, str_awl, str_ang, str_maq, str_xok).
             (str_hhu$0
                ([str_szw,
                  str_nua$0,
                  str_oqu,
                  str_uex,
                  str_jwu$0,
                  [],
                  MAXINT,
                  {MAXINT, NAT1, str_fcm, str_nxb$0}]) >=
              { str_xdo, str_zrn, str_iog, str_tnu, str_acb, str_eyr,
                str_llm, str_gzl, str_uvq
                |
                str_xal$0 <= str_klp$0 }))
        )
      END
    ELSE
      CHOICE
        skip
      END
    END ||
    ANY
      str_jun, str_uvq, str_iyh, str_hcv, str_yhy, str_dus, str_ugf, str_uui
    WHERE
      (#
         (str_ukr, str_nyp, str_obm, str_pfn, str_rgd, str_vpx, str_luj,
          str_qsv, str_lgu).
       (str_baz$0 <<: str_erx <=> TRUE /<<: str_swk) <=>
       !(str_zoi, str_gup).(not(str_var /<<: str_pti))) &
      #(str_wud, str_yio, str_yef, str_mlj, str_vku, str_stk).
      (str_jql <= str_qze)
    THEN
      str_wcg 
        (
          { str_aih, str_bed | INT = FALSE } +->>
          ({ str_wxg, str_ftl, str_fdj, str_qxk, str_ltm, str_jni, str_qik,
             str_rpq, str_oqe
             |
             str_kuu /= str_vgj }
             (rec
                (str_pgx:
                 (str_oxy +
                  INTER
                    (str_pkq, str_kup, str_gog, str_rzf, str_ppg, str_sqm,
                     str_fql).
                  (str_qyt <<: "str_slu"| str_yid$0)),
                 str_nnd: str_xkc$0,
                 str_hdw: str_svl$0,
                 str_dfu: str_cdr$0)))
        )
        (
          {str_wze,
           ((str_wea$0 , BOOL) |>> str_aqv),
           TRUE,
           {},
           str_fxz,
           str_pyb,
           ({NAT, str_fcy$0, FALSE, NATURAL, str_lqj, str_mmw, MAXINT,
             str_hbi}
              (BOOL))}
          ,
          (Succ(BOOL))
        )
      
      :=
      Pred
        ({{ str_lkz, str_kwf, str_tgv, str_bdi, str_ahk, str_ewm, str_nbc,
            str_ali
            |
            #(str_fjf, str_xmx, str_glo, str_hay, str_qvq, str_otl).
            (str_obp /: NATURAL) },
          bool(str_fco$0 = str_rbm$0),
          bool(str_npc <<: str_vyj & str_yof$0 > str_szz$0),
          str_eop$0,
          str_nxl,
          str_edq$0})
    END
  END;

  str_onc, str_pnq, str_lmr, str_och, str_osq, str_ovu, str_mzs, str_tjq,
  str_rbw, str_wpm
  <--
  str_iue (str_dcw, str_xhc, str_chd, str_crr, str_ddn, str_kxp)
  =
  ANY
    str_ydb, str_vwc, str_ohg, str_ftq, str_glb, str_mva, str_fpp, str_pwu,
    str_zvy, str_kha, str_wqf
  WHERE
    #
      (str_cnh, str_rhf, str_jcd, str_cuy, str_pic, str_mxz, str_vqb,
       str_nkx, str_sjo).
    (#
       (str_rei, str_jpx, str_knh, str_uzd, str_yaq, str_gby, str_bcm,
        str_gwv, str_ner).
     (STRING /: str_teq <=>
      not
        (!(str_fmq, str_wlf, str_erz, str_bpi, str_bub).
         (#(str_rix, str_txx, str_lhj, str_aqv).(str_eim >= NAT1)) or
         str_ysx$0 : str_lun$0)))
  THEN
    SELECT
      bool(#(str_qtm, str_lmx, str_awf).(str_isp$0 : str_fzd)) |-> [NAT] /<<:
      [str_qhj$0] +->> str_faz
    THEN
      VAR
        str_xwe, str_vxr, str_zfq, str_qec, str_ncb, str_lit, str_deh,
        str_ccv, str_wcv, str_bxu
      IN
        str_ofu, str_ebx, str_guk, str_fns :(
          bool
            (#(str_ujd, str_fed, str_zqm, str_bch, str_jcn, str_imt).
             (!(str_esu, str_zzv, str_ghc).(str_rqi$0 : str_ccl$0) =>
              BOOL <: NAT1)) /<<:
          {{NAT1, str_ujx$0, INT, str_bze, str_eam$0, str_iwc, str_pef,
            str_kun$0},
           str_vcl}
        )
      END
    WHEN
      !
        (str_zzf, str_uhe, str_hkr, str_oey, str_mqt, str_xhb, str_cvc,
         str_fxy).
      (#(str_dbp, str_uvs, str_uoq, str_obj, str_our, str_lyb).
       (not(not(not(NATURAL1 = union(str_hww))))))
    THEN
      CHOICE
        str_szu, str_ukd
        :=
        bool
          ({str_dmf,
            rec
              (str_zla: {},
               str_ukm: NAT1,
               str_tjq: {str_mft$0, STRING, str_asy$0},
               str_siw: NATURAL)} >=
           rec(str_wco: str_qev$0, str_nmr: {[], str_ftp$0, MININT}))
      OR
        str_eux
        :=
        struct
          (str_ypi: (NATURAL1 , MAXINT),
           str_dpc:
           rec
             (str_auc: INT,
              str_qib: str_ogi,
              str_scb: str_hou,
              str_zvl: (mirror(INT)),
              str_rsc: INTEGER,
              str_okz: MAXINT,
              str_gsd: str_hns$0,
              str_csl: str_uxn),
           str_jio:
           struct
             (str_kcs: BOOL,
              str_kjx: str_cit$0,
              str_cig: {str_zib, str_oum$0, str_ybb}),
           str_ytv: str_myy$0,
           str_wae: str_dik$0,
           str_fhk: str_nnf$0,
           str_ugb: UNION(str_qod, str_zuf). (str_vqy <<: str_qco$0| str_cdl))
      OR
        str_fet'str_vlj
        :=
        ((str_jux$0("str_xab")) |-> NAT)
        ,
        (str_hqu$0
           [ran
              ({str_tvb, str_rtt, str_juc, INT, NAT, str_whk$0, str_xzh$0,
                INTEGER})])
          'str_qne ||
        str_hlj, str_gmv, str_qhr, str_cjp, str_ptm, str_zdr, str_wgk,
        str_sur, str_mxt, str_bra
        :=
        bool
          (#(str_tiw, str_bod).
           (not
              (str_yuc$0 = NATURAL &
               #(str_wyr, str_als, str_bzb).(not(INT >= str_qwq)))))
          'str_fyy
      OR
        str_qlt
        <--
        str_xun
          ((conc
              ([{ str_oiz | NAT1 /: str_man$0 }, {str_dpb}]
                 (str_jvt([INTEGER, str_crt, str_xqo$0, INTEGER])))),
           [str_eko,
            str_oke$0,
            { str_zbj, str_zbq, str_oam, str_rzm, str_dgm, str_tfz, str_plu,
              str_fah, str_ukx, str_zta, str_koo
              |
              str_tdc$0 /<<: NAT & not(not(not(str_oxz : str_caz))) },
            str_rck$0,
            TRUE]
             'str_zfp)
      OR
        ASSERT
          !
            (str_jzj, str_nib, str_bmg, str_zyz, str_sms, str_rkm, str_vuq,
             str_wdg).
          (!(str_wpe).
           (!
              (str_rbv, str_jlc, str_ntj, str_fmr, str_zfj, str_srr, str_omf,
               str_yfz).
            (bool(bool(MININT <<: str_dch) >= str_gdy) <<: str_ojg$0)))
        THEN
          str_opr
            ([str_prs,
              (seq([NATURAL])),
              BOOL,
              str_wbo$0,
              struct(str_vmv: {(str_vyj(bool(str_fzf$0 < [])))}),
              str_xin$0,
              NAT,
              str_ksv$0],
             PI(str_qpv, str_dds, str_bzz, str_dto, str_kzo, str_vmu).
             (!(str_amq, str_pyx, str_hnh, str_bst, str_onj).
              (rec
                 (str_tql: str_hun$0,
                  str_kcj: str_yzl,
                  str_nmp: FALSE,
                  str_nqf: NAT1) <:
               [str_whk$0, str_egw, (subtree(str_ioe$0)), str_ksr$0]'str_nmf)|
              str_kor$0))
        END
      END
    WHEN
      not
        (rec
           (str_wrp: TRUE,
            str_onv: str_hoq,
            str_biy: MININT,
            str_hmv: NAT1,
            str_zsp: (str_qsp , str_mqs),
            str_dqk: str_kja$0) /:
         bool
           (#(str_mpz, str_dsu, str_axe, str_olz, str_oqd).
            (NATURAL = NATURAL1))
           'str_mng)
    THEN
      str_nvi, str_cbw, str_hwj, str_jlw, str_uny, str_dxa, str_zsr, str_yrk,
      str_mee
      ::
      first
        (bool
           (!(str_syc).
            (not
               (!(str_fjh, str_ufn, str_noj, str_dqp, str_gaf, str_izz).
                (!(str_ike, str_apr, str_ypl, str_grm, str_qpk).
                 (!(str_jyn, str_czw, str_sul).({} : str_clc)))))))
    WHEN
      str_nap <:
      FIN
        ([MININT,
          str_syb$0,
          str_sek,
          str_pmt,
          STRING,
          rec
            (str_qpq: INTEGER,
             str_lqj: FALSE,
             str_ztd: str_pkd$0,
             str_uvi: "str_fcv",
             str_htl: str_ysq$0,
             str_nzp: str_txh$0,
             str_wpe:
             struct(str_lvc: str_ddy$0, str_zev: {}, str_uva: str_gfi$0))
            'str_ppc
            'str_rhp,
          {},
          str_olb$0])
    THEN
      str_giq, str_jvx, str_jps
      ::
      bool
        (!(str_zkn).
         (struct
            (str_ger: str_wix$0,
             str_iaw: str_zyt$0,
             str_blc: str_xtg,
             str_fku: bool(str_wwr$0 /<: str_qjf),
             str_lcp: str_ziz,
             str_adc: str_oza,
             str_gwe: (infix(MININT(str_zyb)))) =
          NAT))
    WHEN
      {(rec(str_qah: NATURAL, str_qwb: str_you$0) / BOOL'str_cvb)} >
      {struct(str_mrz: 4878, str_lon: MININT, str_yhp: NAT1)}
    THEN
      IF
        !
          (str_xnl, str_ucu, str_wtp, str_pob, str_cjw, str_hyx, str_uie,
           str_pkn, str_ddp, str_cdh, str_xol).
        (not
           (#(str_zyh, str_vlu, str_xxz, str_van, str_zdu, str_xat).
            (str_pjr$0 <: str_bit$0))) &
        not
          (#
             (str_qbd, str_hzb, str_wsf, str_agb, str_lso, str_ogr, str_ele,
              str_vbc, str_pau).
           (str_wba : BOOL))
      THEN
        str_jlv <-- str_mdm
      ELSIF
        !
          (str_nep, str_cgm, str_pdm, str_yaj, str_oyl, str_ell, str_tdm,
           str_fnm).
        (rec
           (str_upo: str_ewk$0,
            str_syo: str_lps,
            str_kpj: str_jhu,
            str_jmc: MAXINT,
            str_gxe: str_sug$0,
            str_wxa: str_hpp$0,
            str_uum: NAT,
            str_niw: str_ugn$0) >
         {str_zyf,
          str_cez,
          BOOL,
          {},
          NATURAL,
          {str_ghj, str_ynv, BOOL, ([STRING] |-> str_dds), INTEGER},
          MININT})
      THEN
        str_oys 
          (
            %(str_hxs, str_ktk, str_lak, str_ymk, str_lpl, str_imx).
            ((str_vph$0 <<: str_sht$0 =>
              !(str_dxd, str_dzz, str_hbk, str_fsc, str_lup, str_meq).
              (not(not(str_gwu$0 = NATURAL1)))) or
             INT <<: FALSE|
             INTER
               (str_sin, str_clp, str_uty, str_dfc, str_jmo, str_moq,
                str_fid, str_tot, str_zhl).
             (str_hzy /<: str_lep| str_vog$0))
          )
        
        :=
        son
          (struct
             (str_jge: str_nod$0,
              str_npk: bool(#(str_avi).(not(str_bev$0 <= str_msr))),
              str_bwq: str_qyi,
              str_aoh: str_bzb$0,
              str_mxy: {str_yuc$0, INT, str_lfa, str_pcq, str_rot$0},
              str_hzs: str_vaz,
              str_xaj: str_spn$0'str_tmb,
              str_ewd: str_ohc))
      ELSIF
        {((str_rdq , str_jzj$0)
            (SIGMA
               (str_kmy, str_feq, str_eqq, str_wsu, str_dmv, str_uli,
                str_roj, str_mii).
             (str_kxy$0 /= str_sxe$0| str_ddg)))} /:
        { str_dbd, str_has, str_sow, str_gnq, str_fbf, str_iuy, str_tcc,
          str_wud, str_tjg, str_hnq
          |
          str_ynx /<<: str_zen$0 & str_daw /: MININT }
      THEN
        str_rhg, str_jnf
        :=
        PI(str_tku, str_yaw, str_qbs, str_xko).
        (!(str_thx, str_ftk, str_khc, str_ggd, str_ffs).(str_tnt$0 = TRUE) &
         INTEGER /<: str_zpm$0|
         const(rec(str_ouf: INTEGER, str_vuy: NATURAL1) |-> str_fmk))
          'str_yca
      ELSIF
        {((str_mzj ;
           struct
             (str_aub: str_phy$0,
              str_cpn: str_mcg,
              str_gcd: NAT1,
              str_rnb: str_tub$0,
              str_ikb:
              { str_wkz, str_iej, str_zin, str_ysm, str_yij, str_grr, str_tmn
                |
                str_akl$0 < [] }))),
         str_udn} :
        struct
          (str_bcq: str_yxu,
           str_vyg: FALSE,
           str_ocg: str_mpz$0,
           str_qgi: str_fwl,
           str_koo: str_srh,
           str_dje: str_tqj$0,
           str_ezx: str_yjc,
           str_rdw:
           %
             (str_xkp, str_ezi, str_org, str_aay, str_gry, str_gnn, str_fsp,
              str_dwl, str_imc).
           (str_vdq$0 <<: MAXINT| str_vdi))
      THEN
        str_mvr 
          (
            struct
              (str_rhi:
               (NAT1
                ,
                PI
                  (str_kth, str_uyz, str_dss, str_hnj, str_wtb, str_ajm,
                   str_bdo, str_qgf, str_pri, str_iir).
                ({} = NATURAL1| str_nur$0 |-> str_pdl)),
               str_isg: (((postfix(str_uof))(str_wfx)) <- str_iyu))
          )
          (
            struct
              (str_pen: BOOL,
               str_rgd: str_kuu$0,
               str_yal: NAT,
               str_ydm:
               (%(str_xet, str_quf, str_ejw).
                (BOOL <: str_lgw$0|
                 {STRING, str_zfo, str_xix$0, str_rpx$0, MININT, str_ryf$0}
                   'str_ren)
                  'str_fpm
                |->
                str_xbr),
               str_svp: str_akx,
               str_jpy: INT,
               str_cen:
               struct
                 (str_gys: NATURAL1,
                  str_iyo: str_wgr,
                  str_zhg: str_uox,
                  str_qba: str_ezs),
               str_ovi: str_onh$0)
          )
          (
            rec
              (str_yas:
               { str_vod, str_jpb, str_gha, str_vsx, str_gwq, str_ofd,
                 str_afe, str_dok
                 |
                 not
                   (#
                      (str_elq, str_jlu, str_usi, str_hvk, str_rto, str_yvg,
                       str_wmx).
                    ((str_qlu$0 /= INT & str_yiq$0 : BOOL) <=>
                     str_vxa$0 <= str_feq)) }
                 'str_odo)
          )
          (
            struct
              (str_luk: (str_bji(str_sql$0)),
               str_czi:
               bool
                 (!
                    (str_oed, str_wrx, str_ayu, str_ton, str_uhn, str_dwa,
                     str_rwj).
                  (str_alo$0 > NAT) =>
                  str_juw$0 /: {})) /\
            PI(str_pok, str_mzu, str_gxo, str_mtc, str_jkb, str_taw).
            (str_ijk$0 < str_eii$0| str_huq$0)
          )
          (
            rec
              (str_bzj:
               %
                 (str_hiy, str_nqw, str_out, str_oaf, str_gee, str_bwi,
                  str_jtn).
               (str_lst$0 : str_gbl|
                SIGMA(str_dwv). (MAXINT = str_jpl$0| str_sjg)),
               str_kbq:
               UNION(str_tio, str_ano, str_suk, str_jfs).
               (str_dfl >= str_pey$0| NATURAL),
               str_tex: str_men$0,
               str_evw: str_zop$0,
               str_zeo: str_bsn$0,
               str_lju: str_yfw$0,
               str_tba: str_hsf$0,
               str_hev: (str_mqy(str_stf$0)))
              (str_mey |-> str_fly)
          )
          (
            INTER
              (str_pgk, str_ylr, str_rql, str_sck, str_zbl, str_awz, str_ohs,
               str_kfq, str_che, str_lca, str_puy).
            (!(str_lqd, str_asc, str_gzg, str_ndv).
             (MININT < str_uum$0 => str_hhq$0 < str_jst)|
             INTEGER) /\
            (POW([(str_dvn$0 |-> str_kvi)]))
          )
          (
            (bool
               (#
                  (str_vwd, str_int, str_lik, str_dlj, str_pyr, str_nsc,
                   str_mip).
                (!(str_eby, str_bqo).
                 (!
                    (str_tdl, str_nts, str_wyd, str_auf, str_bhn, str_gto,
                     str_xty, str_nbn, str_xws, str_vjy).
                  (str_agw$0 <<: str_pci))))
             ,
             [STRING, BOOL, str_yfb])
              'str_qdw
          )
          (
            {str_ipv, MININT, str_mmj, MININT, str_tuh, "str_vwn"}
            ,
            {str_tbs$0,
             str_hku$0,
             bool
               ({ str_omw | #(str_rwr, str_caa, str_say).(str_rhp : INT) } <=
                MAXINT),
             BOOL,
             str_ycx$0,
             {}}
          )
          (
            %(str_qhb, str_zqc, str_dbf, str_tap, str_afa, str_uvs, str_uzt).
            (!
               (str_ple, str_prl, str_qvd, str_nog, str_rmj, str_hna,
                str_oow, str_vij, str_jrx, str_ycp, str_djk).
             (str_uyc /: str_qza$0)|
             bool(INT /: str_xly))
            |->
            {(first(bool(str_stt >= str_dyt$0))),
             str_afa,
             str_axb$0,
             str_xub,
             str_xdn$0,
             str_lhv$0,
             FALSE}
          )
          (
            rec
              (str_qmo: str_sab$0,
               str_zvb: ({TRUE} |-> [str_ucw$0, str_gec]),
               str_qcq:
               INTER(str_gsm, str_was, str_iqq, str_tnn, str_rhw, str_jxu).
               (not(NATURAL <<: MININT)| str_wun),
               str_mut:
               rec
                 (str_xzt: str_ngi,
                  str_fim: str_jih,
                  str_uhf: BOOL,
                  str_kkr: [],
                  str_azw: str_rtq),
               str_xxb: TRUE)
          )
        
        :=
        (iterate
           ({INTEGER,
             str_pjg,
             INTEGER,
             str_iut,
             str_jof,
             struct
               (str_zpv: STRING,
                str_and: TRUE,
                str_wia: (str_rpc(bool(not(INT /: str_sbg$0)))),
                str_udx: str_pnt,
                str_aeq: str_nhm$0,
                str_rkd: str_tim),
             TRUE}))
          'str_omj
      ELSE
        str_iwg, str_gyq, str_ehj, str_spq, str_rbm, str_yvf
        :=
        {str_usl$0,
         [str_shm, str_blj$0, str_dan, NATURAL, {}, str_qyx, str_cbd,
          str_jbo$0],
         str_voa$0}
          (UNION
             (str_sva, str_ywt, str_tor, str_kim, str_adn, str_mvm, str_eym,
              str_xip, str_mok).
           (INTEGER /<<: NATURAL => str_ect$0 /<<: str_ecj$0| str_bup'str_agt)
             'str_hdq)
      END
    END
  END;

  str_kfc, str_mba, str_lnq, str_ewb, str_baz, str_uvk
  <--
  str_vkx (str_gyu, str_wxe, str_bgs, str_lba, str_hjf, str_vmx, str_wtu)
  =
  ASSERT
    [{ str_ema, str_evp, str_ilw, str_ina, str_tey, str_khw, str_dyl,
       str_zzi, str_tbc, str_nmf
       |
       str_ahe$0 /<: str_dpn },
     rec
       (str_cin: str_ydo,
        str_xmt: str_bst$0,
        str_ome: str_dap,
        str_aqh:
        struct
          (str_ldv: str_dtp$0,
           str_ppd: str_uyk$0,
           str_cuj: str_pfc,
           str_mnt: str_gbq$0),
        str_xrb: str_dgs)] /:
    INTER(str_pdh, str_trv).
    (str_uwk$0 : str_rgp$0|
     [str_yld$0, str_fpi, {}, TRUE, MININT, str_lbl$0, str_okf$0])
  THEN
    IF
      rec
        (str_fpf: %(str_vlm, str_dyd, str_oth). (str_ooa < str_mrx| str_qbh),
         str_pyo: INT,
         str_sjq: str_qzf$0,
         str_vpk: (INT , BOOL),
         str_toi: (subtree(struct(str_mze: str_yqw, str_fiw: str_txc)))) =
      str_edl'str_fiq
    THEN
      PRE
        #(str_zxu, str_keh, str_ybl, str_jqs, str_esk).
        (str_uao < str_kwz >->> str_wot$0 & not(str_imc'str_wnt <= str_cdp$0))
      THEN
        str_ven, str_rcu, str_euw, str_ncq, str_gmv, str_tyx :(
          #(str_ubh, str_lye, str_ozh, str_nyx, str_hzq, str_usl).
          (!(str_esf, str_htp, str_mjk, str_bqq, str_rsu).
           (bool
              (#
                 (str_vjq, str_opi, str_zrp, str_mqn, str_zaf, str_zls,
                  str_fhz, str_kyd, str_glj, str_dru, str_vhs).
               (#(str_pbr, str_oxm).(str_dqh <<: str_yas$0))) =
            INT'str_zka))
        )
      END
    ELSIF
      not
        (#(str_eic, str_dfc).
         (#(str_dqh).
          (!
             (str_dju, str_tdg, str_wvl, str_ibi, str_hqp, str_dii, str_pju,
              str_nxa, str_thf, str_gfx, str_vtf).
           (!(str_gun, str_thz).
            (INT <: [str_erb$0, str_qgl$0, TRUE, str_jee])))))
    THEN
      skip
    ELSIF
      arity([]) <:
      struct
        (str_dki: str_rge,
         str_pcn: NATURAL,
         str_qkt: str_ymz,
         str_gud: str_rvc,
         str_efv: str_rew,
         str_tfa: str_aqn,
         str_osk: 98,
         str_xuq: str_lto) or
      51'str_muu /= str_nos$0(1)
    THEN
      CHOICE
        skip
      OR
        IF
          not
            ((not(str_ivz$0 <: str_net$0) <=>
              (str_qco /: NATURAL or str_atw <: str_keb)) <=>
             not
               (!(str_dbb, str_ddl, str_oah, str_mlt, str_tmv).
                (str_thp$0 <: NAT)))
        THEN
          str_qni, str_phk, str_lvj, str_tqy, str_ueg, str_ega
          ::
          struct
            (str_qaw: str_fbf,
             str_qmb: str_vki,
             str_rzl: str_hzi,
             str_eit: str_frz,
             str_hjd: (str_tjs <- str_qre),
             str_pqz: str_meb,
             str_vpo:
             (father
                ({str_dxd$0,
                  (str_qyt$0 , TRUE),
                  {INT, ([] \|/ NATURAL), str_wem$0},
                  str_swl,
                  [],
                  str_wtg,
                  {}})),
             str_xwm: str_jxo$0)
        ELSIF
          #
            (str_pul, str_dre, str_coa, str_qss, str_hwx, str_ost, str_dmp,
             str_dxv, str_uxr, str_vap, str_jvr).
          (!
             (str_tyf, str_dej, str_kgv, str_iod, str_rdm, str_tnw, str_tui,
              str_jub, str_mgt, str_mwm, str_ebc).
           (!
              (str_dkd, str_eei, str_uaq, str_fsm, str_lsh, str_exa, str_fkn,
               str_bzc).
            (str_yvw$0'str_jmb <<: str_xqa$0) <=>
            !(str_mld).(str_ryc <: str_ccv)))
        THEN
          str_mmg, str_xll, str_pnn, str_mzr, str_uqy, str_wpp, str_tyg,
          str_fqr
          :=
          bool
            (#(str_byg, str_ikm, str_zml, str_erm, str_vct).
             (not
                (!(str_lvq, str_ebf, str_bvm, str_hyf, str_qio, str_sas).
                 (str_rgd$0 /= str_had)) or
              #(str_zyk, str_yzy, str_ghk, str_rli).
              (!(str_lkn).(str_cta$0 /: str_mcn$0))))
        ELSIF
          PI(str_rmd, str_lro, str_rwp, str_fiv, str_jyw).
          (str_iqp$0 /: INTEGER|
           [str_jfc,
            str_hfz$0,
            str_mja$0,
            (str_hvn$0(NATURAL1)),
            { str_hcz, str_efm, str_sns, str_mqk, str_yzi, str_kdh, str_elp,
              str_pgz, str_wrr, str_aoe
              |
              str_zir = str_uii },
            str_bqc$0,
            str_gpa$0,
            str_ntk$0]
             'str_mao) <=
          NAT[str_mfb]
        THEN
          str_fem, str_vho
          ::
          {struct
             (str_msi:
              bool(#(str_qbr, str_kny).(str_hym$0 * MININT < str_uli$0)),
              str_wel: str_xrz'str_fol),
           str_klu$0,
           INTEGER}
        ELSIF
          not
            (bool
               (str_geu =
                rec
                  (str_ioq: NAT1,
                   str_bbr: str_fgi$0,
                   str_mbv: str_bfs$0,
                   str_ijb: [],
                   str_nfh: INT,
                   str_wnb: str_ozp,
                   str_xkz: str_svk,
                   str_qhl: {}) &
                str_ozq < str_pns$0)
               'str_xfx /<<:
             MAXINT)
        THEN
          str_duw'str_dub
          :=
          PI(str_ilo).
          (#
             (str_git, str_ltk, str_xeh, str_hmf, str_rnl, str_iny, str_cni,
              str_juk, str_ykg).
           (#(str_orx).(NAT1 <= str_yaw$0))|
           %(str_kue, str_ibb, str_nkn, str_iih, str_bug).
           (BOOL < str_zho$0| { str_oep | str_jxw = {str_cms} }))
        ELSIF
          !(str_ldl, str_amm, str_pfs).
          ((not(not(#(str_qdi, str_duq, str_lth, str_otk).(NAT /<: FALSE))) or
            str_vaw$0 <= str_wef$0) <=>
           str_fvq$0 < MININT)
        THEN
          str_dwo, str_hku :(
            8 >
            [str_wmq$0,
             FALSE,
             INTEGER,
             NATURAL1,
             str_yli$0,
             str_tin$0,
             TRUE,
             (str_lot /\ { str_esj | str_rrs /<<: str_tar$0 })] =>
            (str_pgu$0 > str_urk$0 & str_bcm /<<: str_bod$0)
          )
        ELSIF
          not
            (bool(str_kuc < NATURAL1) :
             (bool(str_nmx <: NAT1) |-> str_ugz) <+ (prj2(str_qxg)))
        THEN
          str_tzc, str_qsi, str_hap, str_gvn :(
            (mirror({NATURAL}))
            ,
            struct
              (str_mat: str_pmg,
               str_mao: NAT,
               str_vzw: str_ycy,
               str_peo: str_tsl) >
            rec
              (str_muy: [],
               str_unt: str_xau$0,
               str_xwz:
               SIGMA(str_acq, str_alk, str_svn, str_vdt).
               (str_xnm /<<: NAT1| str_ecl$0),
               str_xih: str_ebm,
               str_gys: str_mbi$0,
               str_nwr: str_ece)
          )
        ELSIF
          not([] <: (prj1(NAT1))({})) or
          #(str_xua, str_iyf, str_zdj, str_oym, str_lfs, str_xtz).
          (not(str_cnb$0 < str_djz))
        THEN
          skip
        ELSIF
          INT /<<:
          { str_szk, str_bpw, str_nqn, str_zon, str_hxh, str_ulq
            |
            str_rfk$0 <= str_zam & str_ytt <: str_ytr$0 } +->>
          (INTEGER
             ({str_mtp,
               NATURAL1,
               str_ryq$0,
               {NAT, str_clt$0, str_pmo},
               str_wix,
               str_zpk}))
        THEN
          str_phl, str_kok, str_uci, str_ikt
          :=
          rec
            (str_wjy: 749'str_lqq,
             str_msp: (str_ssa$0 |-> 7),
             str_cmw: str_bqd$0,
             str_dtd: [INT, str_hoc$0, [], NAT, str_fac, str_ycq$0],
             str_ofd: str_keg) <->
          (postfix(str_gpf[NAT1]))
        END
      OR
        str_cvz 
          (
            struct
              (str_igq:
               ((str_iao$0(str_lsj$0))
                ,
                {str_jli, INTEGER, str_yce, MININT, TRUE, str_jru$0}),
               str_toy: str_usf,
               str_bxf: [str_hgj$0, str_oun$0, NAT],
               str_zas: str_zfn$0'str_dih,
               str_ufi: str_eww'str_vrt,
               str_mtw: STRING,
               str_jgg: str_ihc,
               str_kjk: str_jns$0)
          )
          (
            (NATURAL1
               (rec
                  (str_dpx: TRUE,
                   str_gap: str_pgm,
                   str_zks: str_vsi,
                   str_qsh: str_mhq$0,
                   str_gzd: str_cjd$0)))
              ({ str_rsa, str_ynw, str_zgs, str_hid, str_ebk, str_mjv,
                 str_jke, str_lkx
                 |
                 !
                   (str_jmm, str_utj, str_rfl, str_hfg, str_eas, str_jfy,
                    str_wls).
                 (FALSE /: TRUE) }
                 (bool(str_xag /<<: str_ypf$0)))
          )
          (
            SIGMA
              (str_xxe, str_dti, str_zji, str_peg, str_yne, str_rqm, str_zxp,
               str_nnz, str_zsi, str_eif, str_rxs).
            ((str_ngp < MAXINT <=> str_jpa$0 <<: str_ojp) &
             INT <
             rec
               (str_wfm: bool("str_nud" /: TRUE),
                str_plu: STRING,
                str_fbb: str_eue,
                str_nan: 536,
                str_gff: str_wkp$0,
                str_osi: NAT)|
             str_idt(str_lrk$0))
          )
        
        :=
        PI(str_okx, str_pwn).
        (not(not(not(!(str_fcz, str_sjl).(NAT1 /= TRUE))))|
         %
           (str_ajq, str_tbu, str_juc, str_tnd, str_yaw, str_fef, str_xhl,
            str_fue, str_ldx, str_pbq).
         (str_ran /<<: str_wqi| bool(str_ysy > str_ums)))
      OR
        str_erl, str_sdd, str_ndy, str_kur, str_elh, str_hal, str_kky,
        str_wjp :(
          !(str_dnt, str_bsk).
          (!
             (str_owa, str_nmr, str_qrm, str_ayb, str_wmz, str_sth, str_okk,
              str_gzb, str_qnn).
           (MAXINT /<<: str_bfi$0 =>
            !(str_uwj, str_jqq, str_ymi, str_vzs, str_blc, str_pyu, str_luh).
            (#
               (str_otx, str_otz, str_aua, str_pgb, str_cbs, str_pmr,
                str_puh, str_ssq, str_cbh).
             (!
                (str_bnz, str_xdk, str_awf, str_lmm, str_dgn, str_fap, str_qnn).
              (#(str_onu).(str_pbt : STRING))))))
        )
      OR
        str_yfs'str_tgf
        :=
        bool
          (!(str_rud, str_xzc).
           (!(str_zep, str_ebs, str_cvk, str_esw, str_stb).
            (str_nqo = [str_ipv$0, str_pmz, STRING] => str_peu /: str_vcg$0)))
      OR
        str_dbh 
          (
            struct
              (str_ckx:
               PI(str_gql, str_ttw, str_wyk).
               (#(str_nca, str_slp, str_oyw, str_kzv, str_tzr, str_qru).
                (str_kul$0 <= str_ngp$0)|
                str_ctl),
               str_mla: str_kvl,
               str_ltg:
               bool
                 (bool(str_eba$0 /: str_xbq$0) <
                  { str_xdc, str_fvf, str_zsa, str_pkd, str_poh, str_blp,
                    str_skh
                    |
                    str_amn$0 = STRING }))
          )
          (
            rec
              (str_rry: TRUE,
               str_zvs:
               [struct(str_nzq: str_ikj$0, str_sha: {{}}),
                rec
                  (str_izj: str_diu$0, str_iqs: str_hvm$0, str_tre: str_hed$0),
                str_ust$0,
                rec(str_nmc: str_vnb$0'str_wgh)],
               str_tgx: str_zvc,
               str_oic: str_mzh,
               str_sxe: str_nhu,
               str_cjr: str_mor,
               str_zqp: str_fsi,
               str_ucg: str_pdp$0)
          )
          (
            { str_zro, str_wqk, str_ymc, str_wfl, str_vdd, str_rgg, str_cfs,
              str_tjr, str_aev, str_fni
              |
              !
                (str_cqu, str_huf, str_mwm, str_ugw, str_rbu, str_bsj,
                 str_gcy, str_cdo, str_jbn).
              (struct
                 (str_yme: str_wcw$0,
                  str_qoi: str_exq,
                  str_smi: str_qft$0,
                  str_gkg:
                  { str_sio, str_avl, str_pok | not(str_lyv$0 /: str_mwv) }) /<:
               str_lgl$0) }
          )
          (
            front
              (struct
                 (str_sht: ((str_ycv'str_bzl <- str_quw$0) , 1),
                  str_byb: (MININT , TRUE),
                  str_uzy:
                  [str_mzz, "str_qkj", str_clh$0, str_rfg$0, str_hci,
                   str_npy$0, INT]))
          )
          (
            rec
              (str_pmu:
               struct
                 (str_smg: str_fmw,
                  str_zmi: NAT1,
                  str_uai: str_wpl$0,
                  str_lfk: TRUE,
                  str_wuz: []),
               str_iro: {str_lja, NAT1, FALSE}) +->>
            (%(str_pif, str_rea, str_jql, str_ase, str_rqb, str_bfn, str_btl).
             (str_yhi < str_kyc| btree(str_txr$0))
               (str_sxy$0))
          )
          (
            bool
              (not
                 (!(str_knn, str_mnu, str_ewi, str_smo, str_oeo, str_bdk).
                  (92 <<: str_wof <=> MAXINT >= str_chh)))
            |->
            UNION(str_btq, str_jnz, str_rbv, str_ahi).
            (str_igr$0 /<: {}| TRUE)
          )
          (
            bool
              (#(str_pti).
               (#(str_fzm, str_ush, str_vht, str_lbk).
                (#(str_qoz).
                 (NAT1 |-> str_yll <:
                  { str_elc, str_qio, str_gwh, str_gbw, str_tjs
                    |
                    18 = str_gwg$0 }))))
          )
          (
            INTER
              (str_bvr, str_oyo, str_msj, str_lxk, str_obl, str_xsb, str_frc,
               str_nhg, str_ufe).
            (!
               (str_pnd, str_toy, str_zbt, str_dxg, str_fap, str_ljl,
                str_vip, str_rrs, str_nwf, str_wux, str_mrh).
             (str_zgk : str_qdg$0)|
             NATURAL <<| str_dpd$0)
            |->
            {str_hxk,
             { str_ijg, str_uzx, str_keb, str_scl, str_apb, str_zyw, str_war,
               str_jsc, str_tqf, str_cyz
               |
               MININT <<: str_yrw$0 => str_wkm /: str_xxa },
             str_eog,
             STRING,
             str_vwm}
          )
          (
            { str_zjy, str_cvu, str_ffw
              |
              #(str_ndl, str_dvh, str_ark, str_vtj, str_juw, str_yto).
              (#(str_jql, str_afm).
               (!(str_dxx, str_soe, str_isf, str_trt, str_nrh, str_ubf).
                (str_axm = str_unb or str_rgo /= closure(NAT1)))) }
          )
          (
            {INTEGER,
             str_ulc,
             { str_bsf, str_fwn, str_qpl, str_omu | str_uyk <: MININT },
             {},
             struct
               (str_msg: str_ccr$0,
                str_phf: str_dhi$0,
                str_ryw:
                INTER(str_icq, str_tcu, str_ndw, str_onz, str_dcn, str_oxi).
                (!(str_ffy, str_kcn, str_wmy, str_kcx, str_dbp, str_uxr).
                 ([] >= MAXINT)|
                 str_toe$0),
                str_ebu: str_zfb,
                str_wqo: str_zgu,
                str_zct: str_ttn$0,
                str_jbc: bool(str_tbc$0 /: TRUE))}
          )
        
        :=
        (str_jdv$0 , str_ivt$0)
          (INTER(str_ski, str_nmu).
           (#
              (str_jop, str_syt, str_zfv, str_rai, str_wzf, str_wrq, str_qrv,
               str_nab).
            (#(str_gfx).(str_sxg$0 = TRUE & str_cus <<: str_ofx$0))|
            rec
              (str_ors: str_set,
               str_kyl: NAT,
               str_lny: INTEGER,
               str_pis: NATURAL1,
               str_jcl: str_gdy)))
      END
    ELSE
      ASSERT
        #
          (str_blg, str_gyj, str_kse, str_afa, str_hbh, str_aql, str_taq,
           str_qvi, str_fna, str_hgh).
        ([MAXINT, str_fre$0, TRUE] >= str_ahh$0 or
         (str_xnc = str_won => [str_ukk, str_zsl, str_cxm, str_nzn$0] /<<: 2))
      THEN
        WHILE
          not
            (not
               (not(str_sts$0 /: str_tuq$0 <=> NAT <= str_skn) <=>
                (NAT1 = FALSE =>
                 !
                   (str_qfw, str_olp, str_fpn, str_rdr, str_fab, str_dhb,
                    str_imm).
                 (INT <: str_pft))))
        DO
          skip
        INVARIANT
          !
            (str_hru, str_qsz, str_mtj, str_ljt, str_ahb, str_qtc, str_szm,
             str_dhq, str_dik, str_kxs, str_gib).
          ([str_jbm$0, []] /<<: str_drb &
           ((str_woa$0 /<: NATURAL1 & str_eqa <<: str_cfb) =>
            #(str_bmb).(str_zdf$0 /<: BOOL)))
        VARIANT
          subtree
            (struct
               (str_tbh: FALSE,
                str_cww: str_kld$0,
                str_trs:
                ((rec(str_xco: NATURAL, str_amh: str_yoq, str_xdo: str_akh$0)
                    ("str_fzj"))
                 ,
                 str_kec$0'str_cek),
                str_mli: (str_uim |-> str_gct$0),
                str_rif: str_nql,
                str_wdt: str_elg,
                str_ada: 4))
        END
      END
    END
  END;

  str_ubd, str_tdp, str_jnh <-- str_hqd (str_xnt) =
  CASE
    first
      ([str_yqv$0,
        { str_xck, str_eae, str_nmd, str_cst, str_oyw, str_dva, str_yut,
          str_dhz, str_frb
          |
          str_rgr$0 >= str_jxa },
        { str_jkl, str_wyc, str_avg | "str_uri" < str_wka }]
         ([BOOL]'str_vmp))
    OF
    EITHER
      str_lqw$0
        (str_mtp$0 ><
         {str_skm$0,
          (rev
             ([FALSE,
               rec
                 (str_ahq: STRING,
                  str_ziw: FALSE,
                  str_fyh: str_dfk$0,
                  str_xvi: str_hwa,
                  str_kqn: str_blz,
                  str_pib: STRING,
                  str_ynv: str_vvl),
               (first(STRING)),
               str_ivl$0,
               str_uue])),
          INT,
          str_eks,
          str_tuz$0,
          NAT1,
          str_jhc})
    THEN
      str_fsp'str_ifp
      :=
      { str_aka, str_ppt, str_beh, str_cnx, str_evq, str_cid, str_rvq,
        str_dbo, str_yzt
        |
        !(str_ckp, str_pic, str_ktu, str_rjg, str_xps, str_xym).
        (rec
           (str_hrs: str_ypo'str_ckr, str_ihf: str_lyn$0, str_ist: str_nnj$0) <
         BOOL &
         !(str_ncl, str_vzf).(str_len : str_qlg)) }
    OR
      bool
        (rec(str_niz: str_iww$0, str_wgd: MININT) <:
         str_nus$0
           ({str_jbj$0, str_orj$0, INT, MAXINT, NAT, str_wxn$0, FALSE, MAXINT}
              ([str_qub, str_waf, FALSE, str_pux$0, MAXINT, str_mpv$0,
                str_sqq, str_lqt])))
    THEN
      str_ywv, str_wnl, str_chf
      :=
      bool
        (not
           (str_fta /<: str_fyz &
            !
              (str_vwd, str_rob, str_ezt, str_uss, str_cjh, str_ccu, str_imv,
               str_mmr, str_ykf, str_exs, str_uaw).
            (#(str_cjr, str_pga, str_eiw, str_jxv).(not(str_rgn : str_mzj$0)))))
        'str_hsz
    ELSE
      SELECT
        PI(str_kbs, str_ylw, str_zsl, str_agi).
        (str_cex /: TRUE| str_okd , MININT)
          'str_cza
          'str_vtq |>>
        {} /=
        str_zgx'str_qly
      THEN
        LET
          str_ywm, str_rqg
        BE
          str_fhm
          =
          PI
            (str_rjw, str_uqc, str_eao, str_npv, str_qaa, str_bpo, str_bvo,
             str_brl, str_ezj, str_qdt, str_uxe).
          (str_phj <<:
           { str_mvo, str_kne, str_wzn, str_vvo, str_lbi, str_mjo, str_jcp,
             str_bpf, str_fnv
             |
             not(str_bqf$0 < str_qsn$0) }|
           union
             (struct
                (str_ort: str_eik$0,
                 str_icv: STRING,
                 str_uwq:
                 rec
                   (str_xcc: str_ren$0, str_jwz: str_xuu, str_mkp: str_ewn$0))))&
          str_ohe
          =
          {str_dnt$0,
           str_qpk,
           MAXINT,
           str_tjz$0,
           str_zrw$0,
           (str_hdh(NAT)),
           STRING,
           (POW
              (rec
                 (str_xbv: str_vkx$0,
                  str_udw: BOOL,
                  str_lyk: str_ekl,
                  str_lvb: (BOOL /|\ str_iml),
                  str_egi: (str_zwv$0 , str_vdx$0),
                  str_vvu: STRING,
                  str_jtp: bool(str_axl$0 : NAT1))))}&
          str_qjy
          =
          struct
            (str_oeo: NAT1,
             str_gls: str_mce$0,
             str_lfl: str_nek,
             str_bvr: str_ser$0,
             str_qxc: str_kxe,
             str_pya: [],
             str_ccw: str_rxk$0,
             str_lta: INTEGER)
          |->
          (Pred
             ((str_llt |-> []) <<|
              [str_vrp,
               {MININT, str_gcx, str_svy, str_pig, str_ifu$0},
               str_npm,
               NATURAL,
               MININT,
               STRING]))&
          str_uir
          =
          rec
            (str_rjs: FALSE,
             str_lkx: NATURAL,
             str_xyr: (INT , str_eba$0),
             str_lii: NAT1)
          |->
          ((TRUE
            |->
            struct
              (str_zhz: str_rsd$0,
               str_wkc: str_uoa,
               str_ued: str_luc$0,
               str_zet: str_kwm$0,
               str_ozd: NATURAL,
               str_mdz: str_csi))
           |->
           {BOOL, str_olg$0, MAXINT, MININT, str_twy, TRUE, str_fww$0})&
          str_lki
          =
          ((rel((str_ixc$0 ; str_ywy))) -> (str_mmv |-> str_owv'str_oma))
            (bool(FALSE /<: str_zxq$0))&
          str_jwi
          =
          [str_kkb$0, STRING, ([] |>> str_ybx$0), (str_aus(43)), {}, []]
          |->
          (min
             ([str_hpz$0,
               str_pya,
               str_gig$0,
               ([] , str_twd),
               str_vpq$0,
               str_oyj,
               str_nye$0]))&
          str_trs
          =
          {(str_xqt$0 <-> MAXINT),
           str_zbl,
           (rec
              (str_zoq: MININT,
               str_efm: NATURAL,
               str_qsn: str_qlz,
               str_wni:
               SIGMA
                 (str_jtu, str_wny, str_xfc, str_yqg, str_ejy, str_ekd,
                  str_rbr, str_kri, str_poj, str_pku).
               (INT /= str_ksz| []),
               str_xey: str_zma$0,
               str_zod: str_lxc$0,
               str_fhu: {},
               str_asd: BOOL)
              (str_mvh$0)),
           str_tzw$0,
           str_gdv,
           (str_gsg$0 |-> str_mkg'str_hxr)}&
          str_eag
          =
          (struct
             (str_adc: str_rtv,
              str_gck: str_lju$0,
              str_ouy: (str_gdv$0(str_pur)),
              str_ycc:
              (%
                 (str_obs, str_jgy, str_xoz, str_eze, str_pnr, str_gap,
                  str_uvq).
               ([] /<: str_gbc| MININT)
                 ([str_rip, str_kbq$0, str_ind$0, INTEGER, FALSE, str_txr$0])),
              str_evo: str_bsu)
           |->
           NAT1)
          |->
          str_lvj$0
        IN
          str_lsd'str_wdk
          :=
          UNION(str_huk, str_ppw, str_zbe, str_jax).
          (str_lay /: NAT1| str_ygj$0) **
          { str_lkc, str_qyw, str_vok, str_imf, str_alt, str_qgp, str_rgg,
            str_yzb, str_hlc, str_lsn, str_bkv
            |
            not
              (str_rky$0 = str_pxq$0 &
               #(str_qdc).(#(str_amx).(TRUE /= str_xzp$0))) }
        END
      WHEN
        #
          (str_wdh, str_rgc, str_eau, str_pxd, str_bmk, str_mkn, str_oal,
           str_uhr).
        (not
           (not
              (#
                 (str_pro, str_our, str_lhz, str_eif, str_cnd, str_fsc,
                  str_rvs, str_dzy).
               (str_vti >= str_uyx <=>
                !
                  (str_gxh, str_mtv, str_anr, str_zxv, str_dfr, str_rix,
                   str_csu, str_woy, str_tki, str_jep).
                (#(str_eiv, str_mnq).(str_bgn <<: {}))))))
      THEN
        CHOICE
          str_qbk, str_wac, str_gad
          ::
          struct
            (str_chu:
             struct
               (str_uyd: str_ccp,
                str_ajw: NAT,
                str_fpg: str_zdt,
                str_npl: str_mwx,
                str_urn: MAXINT,
                str_lie: str_wqj$0,
                str_tod: str_apk),
             str_xrb: {},
             str_vhf: NAT1,
             str_koj:
             SIGMA(str_cbd, str_yoq, str_xnw, str_icj, str_wnk, str_ucc).
             (str_psh$0 /<: NAT1| str_xqa(bool(INT > str_hto$0))),
             str_qdp:
             PI
               (str_gqc, str_lis, str_kqc, str_siq, str_yze, str_amy,
                str_ttt, str_bit).
             (not([] /<: str_ehc)| str_ask$0),
             str_ghh: str_acm$0)
        OR
          str_eqj, str_dkj, str_xvb, str_yje
          :=
          [STRING,
           str_qpp,
           FALSE,
           STRING,
           [MININT,
            NAT1,
            MAXINT,
            str_ijw$0,
            { str_omw, str_nmo, str_hyh, str_vmm, str_wrc, str_qnm, str_xpn,
              str_gcr
              |
              not(str_ytp$0 <<: str_hsg$0) }
              'str_xle,
            str_lvn$0],
           struct
             (str_lyf: str_tko,
              str_nbc: str_gmx$0,
              str_cot: (iterate(str_ibw$0))),
           str_hld$0,
           BOOL]
        OR
          skip
        OR
          str_zhm, str_edu, str_irl, str_qms, str_hbn
          :=
          { str_muw, str_nja, str_ypd, str_gnj, str_dey, str_cyz, str_xvq
            |
            str_wlp /:
            [INTEGER,
             str_ujh,
             BOOL,
             struct(str_jef: FALSE, str_fda: str_mjh$0, str_jen: BOOL),
             {},
             FALSE,
             NATURAL,
             str_zkq$0]
              (str_yis$0 , str_gia$0) }
          |->
          str_lwi$0
        OR
          str_ona 
            (
              struct
                (str_pkl: bool(not(str_wrv$0 <= str_dar$0)),
                 str_bbj:
                 UNION(str_voq, str_fka, str_huh, str_bwn).
                 (#(str_uvv, str_umt, str_bto, str_cfj).(NATURAL1 > MAXINT)|
                  { str_nfu, str_ywh, str_hyz, str_wmy, str_aeu
                    |
                    str_xrd$0 : BOOL }),
                 str_sbi: str_ohk$0,
                 str_nks: str_kim,
                 str_yco: str_jnf)
            )
            (
              { str_dzn, str_wgz, str_qhx, str_kia
                |
                str_ywc /: STRING <=>
                not
                  (not
                     (#
                        (str_rvs, str_ppv, str_ftb, str_imx, str_trr,
                         str_jhr, str_gmn).
                      (struct
                         (str_sll: str_mhn,
                          str_xdd: str_azk$0,
                          str_kgl: INTEGER) <
                       str_hts$0))) }
            )
          
          :=
          rec
            (str_iyv: str_krv$0,
             str_wrv: TRUE,
             str_atv: str_vqt$0,
             str_cjk:
             (((perm(str_pqt)) >< str_yqp$0'str_fiz) -->
              { str_tcp, str_edj, str_hni, str_ojq | str_ngz$0 < 91 }),
             str_wrb: INT,
             str_gqj: str_mnv$0,
             str_azx: STRING)
        OR
          str_owc, str_scf, str_qyg, str_ukt, str_mom
          ::
          Succ
            ([{str_znf$0, str_nrw$0, {}, (subtree(str_fvq))},
              rec(str_aeu: MAXINT, str_muh: str_sgj),
              ((INTEGER >< str_syn) , str_bxo)])
        OR
          str_drt, str_ixn, str_cxe, str_eyf, str_juz, str_iic, str_lhm,
          str_mjw, str_qrq :(
            !(str_bzl, str_jtx, str_gcf, str_yjx, str_dxi).
            (#(str_eip, str_wlq, str_iwl).
             (rel
                (rec
                   (str_oal: NATURAL,
                    str_fhx: bool(INTEGER = FALSE),
                    str_syv: FALSE,
                    str_zqi: str_xfq$0)
                   'str_gll) <
              NAT1))
          )
        OR
          str_rdr, str_afw, str_kmc, str_afb
          ::
          { str_gla, str_vlb, str_ikk, str_ejv, str_ivk, str_khw, str_crz,
            str_fze, str_kcj, str_wcr
            |
            #
              (str_nlm, str_wpl, str_euk, str_ezk, str_guz, str_bev, str_jpi,
               str_wbi).
            ((str_zqc$0 < [] <=> not({} > TRUE)) =>
             not(str_nrh <= str_pzm <=> [] < str_cbn$0)) }
        END
      WHEN
        (#
           (str_emw, str_mus, str_eog, str_rkq, str_vpx, str_kyq, str_zje,
            str_dfh, str_tij, str_dhz).
         (str_gvm /<: str_zsc) or
         str_pwr <= [str_kja$0'str_vfj]) =>
        (TRUE <<: BOOL => INT = str_jib$0)
      THEN
        PRE
          not
            (#(str_jqm).
             (!
                (str_vtm, str_wlr, str_mvn, str_eim, str_gpy, str_gpq,
                 str_jyz, str_izv, str_xhk).
              (!(str_qkd, str_fdi, str_mha, str_eki, str_cfc).
               (not(str_avx$0 = str_ngn$0))) &
              NAT = str_lvf))
        THEN
          str_rqs 
            (
              (Pred
                 (rec
                    (str_ubd: NAT1,
                     str_std: (str_lfx -> str_ehn),
                     str_sjk:
                     [str_ncy$0, MAXINT, str_msq$0, str_leq$0, str_srn$0,
                      str_qpj],
                     str_wri: FALSE)))
                ({ str_psq
                   |
                   !
                     (str_egf, str_usn, str_pjb, str_cuq, str_icn, str_tvn,
                      str_you, str_cmw, str_mhu, str_eqa).
                   (str_ngw /: str_nyg) })
            )
            (
              rec
                (str_rbv: [],
                 str_nyw: (str_rjo +->> str_awz$0),
                 str_lna:
                 rec
                   (str_jxq: str_vdm$0,
                    str_kbq:
                    {str_hkf, str_ckk$0, "str_wrt", INT, {}, NATURAL1,
                     str_apn},
                    str_rrd: str_pnq,
                    str_ahs: str_kwn$0,
                    str_obe: BOOL,
                    str_eco: TRUE,
                    str_tvg: NATURAL),
                 str_fat: bool(not(str_tat$0 <: str_sxm$0)),
                 str_dyr: (id(str_ycd)),
                 str_wsf: MAXINT,
                 str_bdv: str_avk)
            )
            (
              ((str_svd$0
                |->
                bool
                  (!
                     (str_mse, str_kwa, str_bbi, str_eot, str_edh, str_pdn,
                      str_lyo).
                   (str_ibz$0 : str_pbq$0) &
                   (str_vim$0 <= str_gpc or str_eob$0 : str_foy))) -
               str_kbs)
                'str_ujw
            )
            (
              bool
                (PI(str_pvz, str_uhx). ([] <<: str_ifs$0| str_sqv$0) >=
                 bool(not(MININT /: BOOL) <=> not(str_noq$0 >= str_als$0)))
            )
            (
              { str_isi
                |
                !(str_dmd, str_gad).
                (not
                   (!
                      (str_rdm, str_epn, str_eam, str_gge, str_rme, str_uhw,
                       str_vrw, str_zbr, str_gjl).
                    (str_gud : str_pao) or
                    struct
                      (str_pyp: str_znt$0,
                       str_upl: str_jna$0,
                       str_cyl: str_jtg) /=
                    str_jby$0)) }
            )
            (
              (seq1
                 (bool
                    (#
                       (str_mry, str_aps, str_lle, str_rtt, str_gwr, str_hbx,
                        str_uij, str_rxg, str_ryq, str_bbr).
                     (not
                        (#
                           (str_ypb, str_ayr, str_byd, str_mmk, str_srx,
                            str_scp, str_ggk, str_ygo, str_hkl, str_iai).
                         (str_bwe /<: TRUE))))))
                'str_shs
            )
          
          :=
          rec
            (str_ewb: str_sul,
             str_ccx: [],
             str_eav: str_jdt,
             str_knc: str_yul$0,
             str_xut: str_nyi$0,
             str_gek:
             rec
               (str_tmp: str_hii,
                str_pna: NATURAL1,
                str_ans: (NAT1 --> NATURAL1),
                str_fvr: str_pqp,
                str_axt: str_weg,
                str_zpp: bool(str_gcz$0 /: str_jnx),
                str_bji: str_big$0),
             str_ryh: [(Succ(BOOL))],
             str_aep: {str_kxs$0})
        END ;
        str_gsn'str_wui
        :=
        {str_qsf$0,
         str_wtk,
         str_cif,
         (str_pcv(NATURAL1 /\ NATURAL)),
         str_hpw$0,
         ({str_hma, str_teg$0, str_zjn$0, NAT1, NAT1, STRING} , str_lmj)}
          'str_whx
          'str_zlq
      ELSE
        LET
          str_vmi
        BE
          str_poz
          =
          bool
            (not
               (!(str_vxo, str_lgo).
                (#(str_nil, str_tjq, str_nur, str_vil).
                 (#
                    (str_bck, str_zhh, str_hvc, str_jro, str_rtn, str_oie,
                     str_wrg, str_ejh).
                  (!(str_ayk, str_gwx, str_rqq).
                   (str_kei <: BOOL & str_iur$0 > str_lwe$0))))))&
          str_njh
          =
          PI(str_pkw, str_xwq, str_rfl, str_pev, str_foo).
          (str_mtt < str_iat$0 & [] <= str_rpz|
           seq1({(bool(TRUE /<: str_rgv$0) \|/ str_jsz)}))&
          str_dby
          =
          rec
            (str_xqo:
             PI
               (str_owx, str_rng, str_niq, str_xdi, str_ifd, str_pfm, str_ldb).
             (!(str_ftb, str_arr, str_jnu).(str_rwr$0 /<<: str_wgp)|
              rec
                (str_wzg: TRUE,
                 str_ydl: str_lxx$0,
                 str_sxu: "str_emb",
                 str_orv: NATURAL,
                 str_kmt: str_gou,
                 str_mzt: (str_was$0(str_adm)))),
             str_obh: str_odb$0,
             str_tap:
             rec
               (str_nmc: str_yeb,
                str_jmh: MAXINT,
                str_bgv: str_teh$0,
                str_gfa: str_ypj,
                str_vrm: (rev(str_xbs$0))))&
          str_pay
          =
          rec
            (str_bdi:
             (subtree(str_fcp$0 |-> (perm(max(FALSE)))))'str_wav'str_lqv,
             str_blk: str_nuf,
             str_onl: MAXINT)&
          str_epb
          =
          rec
            (str_gfs: str_qou,
             str_esp: str_amb,
             str_utn:
             ([str_oft, str_yrc, MININT, str_mvv$0]
                (STRING - str_rfd'str_vee'str_xdv)))
            'str_lmn&
          str_iqk
          =
          [NAT,
           { str_reh, str_kna, str_bbk, str_cxp
             |
             #(str_psd, str_xgw, str_xek).(FALSE <<: str_kly$0) },
           str_oqr,
           str_frp$0,
           rec
             (str_zjq: FALSE,
              str_aeh: str_lzw$0,
              str_tti: str_uja$0,
              str_mwh: str_sgn$0),
           str_qcv,
           bool(NATURAL1 <<: {} or INTEGER < str_dyx$0 or 4965 /<: MININT)]
        IN
          str_yih 
            (
              str_nan
              ,
              (conc
                 ([FALSE,
                   [],
                   str_hpc$0'str_qic,
                   str_mog$0,
                   str_bui,
                   MAXINT,
                   str_lcs,
                   str_ykb] ->
                  bool
                    (!(str_lez, str_rto, str_dac, str_dhd, str_cfr, str_vcy).
                     (str_ziw <: str_tnj))))
            )
            (
              bool
                (bool
                   (!(str_sad, str_lte, str_vwa, str_vzp, str_snk).
                    (str_hil$0 /<<: INTEGER)) <<:
                 [[PI
                     (str_fby, str_hvw, str_uaa, str_kes, str_voy, str_ldr,
                      str_pdx).
                   (BOOL : str_bqr$0| str_nlw),
                   NAT],
                  str_wbu$0])
            )
            (
              [(str_uqb$0 , str_apa$0),
               (union
                  (struct
                     (str_sdj: BOOL,
                      str_mpw: NAT,
                      str_bbs: [],
                      str_zbt: str_mov,
                      str_wgw: str_wim,
                      str_qrx: [],
                      str_bfc: str_wad,
                      str_khz: str_kds$0))),
               (str_izx$0
                  ([NAT1, str_zau, TRUE, str_iys, NATURAL, str_vvn$0, str_qyh]))]
                'str_cjf
            )
            (
              {(BOOL +->
                [STRING,
                 (str_yoh([str_yzt$0, str_oxa, str_lvo, str_eec$0, INTEGER])),
                 [],
                 rec(str_ttm: (INTEGER \/ str_ypa$0))])}
            )
            (
              {[(rec(str_chb: FALSE, str_xxw: str_bvq, str_pyc: FALSE)
                 |->
                 struct
                   (str_qlf: str_eum,
                    str_kdy: NATURAL,
                    str_fax: INTEGER,
                    str_jaq: [],
                    str_hoq: STRING,
                    str_nyf: str_cor'str_pyp)),
                NATURAL],
               rec
                 (str_olg: str_mxl$0,
                  str_khu: str_kys$0,
                  str_ptp: {},
                  str_bhi: str_fnp,
                  str_rap: INTEGER,
                  str_gmv: str_evm,
                  str_ymz: str_cgf$0,
                  str_ixh: MAXINT)}
            )
            (
              [bool
                 (!
                    (str_vmd, str_ahb, str_jmn, str_tll, str_dad, str_btf,
                     str_xun).
                  (#(str_sit, str_mxt, str_aaz, str_ojo).
                   (!
                      (str_fgr, str_gjv, str_mph, str_sal, str_jow, str_gzg,
                       str_shl, str_aal, str_zry, str_ekz).
                    (#(str_xuf, str_fnv).
                     (#(str_yqq, str_dcm, str_jwo, str_xqz).
                      (str_twh : str_zyc)))))),
               NAT,
               str_heu$0,
               str_tii,
               str_vgh,
               str_lub$0,
               NAT]
            )
            (
              struct
                (str_avm: str_eeq,
                 str_pjm: (str_gon -> str_mlk),
                 str_und:
                 %(str_jvl, str_uae).
                 (FALSE < MAXINT|
                  %(str_ryu, str_waj, str_pam, str_ybo, str_qjv).
                  (str_qrj$0 <<: str_gqk| fnc(first(str_cux$0)))))
                ~
            )
            (
              rec
                (str_kbg: ([] , str_rzp),
                 str_jxp:
                 struct
                   (str_ujv:
                    rec
                      (str_ewf: (str_nkk /\ str_gpi),
                       str_mrf: str_eys,
                       str_rgf: MAXINT,
                       str_hky: str_ktj,
                       str_mvr: str_icq$0,
                       str_apu:
                       {str_ogg, str_hqu$0, str_dms, INTEGER, str_mcp},
                       str_bzr:
                       {str_qrq, str_eir$0, STRING, MAXINT, INTEGER,
                        str_qww$0})),
                 str_jdz: NAT)
            )
          
          :=
          (infix
             (rec
                (str_lwf:
                 %
                   (str_kvg, str_mnk, str_ppm, str_edm, str_fyu, str_nnc,
                    str_ces, str_woz).
                 (str_zxx$0 = str_pzn|
                  INTER(str_pqh, str_cak, str_hox).
                  (MININT <: str_yhm| str_swt$0)),
                 str_vxg:
                 { str_qfn, str_tgl, str_glh | str_cdp$0 /<: str_jkf },
                 str_oyt: str_ivd$0,
                 str_zqf: BOOL,
                 str_dvp: {str_oqh$0, NAT, TRUE},
                 str_wnw: str_whf$0,
                 str_vay: str_vhs)))
            'str_kni
        END
      END
    END
  END;

  str_dvd
    (str_bzz, str_pgw, str_sde, str_bxn, str_mfc, str_wbz, str_wbt, str_lmd,
     str_ggj, str_twm)
  =
  ANY
    str_muf, str_bzx, str_vsw, str_ixh, str_yqf, str_avh
  WHERE
    str_jpf$0 <<: INTEGER <=>
    str_ehx$0 =
    PI(str_rnn, str_dpb, str_cvz).
    (not(str_fgz$0 /= STRING) & (str_ppd$0 < {} & str_adk < BOOL)|
     { str_rue | str_zdl > str_mfw$0 })
  THEN
    SELECT
      not
        (not
           (#
              (str_dbf, str_knk, str_ypy, str_tlc, str_jbg, str_tsw, str_ajx,
               str_mow, str_azs, str_zpi, str_uhu).
            (mirror("str_yun") /<: (MININT ; str_sbf)))) =>
      MAXINT <<: str_nmk$0
    THEN
      VAR
        str_axw
      IN
        WHILE
          #(str_eej, str_auv, str_rao, str_vob, str_fjn, str_iks).
          (!(str_sqr, str_jit, str_shy, str_gyk, str_jzk).
           (!(str_vtk, str_ims, str_gib).
            (!(str_krs, str_sbg, str_gqs, str_vpu, str_oik, str_itk, str_gjo).
             (TRUE = str_yun <=> str_rwr /<: NAT1)))) =>
          str_lxj <: str_tfx
        DO
          str_cee 
            (
              rec
                (str_gof: str_dvr,
                 str_vtx: str_zot,
                 str_ilc:
                 (INTEGER'str_lvu
                    (last
                       (fnc
                          (INTER(str_xcr, str_esd).
                           (str_bxc /<<: str_bag$0| str_yat'str_mgd))))),
                 str_pqw: str_ehk)
            )
            (
              [str_ais,
               struct
                 (str_ihr: 4,
                  str_hgj:
                  (prj1
                     (rec
                        (str_jlo: str_uab,
                         str_aud: str_irj,
                         str_luf: INT,
                         str_skp: str_tiy$0,
                         str_cgj: str_lkk,
                         str_ccg: STRING))),
                  str_tya: str_cqv$0),
               bool(str_umf$0 , STRING /= NAT)]
            )
            (
              { str_ebq, str_kte, str_pzd, str_zqp
                |
                #
                  (str_xyn, str_kdu, str_fzv, str_stf, str_cxt, str_xrd,
                   str_gkv).
                (str_hqi /= MAXINT &
                 not
                   (!(str_jew, str_zzr, str_owi, str_ymu, str_ckx).
                    ((TRUE >= str_pdj & str_qcw$0 /= str_fkz$0) or
                     str_mqd /<: str_agu))) }
            )
            (
              rec
                (str_yzx: str_kie,
                 str_qtc: INTEGER,
                 str_rro: str_mqw$0,
                 str_vvh: str_pxy,
                 str_jil:
                 rec
                   (str_sui:
                    (TRUE <->
                     struct
                       (str_mur: str_oqh,
                        str_htg: str_jaq$0,
                        str_mxp: FALSE,
                        str_pvc: str_wgn,
                        str_avo: INT,
                        str_snc: str_jbz$0,
                        str_ohf: TRUE)),
                    str_mvv:
                    struct
                      (str_epo: str_ufh$0,
                       str_tgx: str_ggv,
                       str_hep: str_iun$0,
                       str_dsb: str_uwv$0,
                       str_nne: str_cpd$0,
                       str_csd: NATURAL,
                       str_rjr: BOOL,
                       str_crv: NATURAL),
                    str_mfb: str_ccd$0),
                 str_qep: str_bfk$0,
                 str_hjp:
                 ([str_lbl$0, str_dzx$0, str_okr, str_jbs, str_jcz, str_kig$0] ->
                  str_xtz$0))
            )
          
          :=
          (INTER(str_xgq).
           (str_vrc$0 |-> BOOL <
            {str_fmg, str_tzi, str_sye, str_zyp, "str_wxi", NATURAL, BOOL,
             str_dft}|
            [str_woe, [], str_sil$0, str_tcm$0, str_qdl$0, BOOL, str_xey$0]) -->
           str_wgm$0)
            'str_doh
        INVARIANT
          not
            (not
               (INT /<: str_bqf <=>
                !
                  (str_cwf, str_vwu, str_ejy, str_jtd, str_tdn, str_idl,
                   str_gbi).
                ([] \|/ str_lxo$0 <
                 PI
                   (str_mft, str_fxv, str_lyi, str_ccf, str_mrm, str_irg,
                    str_ixy, str_nxh).
                 (FALSE = BOOL| str_dpp))))
        VARIANT
          struct
            (str_qxh: MAXINT,
             str_mcj:
             (([FALSE, NATURAL1, str_llu$0, str_wgf$0, str_eer$0, str_yke,
                str_cdq]
               |->
               str_jfu$0) <<|
              (rec(str_aje: NAT)'str_hbw <+ str_qfw$0)),
             str_cqf: [],
             str_exj: str_dof,
             str_tdt: str_zon)
        END
      END
    WHEN
      !(str_gbl, str_hcn, str_ouu).
      (!(str_qzd, str_blk, str_acl, str_xzb, str_iem, str_rqu).
       (str_edo$0 =
        FIN
          (bool
             (str_tst <<: str_dht or
              #(str_dtb, str_xyb, str_jky, str_tmb, str_sdo, str_hzs).
              (FALSE > NAT1)))))
    THEN
      CHOICE
        str_evx, str_pic, str_wyo, str_ypq, str_vxl, str_trx, str_pmx,
        str_yrj, str_dfl, str_ijy
        <--
        str_rvx
          (bool
             (str_wkq$0 : TRUE =>
              !
                (str_ysw, str_xeh, str_mul, str_gpc, str_ntd, str_euf,
                 str_kvp, str_dbu, str_mtn, str_qco).
              (!(str_uek).(str_apf <<: str_fqt$0 => str_zqu$0 < str_ywa$0) =>
               !
                 (str_yle, str_asz, str_xix, str_kfb, str_vrx, str_aco,
                  str_rcr, str_duc, str_hqq, str_not).
               (str_mqf <: str_snv))),
           ([MAXINT,
             BOOL,
             str_qfr$0,
             rec
               (str_kki: str_enj$0,
                str_gxy: str_her$0,
                str_gtz: str_jtq,
                str_tyb: str_rcl$0,
                str_ouk: NATURAL1,
                str_lgp: str_pde,
                str_xke: INTEGER,
                str_diu: str_ydb),
             str_kjx,
             str_hxx$0]
              (bool
                 (#
                    (str_kyu, str_oge, str_gda, str_vre, str_mjf, str_bdw,
                     str_adf).
                  (([] /<<: str_non$0 <=> str_xnw /: str_kjz) <=>
                   str_oij$0 <: str_yhy)))),
           (rec
              (str_aed: BOOL,
               str_mxb: str_kdv,
               str_vab: (str_hjz$0'str_nvj +-> str_nus),
               str_lso: MAXINT,
               str_ljj: str_ypy)
            ,
            (top
               (%(str_fsp, str_ilz, str_ggg, str_hts, str_vjo, str_cqe).
                (str_bmd$0 <<: str_ipx| MININT)
                  'str_tdy))),
           (str_xsr$0
            |->
            struct
              (str_pgc:
               rec
                 (str_nsd: str_uce$0,
                  str_hio: {},
                  str_hug: str_yut,
                  str_hag: INTEGER,
                  str_vmq: str_anr$0,
                  str_hsp: str_fwo,
                  str_mhd: str_wme,
                  str_rxp: "str_gma"),
               str_jwl:
               ({INTEGER, {}, str_sxc$0, NAT}
                  (rec
                     (str_aya: TRUE,
                      str_yvd: INTEGER,
                      str_wcp: str_pyg$0,
                      str_tzv: FALSE,
                      str_xqy: str_aul$0,
                      str_vqg: str_dbz'str_hcu,
                      str_bqx: str_kpk,
                      str_ptd: str_arx$0))),
               str_ttg: str_ljz))) ;
        str_sik, str_czs, str_jsj, str_hxn, str_gdo, str_eec
        <--
        str_jbz
          (bool
             (((not(str_ifr /: INT) or {} = BOOL) =>
               (MININT : str_khy$0 <=> BOOL < NAT1)) =>
              (NATURAL1 /<: str_grw$0 <=> str_ghp /= str_bdw$0)))
      OR
        skip
      OR
        skip
      OR
        str_hcv, str_wmi, str_jej, str_nwy, str_jym :(
          str_dcj >
          [({ str_zwe, str_zdq
              |
              !
                (str_kwr, str_mvv, str_usq, str_yus, str_rqc, str_uzz,
                 str_gji, str_wjy, str_hek, str_nmi, str_dhu).
              (TRUE <: str_obv$0) } /|\
            bool(str_xfy$0 <<: str_kme$0 & str_sdo = str_ofe))]
        )
      OR
        str_npg, str_kpv, str_tko, str_lyk, str_urw, str_hko
        <--
        str_ann
          ((rec
              (str_lxv:
               (struct
                  (str_uxz: str_eoe,
                   str_jrw: str_nqe$0,
                   str_ccl: INT,
                   str_vwm: str_dlg$0)
                  (rec
                     (str_ihe: FALSE,
                      str_adb: [],
                      str_wah: str_akr,
                      str_guq: str_toz,
                      str_mlo: NAT1,
                      str_hfb: str_lig))),
               str_mic: FALSE) >->>
            struct
              (str_dmv: str_ovg,
               str_wvc: str_ejm$0,
               str_lfk: str_rjp$0,
               str_wtf: NATURAL,
               str_xam: str_eqr,
               str_ezv: []'str_ptr)),
           ({rec
               (str_fez:
                rec(str_hig: str_sed, str_fsg: str_elu$0, str_qei: str_pfm$0))}
            ,
            bool(str_qog /<<: str_lgo)'str_ydu),
           bool
             (str_abu$0(str_oan) /=
              str_wgr$0
                (UNION(str_dqh, str_jsr, str_qot, str_qup, str_bjz, str_viy).
                 (str_wud$0 <: str_npk$0| bool(not(str_mcr$0 >= str_gbc))))),
           (str_pin \|/
            ((NATURAL([str_zba, str_mro$0, str_tpo$0, MININT])) *
             struct
               (str_gov: str_ysx$0,
                str_iha: str_fim$0,
                str_hke: str_okc$0,
                str_gmw: str_ylh,
                str_zoy: STRING,
                str_fql: FALSE,
                str_gmq:
                SIGMA(str_wfa, str_tep, str_qlb).
                (MAXINT > str_cmo$0|
                 SIGMA(str_lbx, str_ysk). (str_xyc$0 >= FALSE| INTEGER)),
                str_xrx: str_pnz))),
           [{str_vss,
             "str_hfm",
             str_amf$0,
             MAXINT,
             struct(str_dcz: str_iga$0, str_wtf: str_mhq),
             str_raw},
            (infix
               ({ str_cbv, str_eit, str_mlm, str_hfu, str_tak, str_cyp,
                  str_exe, str_fxh, str_art, str_xou, str_rpu
                  |
                  str_iex$0 < str_xfp$0 })),
            (str_ktn$0 |-> [str_iso$0, str_opp$0, str_hxv, str_jhd]),
            str_vgm$0,
            STRING,
            str_ibc],
           (SIGMA(str_szv, str_uxv, str_ttr).
            (str_qet /= []|
             [FALSE,
              struct
                (str_wqd: str_twb$0,
                 str_mak: str_eov,
                 str_odi: MAXINT,
                 str_shb: str_yap,
                 str_yax: str_mnp$0,
                 str_ief: STRING,
                 str_tpi: str_vmo$0),
              str_ywe,
              "str_ukc",
              str_zji$0,
              STRING,
              INTEGER] |>>
             (NAT \/ str_pls))
              (struct
                 (str_obx: str_gak$0,
                  str_rtk: NAT1,
                  str_ohk: BOOL,
                  str_zpi: str_ijf,
                  str_deq: str_sod$0,
                  str_yxl: str_pll$0,
                  str_cyb: {}))),
           { str_dxz, str_hix
             |
             not
               (#
                  (str_qmt, str_mli, str_zyy, str_zbj, str_bdf, str_vzj,
                   str_sql, str_qfr, str_unx, str_tnu, str_mfo).
                (not(#(str_irz, str_kux, str_hra).(str_adt < str_dxt))) &
                not(str_jsj$0 <: str_ful$0)) },
           SIGMA(str_qjj, str_rpq).
           (not(str_sjf$0 >= FALSE) &
            { str_vzj, str_pag, str_snu, str_wvh, str_cos, str_gla, str_eyr,
              str_voy, str_lvv, str_ftx
              |
              NAT /<: str_okr } /:
            ((MININT <| str_amk$0) || MININT)|
            str_jab$0),
           (card
              (INTER(str_sgz, str_ixi, str_jhk, str_olx).
               (str_ixd <= { str_odw, str_pgk | str_hpl$0 /: NATURAL }|
                [str_hbi$0,
                 str_gue$0,
                 str_kkm,
                 str_ick,
                 str_ubk,
                 NATURAL1,
                 (str_tls .. str_dlq)])
               |->
               str_irv)))
      OR
        str_plb 
          (
            bool
              (!
                 (str_xcw, str_cvu, str_jqe, str_njn, str_tvv, str_lvx,
                  str_xza, str_yqq).
               (not(str_izp$0 /= str_msc)) <=>
               (!
                  (str_nxn, str_kel, str_auv, str_ued, str_gly, str_kyj,
                   str_isj, str_pmu, str_zmz, str_cqf).
                (str_mcv : str_dnw) =>
                str_cyh = INT))
          )
        
        :=
        struct
          (str_ohq: FALSE,
           str_xor: str_mwv$0,
           str_inl:
           { str_nbm, str_ibz, str_jzu
             |
             #
               (str_nis, str_sng, str_irp, str_pbj, str_qvp, str_tac,
                str_tda, str_msa, str_zfn, str_znm, str_joq).
             (bool(str_inh'str_boh /<: str_zfa$0) > FALSE) },
           str_evc: BOOL,
           str_rbv: 282,
           str_dur: str_hwg,
           str_vnb: FALSE) ;
        str_bbj, str_zlt, str_rux, str_lte, str_mlj, str_yqw, str_wtl,
        str_aib, str_pqn, str_ynv
        :=
        [str_fdv$0,
         str_gwz,
         (str_qei
          |->
          [{},
           [[MININT, str_her, (str_liz /|\ str_hlq$0)],
            str_ayl$0,
            str_wgu$0,
            str_pkl$0,
            str_xec],
           str_fzy,
           str_omk$0,
           (INTEGER |-> str_hob)]),
         str_jnm$0,
         FALSE]
      END
    WHEN
      #(str_sdu, str_eou, str_eev, str_gaz).
      (!(str_bhg, str_atc, str_ekm, str_etx, str_egl, str_rxw).
       (!(str_vrp, str_fsu).
        (not
           (#(str_rta, str_aqz, str_igk).
            (not
               (!
                  (str_yma, str_ccd, str_kdi, str_dbo, str_bcw, str_qin,
                   str_qkl, str_oit, str_hhc, str_esd, str_gem).
                (INT <: str_qxh)))))))
    THEN
      skip
    WHEN
      tree
        ({ str_qup, str_djg
           |
           not
             (!(str_bne, str_upo, str_hrs, str_vxa, str_nro).
              (str_bbo /: INTEGER)) }) <<:
      %(str_wxo, str_ywk).
      (#(str_jfj, str_kli, str_qyh, str_hyb).(str_far$0 /<<: NAT1)| INT)
    THEN
      str_nkq, str_doo, str_doj, str_tyr, str_tcb, str_zca, str_etw, str_mon
      ::
      PI(str_sco, str_axz).
      (str_ixg /<:
       rec
         (str_pdn: str_voj$0,
          str_azk: str_omu,
          str_ieo: str_vam,
          str_ycr: str_dym)|
       SIGMA(str_eps, str_mhc, str_nhd, str_hkf, str_jqv, str_ouu, str_njt).
       (INT = [] => BOOL >= str_nrx| str_agn$0(str_vzu$0)))
    WHEN
      !
        (str_tky, str_alz, str_efq, str_fog, str_yzh, str_wmn, str_kjb,
         str_hdj).
      (struct
         (str_kdl:
          { str_jjf, str_asc, str_mfn, str_rcn, str_qyd, str_vbu, str_xnr
            |
            str_jbt$0 /<<: str_mez },
          str_hvn: INTEGER,
          str_net: str_low$0,
          str_zvx: 0)
         'str_rwy /<<:
       struct
         (str_fzl: BOOL,
          str_hhd:
          struct
            (str_qub: NATURAL,
             str_fpx: MININT,
             str_lgf: str_ugf,
             str_wme: NAT,
             str_mra: str_mbu,
             str_vym: str_jwk)))
    THEN
      str_xij, str_dqd, str_upa, str_aij, str_ucw, str_pve, str_vqt, str_wdy
      <--
      str_vnt
        (((prj1({ str_axu, str_oii, str_rob, str_hdi | INT /<: str_lgt$0 }))
            ([(struct
                 (str_tgm: [NATURAL, str_gqh, MININT, str_fyi$0, str_tva$0]) |>
               str_bdh$0),
              str_xml$0])),
         struct
           (str_vwy:
            SIGMA(str_lfb, str_kwj, str_lao).
            (not(!(str_bus, str_dub).(NAT < [str_zcn$0]))|
             rec
               (str_imc: str_kfk,
                str_ehc: str_sbz,
                str_yxt: str_hfh,
                str_hol: str_wto$0))),
         struct
           (str_nts: {},
            str_gnk: {str_zth$0'str_bog, str_bnt, str_vbb},
            str_dfu:
            {str_ihy,
             [],
             [str_mwq, str_jxn, str_xal$0, str_ezc$0, "str_ybx"],
             BOOL,
             NATURAL},
            str_aks: TRUE,
            str_qeg:
            UNION(str_ueo, str_onl, str_jyw, str_pjm, str_yyj, str_bvc).
            (str_lzr$0 /: str_tie$0| bool(MAXINT /: str_yia$0))),
         [MININT,
          str_jap,
          str_vbe$0,
          str_xyz$0,
          NATURAL,
          [NATURAL1, (str_kjc$0 * NAT1), str_tmz]'str_eqa,
          str_lpe,
          ((card(str_uby$0)) >+>
           [str_wcb$0, str_age, str_tzd$0, str_trx$0, STRING, str_exq,
            str_xfr$0, MININT])],
         (Pred
            ({str_bos,
              str_cjy,
              (str_opw$0 - (str_zdk , BOOL)),
              str_fyc$0,
              (min
                 ([str_gjj$0,
                   str_dwc$0,
                   str_uav,
                   str_nrb,
                   str_pqx'str_ojd,
                   str_vaz$0]))})),
         UNION
           (str_ufx, str_kdt, str_xuo, str_rlx, str_gop, str_qfg, str_kfk,
            str_yjs, str_jqq, str_kmt, str_rmn).
         (not
            (#(str_vbo, str_yob, str_ggc, str_hpz, str_hnn, str_zho, str_hfm).
             (!(str_fpv, str_ilu, str_edi, str_scr, str_wsb).
              (str_ebr /<<: INT , str_gkr)))|
          UNION(str_bsm). (str_zjb < {}| INTEGER)),
         struct
           (str_xnz:
            { str_yvo, str_lqe, str_hiy, str_vml, str_ile, str_myy, str_yga,
              str_ihz, str_bzr, str_cev, str_urk
              |
              str_smn <:
              { str_cju, str_dvq, str_osr, str_anz, str_fuu, str_axb, str_qzr
                |
                !
                  (str_fdh, str_voe, str_mru, str_cfp, str_ika, str_dpt,
                   str_xci, str_wig).
                (str_dig /: INTEGER) } },
            str_qpc: (iseq1(str_xkb$0)),
            str_dcp: str_hcl$0,
            str_bbg: str_vjk,
            str_ugm: str_vmr,
            str_aka: NATURAL))
    ELSE
      skip
    END
  END;

  str_zqt, str_lwf, str_iyu, str_enr, str_hus, str_vsq
  <--
  str_yxf (str_lhs, str_wdq, str_csv, str_ftx, str_auf, str_cru)
  =
  WHILE
    !(str_jux, str_pvz, str_tek).
    (not
       (not(not(!(str_zqc, str_jse).(str_ayj$0 = MININT))) or
        !
          (str_fqw, str_zkc, str_yma, str_ish, str_xes, str_uvq, str_xeh,
           str_yxq, str_akq, str_ely).
        ([] : {})))
  DO
    ANY
      str_aop, str_www, str_yjt, str_ebz, str_qkf, str_nrg, str_zgp, str_akv,
      str_lps, str_psf, str_yub
    WHERE
      !(str_jez).
      (!
         (str_ruj, str_kcd, str_vuw, str_zim, str_iqx, str_edi, str_buj,
          str_feb, str_xpg, str_nsu, str_aeq).
       (#(str_leu, str_gvg, str_ryd, str_xxb).
        (not
           (str_rlk <<:
            { str_dlc, str_jpd, str_fla, str_css
              |
              str_jyh$0 <: str_rpa & str_lkq /<<: str_kzg$0 }))))
    THEN
      VAR
        str_opt, str_lee, str_lea, str_fbj, str_oaq, str_eri, str_avc
      IN
        SELECT
          { str_app, str_zyk, str_amx
            |
            !(str_ocf, str_xtz, str_ndw).(str_ctd$0 > NATURAL) } =
          bool
            (not
               (#(str_lwh, str_uvd, str_vgw, str_yap, str_zxe).
                (#(str_hsn, str_xdr).(str_gsu < TRUE))))
        THEN
          VAR
            str_ggm, str_qdu, str_dpv
          IN
            str_mqn, str_fdw, str_kkd, str_pvd, str_wub, str_kpo, str_qtw,
            str_jng
            ::
            SIGMA
              (str_ujp, str_ymu, str_szo, str_xpg, str_cnb, str_qnd, str_ucm,
               str_vym, str_bbu, str_yus, str_hbg).
            (MAXINT <<: str_zrw$0|
             { str_lvh
               |
               !(str_qhw, str_yds, str_yos, str_rix).
               (not(str_rvr$0 /= INT) =>
                (str_fpq > str_fsi =>
                 !
                   (str_ltt, str_bzt, str_vvm, str_bce, str_qox, str_nhp,
                    str_ozb, str_qzg, str_git).
                 (NATURAL <= FALSE))) })
          END
        WHEN
          not
            (!(str_lce, str_cbx, str_lrb, str_kjg, str_wxf, str_egm, str_nfr).
             (#
                (str_wez, str_qkq, str_lzm, str_gtg, str_zyu, str_yzk,
                 str_uze, str_cti, str_qps).
              (#(str_ays, str_csf, str_kwc, str_nzw, str_atq).
               (!(str_kwl, str_tam, str_jai, str_tqh, str_ilj, str_zlg).
                (#(str_svy, str_laa, str_jai, str_bwy, str_htv).
                 (not(NAT1 <= str_zun$0)))))))
        THEN
          str_rtf, str_jap, str_suy :(
            ((!
                (str_fem, str_knu, str_lko, str_mrp, str_nox, str_kri,
                 str_ahg, str_xma).
              (str_fhy /<: str_qcz &
               !
                 (str_bqd, str_wnn, str_mbj, str_dst, str_obb, str_zac,
                  str_juc, str_iss, str_dje).
               (TRUE < str_klx)) &
              str_wax <: str_ywa$0) <=>
             (STRING : str_jwm & str_ffh >= NATURAL)) =>
            str_orq /<: NATURAL
          )
        WHEN
          not
            (#(str_nds, str_ayz, str_vom, str_uyh, str_qvb, str_cwl).
             (str_tdn /: NAT & str_jip < str_dll) or
             !(str_zft, str_ktv, str_rjo).
             (#
                (str_rxp, str_fkq, str_njp, str_nzy, str_czo, str_ram,
                 str_sjv, str_wyp, str_ibx, str_yww, str_ywv).
              (#
                 (str_vxr, str_glj, str_nrv, str_ecy, str_mgj, str_bys,
                  str_hra, str_hnv, str_eaz, str_rfl).
               (str_mpn$0 > str_bez))))
        THEN
          CASE
            {MININT,
             str_zrl,
             TRUE,
             struct
               (str_ofv:
                rec
                  (str_oei: (btree(str_mss /\ (str_sit$0 , (sons(str_jox)))))),
                str_ksj: str_psn),
             str_ojl}
            OF
            EITHER
              { str_faf, str_nsq, str_edh, str_idm, str_pij, str_hxz, str_auo
                |
                not(str_dof$0 <: str_rkq) <=>
                !(str_vlx, str_ehn, str_bop).
                (str_kzy <<: str_cxf >-> str_hze$0) }
            THEN
              str_zzg <-- str_mjy
            OR
              bool
                (#(str_lkn, str_ren, str_puq, str_fts, str_oea).
                 (FALSE = str_ksl$0 => MAXINT /<: 9) &
                 str_kfj$0 <<:
                 [{str_yqd$0, str_vgf, str_qbb, TRUE, str_gsc, str_eib$0,
                   STRING, str_czz}])
            THEN
              str_ogk, str_srr
              :=
              [struct
                 (str_mrr: str_kos,
                  str_agw: TRUE,
                  str_sav: str_phv,
                  str_wmg: STRING,
                  str_kxv: str_zrw,
                  str_pfu: str_rzx,
                  str_njf: NATURAL1)
                 'str_gsu,
               bool(!(str_hlr, str_xpu, str_dkp).(str_wzq <: str_vww)),
               UNION(str_fhg). (str_kms$0 /<<: NAT| str_cyi$0)]
            END
          END
        ELSE
          str_cdf
          <--
          str_txo
            (([[FALSE,
                str_nvq,
                ({ str_sbo, str_xwj, str_nfj, str_clt | str_pun$0 : str_nmp }
                   (NAT))],
               "str_wil",
               str_ahy$0,
               FALSE,
               (PI
                  (str_elu, str_fjm, str_ruv, str_awk, str_alq, str_ylc,
                   str_amg, str_ewb, str_ykn, str_ovz, str_ujs).
                (str_zya$0 <= str_ktw| TRUE)
                  (TRUE)),
               NAT,
               str_wxm$0]
              |->
              NAT),
             ((TRUE(str_exu))
                (rec
                   (str_zae:
                    UNION
                      (str_nrl, str_eiq, str_esl, str_frs, str_hnu, str_dww,
                       str_sdj, str_exb, str_vsg, str_xhr).
                    (NATURAL1 /<: str_cbx$0|
                     SIGMA(str_qzm, str_mqp, str_yot, str_txy).
                     (str_ixp <<: INTEGER| bool(TRUE /<: str_vsp$0))),
                    str_wzv: (str_xqo$0(str_uaz$0))))),
             struct
               (str_fgf: ({}(str_fhw +->> str_hqs)),
                str_hky:
                UNION(str_fal, str_avx, str_yeh).
                ({} = str_qxm$0|
                 [str_pts,
                  rec(str_pdo: str_edl, str_jdo: str_kth),
                  {},
                  TRUE,
                  str_nvi]),
                str_jsk: str_ttr,
                str_yun: (front(str_gul))),
             rec
               (str_uex: str_ofi$0,
                str_skh:
                UNION(str_iwr, str_ekq, str_nsr, str_jne, str_crg, str_kdz).
                (str_mtq < STRING| str_iwh$0),
                str_pdx: str_hyh$0,
                str_edc:
                ({ str_fsq, str_fny, str_fka | str_yli$0 <= NATURAL1 }
                   (str_lgu$0)),
                str_frs: [],
                str_ryn: str_otg$0,
                str_klr:
                (FALSE /
                 { str_ahl, str_vlj, str_ijz, str_kbg, str_ztj, str_ofp,
                   str_lpo
                   |
                   TRUE <: str_kyg$0 })),
             (iseq1
                ((str_zom ..
                  {INTEGER,
                   str_haa,
                   str_mkv$0,
                   str_uft$0,
                   [FALSE,
                    STRING,
                    (TRUE , str_wcv),
                    str_fnq$0,
                    str_iem$0,
                    str_hzg,
                    str_erk$0],
                   str_vjf,
                   (inter(str_jvf$0))}) \/
                 TRUE)),
             (rec
                (str_cmf:
                 rec
                   (str_eou: str_owe,
                    str_tch: str_nrr$0,
                    str_psw: str_fwt$0,
                    str_hir: str_lwu$0,
                    str_ybo: {str_ogo, str_zcr, NATURAL1},
                    str_icg: str_whu$0,
                    str_krj: STRING,
                    str_vdi: str_frw),
                 str_dnh: [],
                 str_oif: {str_oua})
                ({ str_sot, str_xuq, str_jzb, str_hgu, str_bkf, str_kwz,
                   str_tbq, str_zgp, str_vox
                   |
                   NATURAL1 >= str_jjr => str_lxu > str_vfq })),
             {FALSE,
              str_wzu,
              (MININT , (INTEGER <<| (INT |-> FALSE)'str_rux'str_wej)),
              NATURAL1,
              str_tml$0,
              []}
               'str_kqm,
             SIGMA
               (str_knm, str_awf, str_xcl, str_wzi, str_lds, str_svu,
                str_xrt, str_jnp, str_nem).
             (#
                (str_jeg, str_hlu, str_lov, str_zgo, str_nzf, str_wgd,
                 str_ozy, str_zdn, str_czh).
              (#
                 (str_dbo, str_yrp, str_hvz, str_zxk, str_rfr, str_yal,
                  str_lrc).
               (str_zgh$0 , str_ahr : str_vtr$0))|
              [str_ugt,
               str_huu$0,
               rec
                 (str_pbc: MININT,
                  str_rnm: str_lvo$0,
                  str_rmk: str_wnl,
                  str_loa: NAT1,
                  str_nue: str_iel$0),
               str_aga$0,
               str_yfu]))
        END ||
        str_xnj
          ({(PI(str_vzl, str_ost, str_vlh, str_lza, str_hen, str_heo).
             (INTEGER /: str_lvm|
              [str_qpi, str_rqa$0, str_qcu, str_hfb$0, NATURAL, str_cpk,
               str_ynt, str_dat$0]) <<|
             (seq1(infix(str_bkp$0)))'str_gvk)},
           (PI(str_duz, str_neb, str_sod, str_ykp).
            (STRING <<: str_tbz$0| str_xnd)
              (max
                 (((str_ylf$0 <- str_ciy$0) , str_usy)
                    (bool(MAXINT <<: str_ydb))))),
           {rec
              (str_acn: NAT1,
               str_ldt: str_dsn$0,
               str_liw: str_pgz$0,
               str_nhm: str_fue$0,
               str_jpx: str_wnn$0,
               str_tik: str_qoz,
               str_yuj: str_lzy,
               str_ehm: str_myx),
            [{struct(str_smp: (str_qwm$0(str_sci$0)), str_rsh: str_qth$0)},
             str_vor$0,
             rec
               (str_utq: INTEGER,
                str_ryt: INTEGER,
                str_ldq: INTEGER,
                str_zkx: []),
             str_oyg$0]},
           ((struct
               (str_itq: str_hch,
                str_ovp: str_kwd$0,
                str_rlm: FALSE,
                str_liu: str_mdm,
                str_jtu: INTEGER)
             |->
             (str_wvx(str_zlo$0)))
              'str_yay
              ({ str_uyt, str_lfh, str_lxl, str_ove, str_vbn, str_kip,
                 str_gbo
                 |
                 str_ruy$0 /<<: NAT1 }
                 'str_lwv)),
           {str_efj,
            %
              (str_olv, str_kwk, str_amx, str_gao, str_lij, str_awn, str_kfy,
               str_pzm, str_wfo, str_ljc, str_uil).
            ((bin("str_vau")) |-> MAXINT > str_nnn(str_mjv$0)|
             {str_udm, str_sui, str_cqx, {}, BOOL}),
            str_xdv,
            NAT1},
           ((str_xaf /\ [str_zdy'str_oid, str_pbo, INTEGER, NAT1])'str_efh
              'str_ltu
            ,
            (str_vjr$0 |-> str_tfn)),
           [STRING,
            STRING,
            [],
            TRUE,
            rec
              (str_lgz:
               UNION
                 (str_kkf, str_mcm, str_egt, str_tio, str_iqe, str_nyv,
                  str_det, str_wol).
               (#(str_zns, str_llk, str_udb).(not(INT /<: INT))|
                (str_xjw$0 .. str_sgq) |-> INT)),
            str_mhu,
            str_dvm,
            TRUE],
           struct
             (str_zap: (INTEGER([])),
              str_txr: INT,
              str_tku: str_hlr$0,
              str_fhv: MAXINT,
              str_onw: str_mmt,
              str_yut:
              struct
                (str_owq:
                 rec
                   (str_owz:
                    {(prj1(INTEGER)),
                     str_ysl,
                     str_xty$0,
                     str_pvl,
                     MAXINT,
                     MININT,
                     str_zmc$0},
                    str_sat:
                    UNION(str_irn, str_ktt, str_arf, str_uws, str_fzu).
                    (NAT1 <: str_jfm| TRUE),
                    str_wxp: str_zbr$0,
                    str_qgq: [],
                    str_ihs: INT,
                    str_ysu: str_mew,
                    str_jyg: [],
                    str_ijg: str_yac$0),
                 str_uof: str_slq,
                 str_fng: [],
                 str_ayx: str_zkm,
                 str_iyr: str_yms),
              str_jnc: str_fdu),
           rec
             (str_rer: str_jdb$0,
              str_vmw:
              (str_aha
               |->
               INTER(str_ccw).
               (#(str_lhs).(TRUE <= str_aqf$0)|
                {FALSE,
                 STRING,
                 {NATURAL1, str_chl$0, str_mnm, str_khg$0, STRING},
                 str_dad}
                  'str_bmh))),
           [(struct(str_avn: str_nda$0, str_cdq: str_npl$0, str_chm: TRUE)
               ([(str_cuk(str_fgm$0)), (str_ldu ^ str_wsq$0)]))
              'str_crw])
      END
    END
  INVARIANT
    !(str_ani, str_klr, str_aaw, str_csw, str_udy, str_vvy, str_jrt, str_vpm).
    (not
       (#
          (str_lfe, str_goo, str_wmh, str_fcf, str_cdl, str_sph, str_xnx,
           str_edk, str_brb, str_ifu, str_npn).
        (#
           (str_nwe, str_bbf, str_rwt, str_kgk, str_oru, str_nwk, str_hob,
            str_bag).
         (#(str_xoy).
          (#(str_gzc, str_rnu, str_uau, str_frv, str_dge, str_brh).
           (!
              (str_bqu, str_djd, str_wdg, str_sbe, str_zke, str_nhi, str_ffd,
               str_zak, str_nku, str_rwb).
            (str_ctq$0 > str_zom)))))))
  VARIANT
    (STRING(str_vwq))
      (bool
         (str_ylq$0 /<:
          rec
            (str_exi: BOOL,
             str_obr: "str_opd",
             str_hly: [],
             str_gdc: NAT,
             str_ebn: MININT) >+>
          struct
            (str_dzf: BOOL,
             str_flt: TRUE,
             str_mhh: str_ygl$0,
             str_ndv: str_gzm,
             str_adl: str_edb)))
  END;

  str_whz, str_wjz, str_jsk, str_dos
  <--
  str_gnw (str_mzx, str_wnl, str_cyd, str_son, str_rds, str_fvh, str_owl)
  =
  ANY
    str_nul, str_yyu, str_aem, str_jtk, str_azs, str_cdk, str_kuv
  WHERE
    str_tco > str_rgu$0 &
    not
      (mirror
         ((seq(str_qif$0)) +
          { str_ryq, str_zye, str_gke, str_ctd, str_shp | [] /= BOOL }) >=
       [])
  THEN
    CASE
      UNION
        (str_ncv, str_kuc, str_zpd, str_nox, str_nlg, str_nue, str_xuk,
         str_gze, str_krv, str_xwj).
      (not
         (str_efe$0 > str_tol$0 &
          !
            (str_xif, str_wra, str_ler, str_imu, str_geh, str_mxb, str_lgi,
             str_cfr).
          (str_voz$0 /: str_qkr))|
       bool
         (#
            (str_oub, str_yqo, str_liy, str_peq, str_agq, str_lpj, str_oyw,
             str_jpi, str_dtj, str_wrs, str_ait).
          (not(STRING < 3))))
      OF
      EITHER
        { str_rsl, str_uyi, str_tgf, str_vie
          |
          not
            (not
               (!
                  (str_kdl, str_fnv, str_hzs, str_nor, str_xby, str_ung,
                   str_zbf, str_vqp, str_sbj).
                (str_euo$0 /<: str_vqo &
                 #(str_bfi, str_lxw, str_cgj, str_lgx).(str_ciq <: str_lmu$0)) &
                str_alf$0 /<<: str_xhn$0)) }
      THEN
        WHILE
          !
            (str_qfq, str_ots, str_duj, str_ugm, str_efz, str_dnj, str_mbm,
             str_xrk, str_mks, str_nzg, str_qdo).
          (((str_mok$0 || str_dnz)) , str_jfh$0'str_rsa /<<:
           struct
             (str_jgl:
              INTER(str_ubq, str_mfi, str_fmp, str_fqv, str_ldg).
              (BOOL > str_vlu$0| str_rfb$0),
              str_clb: str_hta))
        DO
          VAR
            str_qgj, str_qpp, str_uph, str_jei, str_dno
          IN
            str_qpd'str_zvh
            :=
            bool
              (not
                 (str_zef$0 <<:
                  {(str_hmv([str_rlr])),
                   MAXINT,
                   str_pfz$0,
                   (rev([])),
                   str_lua$0,
                   INTEGER}))
          END
        INVARIANT
          str_jlg : str_xdj =>
          !
            (str_gdp, str_swv, str_feh, str_ppl, str_szd, str_hjx, str_dbi,
             str_obu, str_oyk, str_txr, str_mzf).
          ((str_xks$0 |-> str_ajt$0)(str_mup$0) <:
           {str_zew,
            str_tvt,
            BOOL,
            MININT,
            str_sno,
            str_uos,
            str_ees,
            ([][str_jcc])})
        VARIANT
          PI
            (str_loa, str_kdg, str_cpq, str_dmh, str_jxl, str_hcc, str_sau,
             str_wju, str_wrh, str_rnf).
          (#(str_kku, str_rsj, str_mej, str_awf, str_vky, str_rus).
           (#(str_kcv, str_dqd).
            (#
               (str_qrp, str_xno, str_puc, str_hqv, str_qyw, str_eam,
                str_gvv, str_ojk).
             (not(str_evv$0 <<: str_tch$0))))|
           %(str_sbq, str_zum, str_ojn, str_zkq, str_ney, str_fug).
           (BOOL >= str_ejh$0| str_hrm))
        END
      OR
        ran
          (rec
             (str_wzt: str_ygr,
              str_mlp: (INTEGER(STRING)),
              str_and:
              [str_dcf$0,
               TRUE,
               { str_tkn, str_dnm, str_uai | str_ndi$0 <: str_acj },
               str_txt$0,
               str_bjj$0,
               str_kjv,
               FALSE,
               str_vtv]
                'str_lhe,
              str_zlq: str_cmb$0,
              str_lcm: (union(str_ish$0))))
      THEN
        str_dbg, str_gfq, str_sfy, str_hiv, str_ijh, str_epx, str_ztp,
        str_gyc, str_rlp :(
          mirror
            ({"str_eat",
              {str_ubu, str_eew$0, str_ncm, str_dsk$0, str_iep$0, [],
               str_usk$0},
              str_jnk,
              str_dcv$0}) <<:
          INTER(str_phf, str_fhb, str_rhf, str_ayp, str_gvl).
          (str_xdc = [] => INT <<: str_ztt| str_wtu$0)
        )
      OR
        (str_tqq$0
           (rec
              (str_dtn: NAT,
               str_ceb:
               (prj1
                  ({ str_tgy, str_ydn, str_jgu, str_ggq, str_skb, str_qvk,
                     str_zxq, str_okp
                     |
                     str_ciz$0 : str_qjs$0 })),
               str_nbq: str_jhj$0,
               str_dkv: str_drj$0)
              (str_fau , MAXINT)))
          'str_nci
      THEN
        str_kwx, str_dir, str_vqe, str_gxp, str_szf, str_uxs, str_qyk,
        str_otk
        :=
        bool
          (not
             (struct
                (str_qlb: (FIN(str_piy)),
                 str_dcs: NATURAL,
                 str_nuf: (sizet("str_pem"))) <<:
              STRING(str_lti$0)))
      OR
        [str_yxe,
         {{str_rns,
           str_szv$0,
           str_nuf$0,
           ({str_hqr$0,
             str_jup,
             str_ucr,
             str_rgw$0,
             str_bzp$0,
             (sons(str_gwk$0)),
             str_ssb$0,
             str_bob$0} >->>
            rec(str_uyb: str_ddg$0)),
           NAT,
           str_mpn$0,
           str_kzr},
          MAXINT,
          INT,
          STRING,
          str_fph,
          [],
          NAT}]
      THEN
        str_nkc, str_xxb, str_ukm, str_snl, str_hqa, str_tum, str_ger,
        str_ekz, str_opq, str_vxb
        <--
        str_mxk
          ((%
              (str_cey, str_opx, str_wal, str_xpp, str_zey, str_ugf, str_efi,
               str_dqk).
            (str_vgc$0 <<: str_dxy$0| str_qme$0)
            ,
            ({ str_qte, str_blf | str_hub <: [] } -->
             rec
               (str_jts: (NAT(NATURAL1)),
                str_njz: str_odo,
                str_rmw: FALSE,
                str_owb: [],
                str_zya:
                [str_kte$0, str_sij, [], "str_ath", str_ozz$0, str_ars$0,
                 str_ysl$0],
                str_cpx: str_ufz))),
           SIGMA
             (str_qmn, str_ckq, str_atb, str_mvi, str_dms, str_nvv, str_ecv,
              str_zyi, str_uqm, str_cxc, str_qqi).
           (struct
              (str_vzw: NAT,
               str_anm: FALSE,
               str_wms: rec(str_twj: {}, str_oaj: str_hku, str_bgi: INT),
               str_uvv: str_zse,
               str_nmj: str_ere,
               str_khq: MININT,
               str_zlh: str_tep$0,
               str_kdw: str_hec$0) >
            rec
              (str_flx: MININT,
               str_nls: str_hzd,
               str_lle: INT,
               str_pob: SIGMA(str_kkf). (INTEGER /<: []| str_flh),
               str_bvu: [],
               str_toc: str_mct$0)|
            [TRUE, str_qkf, str_ueu$0, str_rxt$0, NATURAL1, str_euv]),
           (iseq
              (UNION(str_cah, str_cci).
               (not
                  (!
                     (str_kuq, str_hyi, str_avd, str_zeu, str_qgt, str_hrp,
                      str_izu, str_uun, str_ypb).
                   (str_qpp /<: str_ird))|
                { str_wfm, str_hrb, str_fmg, str_oox, str_vfa, str_zvt
                  |
                  str_kpz$0 = str_cym$0 })
                 [{str_wuh, BOOL, str_tvz, str_qoz, NAT1, MININT, str_top}])),
           (FALSE +
            { str_eyj, str_qwk, str_gsl, str_upk, str_dqt, str_tsw, str_bph,
              str_gwl, str_fog, str_myb
              |
              !
                (str_qwg, str_jyw, str_fys, str_eax, str_qeq, str_sqc,
                 str_upb, str_xml, str_gyu, str_hdy, str_gao).
              (not
                 (STRING <=
                  rec
                    (str_vju: str_pmp$0,
                     str_tha: str_zby$0,
                     str_fhg: NAT1,
                     str_eua: str_iir,
                     str_pso: str_xnw$0,
                     str_iqt: str_vqx,
                     str_rmg:
                     struct
                       (str_apq: NAT,
                        str_ddx: str_zxt,
                        str_cya: str_yrp,
                        str_kgd: str_ycr,
                        str_nzz: NAT1),
                     str_gxi: FALSE))) }),
           ({str_haj, MAXINT, str_uph$0, str_vbo, NATURAL, str_skw}
            ,
            (str_wui$0
               (struct
                  (str_sop: bool(not(str_llg$0 < str_woj)),
                   str_gre: (BOOL(str_grd)))))),
           [MAXINT,
            struct
              (str_tok:
               struct
                 (str_wai:
                  rec
                    (str_gdy: BOOL,
                     str_xok: str_nmr$0,
                     str_fnf: BOOL,
                     str_hpv: FALSE,
                     str_cpy: str_gjn$0),
                  str_cvw: (closure(BOOL)),
                  str_oud:
                  UNION(str_qsw, str_pvj, str_weg, str_pqc, str_mgj, str_cwh).
                  (str_use$0 : BOOL| str_vzu$0)),
               str_hxm: TRUE,
               str_ztx:
               rec
                 (str_xvb: str_kzz,
                  str_pxz: "str_olc",
                  str_pll: str_xdk,
                  str_eyl: str_mjh$0,
                  str_sqm: str_aec$0,
                  str_rjg: str_icd$0)),
            MININT,
            str_nby,
            str_uec$0,
            MAXINT],
           INTER
             (str_ucs, str_ixt, str_dlr, str_vql, str_hbk, str_gwn, str_hyn,
              str_ybq, str_qcf, str_mbf).
           ((str_qpn$0 > str_woy & BOOL > MAXINT) or
            (str_zpr < str_ovv <=> ({} <: str_jwp or str_isb$0 <: str_xwv$0))|
            [str_yiw, NATURAL1]'str_jhw),
           (INTER(str_uer, str_iap, str_zzb, str_una).
            (NATURAL1 : 1|
             [UNION(str_gxw, str_txw, str_sqc, str_oja).
              (str_iep : NAT1| str_pqr),
              str_tqs,
              { str_jui
                |
                #(str_low, str_vat).
                (#(str_txu, str_svv, str_kkp, str_wru).
                 (NATURAL /<<: str_dja$0)) }])
              (str_jec$0)),
           (((rel({})) ;
             %(str_pcv, str_jic, str_ljy, str_ifc).
             (str_exd$0 <<: str_yzb$0|
              [[str_yyg, str_wpr, FALSE, str_haz, str_flt, str_xgh$0], []]
                'str_ygb)))
             'str_fjo,
           (bool
              (!(str_ezc).(INTEGER /\ str_emi : rec(str_ssn: MAXINT'str_dca)))
              ~))
      OR
        UNION(str_yso, str_bns, str_exi, str_ath, str_pgi, str_txs).
        (!
           (str_dbd, str_osl, str_mnb, str_pmx, str_lzc, str_izf, str_aok,
            str_exu, str_spp, str_dwe, str_lve).
         (!
            (str_hgq, str_kux, str_nzl, str_vfg, str_wyr, str_xdb, str_fky,
             str_puo, str_dlf).
          (str_rsj > INT))|
         struct
           (str_rgo: str_cew$0,
            str_ucj: str_oan,
            str_vps:
            struct
              (str_enx: str_sgn$0,
               str_rce: str_ait,
               str_afd: struct(str_vij: NAT1, str_gjo: str_qhk, str_tot: [])),
            str_opl: str_uls))
      THEN
        IF
          not
            (str_hhw >=
             [BOOL,
              (str_tle$0 , {}),
              MAXINT,
              str_wmt,
              struct
                (str_eho: str_qsh,
                 str_rij: str_khf,
                 str_nab: str_zir,
                 str_kct: str_rkq$0,
                 str_kvf:
                 rec
                   (str_epy: INT,
                    str_hrg: str_eha$0,
                    str_ind: str_ith$0,
                    str_ukf:
                    { str_gww, str_opz, str_gih, str_ozn, str_bgm, str_fes,
                      str_hsb
                      |
                      NAT <= {} },
                    str_qvq: str_yus$0,
                    str_pcs: NAT1,
                    str_myf: str_xkh),
                 str_bsj: BOOL),
              INTEGER])
        THEN
          ANY
            str_kbx, str_mbf, str_xrb, str_szq, str_lhe
          WHERE
            #(str_njv, str_vke, str_qvt, str_lda).
            (!
               (str_imu, str_rlv, str_osi, str_oen, str_pfu, str_cen,
                str_luu, str_wqv, str_ikt, str_lqq).
             (!(str_afh, str_roi, str_jdz).
              (MININT <
               UNION(str_vee, str_tzu, str_jyf, str_sma, str_nnb).
               (str_aaz > TRUE|
                bool(str_usw /= FALSE & str_ess$0 <<: str_rgu)))))
          THEN
            str_bvf, str_ize, str_rhf
            :=
            [{str_wai$0, 7, NAT, 7},
             rec
               (str_xps: (str_dsg$0'str_uno~),
                str_wmb:
                { str_fde, str_cqf, str_vco, str_xcr, str_lia, str_jcz,
                  str_shw, str_olo
                  |
                  !(str_zbe).(str_cqh$0 /= str_gjk$0) },
                str_pks: INTEGER)] ||
            str_mkw, str_saf, str_mab, str_vwk, str_oaf, str_aer, str_uju,
            str_lon, str_uph :(
              !
                (str_oyq, str_cvj, str_vqx, str_jiz, str_opc, str_rhm,
                 str_det, str_exg, str_hcz, str_sql).
              (not
                 (#
                    (str_aap, str_mps, str_xmu, str_pdv, str_tpr, str_yxp,
                     str_eeu, str_pdo, str_dkg, str_lpl).
                  ({ str_wvl, str_haf
                     |
                     !(str_jpo, str_lkm, str_xtf).(str_egl /<<: str_ppc$0) } /<:
                   seq(str_mka))))
            )
          END
        END
      ELSE
        str_dyf'str_giu
        :=
        { str_sue, str_wul, str_gcr, str_jdk, str_gat, str_qpv
          |
          #(str_vdn, str_ilw, str_egn, str_pya, str_lgk, str_ybh).
          (not
             (!(str_bzu, str_rlv, str_bdp, str_ctq, str_oxd).
              (!(str_yaz).
               (#
                  (str_nar, str_vzl, str_zpd, str_iou, str_rlu, str_auc,
                   str_svi).
                (BOOL <: []))) &
              str_kbk /: MAXINT)) }
      END
    END
  END

INITIALISATION
  PRE
    !
      (str_ijc, str_afl, str_wuu, str_quv, str_mou, str_ost, str_lyk,
       str_avz, str_gou).
    (!(str_ffe, str_fne, str_yxq, str_ocs, str_egu, str_nln, str_lae).
     ({} /= NAT1) =>
     {{[], str_ovv, (right(str_nkc))}} < str_qlf$0)
  THEN
    IF
      MININT /<:
      [bool(bool(str_tcs$0 /<: str_ldx$0) = str_dbr$0),
       NATURAL,
       { str_xdy, str_ell, str_xqq, str_ikf, str_wdo, str_lea, str_slv
         |
         NAT > str_qcq$0 },
       str_awv]
    THEN
      PRE
        not
          (bool(NAT1 /: MININT <=> perm(MAXINT) /: str_hsi) <
           struct(str_ray: str_cxh, str_edd: []))
      THEN
        VAR
          str_tae, str_vzv, str_aru, str_gmw, str_afg, str_kfj, str_kel,
          str_zqg, str_iay, str_khl, str_ued
        IN
          str_hdf, str_avs, str_qec, str_sjp, str_igw, str_tej, str_qrn :(
            not
              (!(str_doa, str_mvb, str_vjc).
               (not
                  (!
                     (str_xqs, str_uaa, str_bzl, str_ugz, str_csn, str_avo,
                      str_erq, str_yuf, str_gtp, str_mpo, str_xgi).
                   (#(str_amr, str_yvl, str_qxf, str_eut).
                    (str_qow$0 > NATURAL) =>
                    #(str_uqt, str_xkn, str_ecr, str_xjg, str_rff).
                    (str_imp /<<: INT)))))
          )
        END
      END
    ELSIF
      SIGMA(str_zly).
      (!(str_rrf, str_ajc, str_fsb, str_kta, str_kms, str_qyy, str_ekp).
       (str_uyu$0 <<: str_mgl$0)|
       struct
         (str_yvv: str_bbr$0,
          str_uol: str_yex,
          str_zyv: NAT1,
          str_zdx: str_qpw,
          str_nep: NATURAL1,
          str_eqq: str_zvn,
          str_xbc: NAT,
          str_lwx: MAXINT)) =
      UNION
        (str_jvy, str_hwu, str_pdy, str_oxk, str_ncm, str_qby, str_jsb,
         str_yca, str_wmj, str_gdy, str_caw).
      (TRUE <: str_ffb$0| TRUE * NAT1)
    THEN
      str_qhk'str_ibg
      :=
      { str_esj, str_zbk, str_oyj, str_gnk | str_jbu$0 > str_bxy }
      ,
      { str_yot, str_oqe, str_yby
        |
        not
          (!(str_vcl, str_yyz, str_emf, str_nhc, str_jvy, str_gai).
           (#
              (str_nbv, str_cgu, str_ccx, str_vao, str_wbr, str_cma, str_npo,
               str_xla, str_vde, str_qxz, str_vba).
            (str_dhr = str_pei))) }
        'str_gwp
    ELSIF
      not
        (#(str_blx).
         (not
            (not
               (#
                  (str_xuf, str_aer, str_dvq, str_gkh, str_vwt, str_mbk,
                   str_rth).
                (not
                   (#(str_mrd, str_rca, str_nvd, str_omq).
                    (str_uqc$0 <<: str_sfv)))))))
    THEN
      SELECT
        [] :
        [BOOL,
         str_tcd,
         str_wln$0,
         str_wpv,
         (tree(bool(str_pnk$0 : str_xgz$0)'str_ebc)),
         { str_brv, str_amz | #(str_qks).(str_qam$0 = str_nrt$0) }]
      THEN
        str_ebs, str_atu, str_wyg, str_dwe
        :=
        right
          (rec
             (str_nqf: TRUE,
              str_dzm: struct(str_yyi: str_obr'str_kqq),
              str_svj: str_kws,
              str_snc: str_ijt'str_pwf,
              str_lww:
              { str_qjm | str_wex$0 >= str_ixd or FALSE >= str_prb$0 }))
      WHEN
        #
          (str_nfn, str_lsz, str_xpt, str_hvb, str_yja, str_fcr, str_dfq,
           str_pdp, str_pxb, str_fcx).
        (#(str_cot).
         (not
            (!
               (str_dnd, str_iut, str_kxy, str_dza, str_tms, str_wbs,
                str_ghm, str_tjj, str_mqt, str_ahr, str_eac).
             (#(str_ofk, str_ybc, str_jxq, str_yav, str_cci, str_fcn).
              (!(str_yhr).(str_foj$0 : str_lhg$0) => str_gre : NATURAL1)))))
      THEN
        str_qnr, str_peq, str_qug, str_pie, str_hgz, str_pol, str_qdx,
        str_hmg, str_uhu, str_svh :(
          [struct
             (str_npy: str_qzk,
              str_tey: TRUE,
              str_ges:
              UNION
                (str_omx, str_vvf, str_djc, str_hrc, str_vtk, str_ahj,
                 str_icz, str_ggd, str_bgq, str_jfa).
              (#(str_azd, str_yjq).(NAT >= str_hqc)| str_whf)),
           BOOL,
           (INT >->> TRUE),
           INTEGER,
           str_mar,
           MAXINT,
           [str_olu$0, str_hqm$0, str_qpg$0, INT, str_xhc$0, str_opv$0,
            STRING]] /:
          str_osj$0
        )
      WHEN
        #(str_gks, str_sqm, str_oqi, str_iiu, str_ehv, str_sww, str_cdm).
        (PI(str_hmf).
         (not(STRING >= str_elg)|
          str_cce$0
          ,
          [str_yot, str_xyx$0, str_uvh, NAT, MININT, str_iqm$0, str_qgc]) /=
         FALSE'str_dls)
      THEN
        IF
          !(str_efi, str_bdq, str_yqp, str_vrp, str_kir, str_yyx).
          (!(str_pqe, str_pnc).
           (#(str_rtl, str_mua, str_dtj, str_wpx, str_bht).
            (not(NAT > INTEGER) =>
             #
               (str_iav, str_ytq, str_vln, str_wfc, str_lsc, str_doy,
                str_xwp, str_emy, str_cvk, str_nwz).
             (str_xtg$0 /<<: FALSE & {} = str_qyx$0))))
        THEN
          str_rhj, str_iuf, str_syh, str_soe, str_yjv, str_gop, str_hfn,
          str_oms
          <--
          str_ecr
            (([str_cbs,
               rec
                 (str_qyr: str_ick,
                  str_fhg: NAT1,
                  str_tii: str_qdq,
                  str_djw: NATURAL1,
                  str_wya: MAXINT,
                  str_xhx: NATURAL,
                  str_eea: str_exz,
                  str_hye: str_swq),
               TRUE,
               str_qqq,
               {str_tgx$0, str_buw$0, str_tpr$0, str_zgq$0, str_gev$0,
                str_vuu, str_qea$0, STRING}]
                ([INTEGER,
                  str_eao$0,
                  (((str_aov , str_quk) || STRING)),
                  str_qfk,
                  str_bws])),
             rec
               (str_acx: str_jpv$0,
                str_tto: str_jbi$0,
                str_dxi:
                ({FALSE, str_elb, str_kyd, STRING, (str_exv(str_byy))}
                 ,
                 PI(str_nmn, str_svi, str_pus, str_zym).
                 (str_tif$0 /<: str_qwl$0|
                  UNION
                    (str_xwe, str_khu, str_iml, str_rqy, str_ydr, str_fyk,
                     str_xew, str_amp, str_trw).
                  (not(MAXINT > str_fgz)| 7))),
                str_pmg: str_glk$0,
                str_slk: str_wea,
                str_iwx: str_wfm,
                str_dhw: str_erg$0,
                str_uga: TRUE),
             rec
               (str_wyz:
                (str_nge
                   (str_ggf$0 |>>
                    (str_yck
                       ([str_yxx, NAT1, str_mhv$0, str_suy$0, NAT, BOOL,
                         str_lgl, str_kxk$0]
                          'str_jcr))
                      'str_qra))),
             struct
               (str_wun: (str_biy$0 +-> str_jdj$0),
                str_kbp: str_ofm$0,
                str_mtn:
                UNION(str_rfp).
                (str_qau <<: str_hsu$0| (str_cpr <<| str_swg) |-> str_jwy),
                str_ows: {},
                str_byy: str_nza$0,
                str_iza: {str_ftu$0}),
             ((union
                 (PI(str_plv).
                  (str_cly$0 /<<:
                   {str_got$0,
                    str_tal,
                    str_qrc$0,
                    struct(str_hhv: str_fmn$0, str_ofb: str_mrc$0)}|
                   str_dad$0)))
              |->
              (INT(str_yon))),
             bool
               (#(str_vxo, str_czj, str_dsb, str_ciu, str_wrf).
                (#(str_zng, str_szw, str_dlw, str_qum, str_ujn).
                 (str_pef$0
                  ,
                  INTER(str_ijt, str_rnk, str_ngm, str_yay, str_txo).
                  (str_vzj <= str_rlf$0| str_agb$0) <:
                  {str_run$0, str_lir$0, str_mzn$0, str_dxf$0, str_nun$0,
                   str_oiz$0, str_dhd}))),
             { str_pwr, str_xem
               |
               not
                 (str_ccg <:
                  rec
                    (str_ndg: str_vdj$0,
                     str_wck: NATURAL,
                     str_ums: MININT,
                     str_ddi: str_fik$0,
                     str_fny: str_mla$0,
                     str_iaz: str_poq$0,
                     str_dya: str_wqn,
                     str_nsm:
                     { str_wku, str_fzo, str_lmq | not(str_sbo$0 <: FALSE) })) }
               'str_rho,
             [str_vpy,
              NATURAL,
              str_ftj$0,
              str_tgo,
              (bool(NATURAL1 /= str_prd$0)(str_dkg$0(str_gdb$0))),
              { str_qvx, str_yqr, str_qyi
                |
                str_xkm$0 /= str_kfk$0 => str_dxu$0 >= INT },
              (POW1(str_pgu))],
             [((str_iuy || str_jhq)),
              (Pred(str_yol +->> str_aog)),
              TRUE,
              [{STRING,
                str_eyd$0,
                MAXINT,
                str_qir,
                NAT,
                (POW(str_hew$0)),
                str_oat,
                str_zqw},
               {},
               str_nws$0,
               str_wun,
               str_wrd$0,
               str_vyo],
              str_vtb$0,
              NATURAL])
        ELSIF
          !
            (str_qrl, str_kpc, str_kfe, str_xit, str_tkg, str_uht, str_cci,
             str_bwm, str_zqg, str_mvt, str_jwo).
          ((!
              (str_dhi, str_jje, str_lnl, str_sur, str_rva, str_hcn, str_npm,
               str_uca, str_yqz, str_qum).
            (str_sho$0 /<<: {}) =>
            INT /: str_zlc) =>
           !
             (str_ras, str_mnu, str_rno, str_wrg, str_qhr, str_rla, str_maf,
              str_ydi).
           ([] <: str_mvv$0)) <=>
          (str_fmx <<: BOOL or {} <: str_sfv)
        THEN
          LET
            str_dbi, str_brc, str_fkm, str_fiw, str_sib, str_dfg, str_egs,
            str_cjb, str_acg, str_sun
          BE
            str_rgk
            =
            { str_ybs, str_mzd, str_xil, str_sth, str_bpu, str_hcr, str_ync,
              str_qov, str_lqp
              |
              #(str_bha, str_ysj).
              (FALSE >= [] &
               (struct
                  (str_jpg: str_ayt,
                   str_vte: NATURAL1,
                   str_ksq: [],
                   str_vxt: INT,
                   str_use: str_nxn$0,
                   str_huo: str_nxu,
                   str_esc: str_jid$0) /=
                str_xjo$0 <=>
                str_hzh$0 /= STRING)) }&
            str_xhh
            =
            INTER(str_hjy, str_fdi, str_tqs, str_lmf, str_cvq).
            (#
               (str_azs, str_tow, str_tft, str_wlj, str_kqw, str_cgi,
                str_hco, str_hbg).
             (BOOL /<: str_qsb)|
             bool
               (!
                  (str_nsy, str_ypz, str_pno, str_wvq, str_zip, str_yip,
                   str_zbn, str_nwb).
                (!
                   (str_tfh, str_xzu, str_smj, str_aci, str_ohs, str_exo,
                    str_wro, str_lhm, str_mwg, str_lwf, str_ahk).
                 (NAT1 <=
                  INTER(str_sef, str_brc). (str_hql$0 = MININT| INTEGER)))))&
            str_vkz
            =
            FIN1
              (((rec
                   (str_kuv:
                    rec
                      (str_tju: str_jja,
                       str_dxp: str_gin$0,
                       str_hwy:
                       struct
                         (str_cad: bool(str_xjm /<<: str_hqt),
                          str_idx: str_eho,
                          str_lun: str_ifp$0,
                          str_unt: NATURAL))) ;
                 BOOL))
                 'str_uts)&
            str_xlk
            =
            { str_wlm, str_plk, str_jai, str_wjc, str_ujn, str_tlu, str_hlp,
              str_ouz, str_oox, str_lmv
              |
              not
                (str_izi$0 /<:
                 rec
                   (str_oqa: MININT,
                    str_miz: str_xcy$0,
                    str_epw: str_rqn,
                    str_lqv: str_cyc$0,
                    str_qai: str_tru$0,
                    str_utr: INT,
                    str_ufz: [],
                    str_qab: str_xml$0)) <=>
              str_jtr /<: STRING }
              (str_ilx$0)&
            str_wxi
            =
            {str_oew$0,
             [str_tqi$0,
              str_sqa,
              str_wwc,
              PI(str_lje).
              (!
                 (str_vgj, str_nhu, str_hcd, str_zwa, str_hyq, str_mks,
                  str_fkt, str_nax, str_ahw).
               (str_wgb$0 = str_esr$0)|
               4),
              MAXINT,
              str_cql,
              str_nko$0],
             str_zdi,
             str_epk,
             str_kqh$0,
             str_odq$0,
             str_svv,
             str_lyn$0} <->
            ((str_wtk$0(str_efj$0)) >+> str_pfd$0)&
            str_yja
            =
            (conc
               ({str_wkg,
                 str_yct$0,
                 INT,
                 str_klx$0,
                 str_udx,
                 INTEGER,
                 str_zot,
                 bool
                   (not
                      (MAXINT < MININT &
                       #(str_xho, str_hgu, str_jba, str_fcf).
                       (str_xkd$0 <: str_jei)))}))
              'str_sua&
            str_xqb
            =
            (union(str_wie))
              (top
                 ({ str_smz, str_lsx, str_ejy, str_utk, str_faf, str_jsq
                    |
                    not(BOOL = bool(NAT1 /= str_pwj$0)) }))
          IN
            str_shr, str_thm, str_qby, str_pvj, str_ieo
            <--
            str_uwk
              (rec
                 (str_lcl: NAT,
                  str_hoo: bool(not("str_fbi" <: str_wvq$0)),
                  str_cnv:
                  rec
                    (str_vgf: str_cya$0,
                     str_cip: NATURAL,
                     str_osi: "str_iwy",
                     str_cit:
                     PI(str_oqh, str_uiw, str_ihi, str_mjp, str_ylf, str_opw).
                     (#(str_upv, str_eto, str_cfr, str_mpp, str_ozr).
                      (2 = str_pts)|
                      {}),
                     str_prx: str_kfq,
                     str_nzy: str_eoc$0,
                     str_xrm: str_peo,
                     str_uon: str_obu),
                  str_idi: NAT)
                 'str_esa,
               (str_xvg$0 |>>
                (BOOL <+
                 %
                   (str_znh, str_qjs, str_twm, str_sva, str_eko, str_rae,
                    str_wus).
                 (str_klw$0'str_hvi >= closure(str_ghv)|
                  { str_iyz, str_dzg, str_tmq, str_xpc, str_baa, str_wli,
                    str_mul, str_fem, str_deo, str_xpt
                    |
                    str_juq /<: str_sah }))),
               (id
                  ({ str_ufx, str_tvs, str_utc, str_sqk, str_enr
                     |
                     INT /<: str_tww$0 =>
                     !
                       (str_qlh, str_nvj, str_odc, str_tau, str_kqm, str_roy,
                        str_jig, str_fbd, str_nsj, str_lkn).
                     (!(str_wyk, str_fzz, str_jve, str_hyz, str_rcp, str_gzc).
                      (#
                         (str_ioo, str_tpv, str_yvq, str_wmh, str_zeh,
                          str_dji, str_ulf, str_hvh, str_ops, str_pwm,
                          str_bir).
                       (str_vmn$0 <<: str_luk$0))) }
                   |->
                   STRING)),
               bool
                 (!(str_pjd, str_scc, str_ktv, str_qrp).
                  (struct
                     (str_wsk:
                      bool
                        (!
                           (str_evw, str_uix, str_bqp, str_dft, str_pwa,
                            str_ksv, str_ncn, str_jxj, str_pqk).
                         (str_phb <= str_ltl))) /:
                   rec
                     (str_vdv: str_umb,
                      str_esi: str_irm,
                      str_bqw: BOOL,
                      str_roq: str_aww,
                      str_ioz: str_tsj,
                      str_vpw: MININT))),
               { str_jus
                 |
                 {(str_sdj(NATURAL)),
                  str_kxs$0,
                  {{ str_hjx, str_byl, str_cuy, str_zti
                     |
                     str_vpr$0 /<: str_nmy },
                   NATURAL,
                   str_pol$0,
                   bool(str_vgz >= str_wxu),
                   str_ykz$0,
                   TRUE,
                   TRUE}} /=
                 NATURAL },
               (UNION(str_zoj, str_mlc).
                (#(str_cuh).(FALSE <<: str_jph$0)|
                 [str_stl$0, str_mfg, bool(TRUE = str_rrc$0(MAXINT))]) /|\
                str_daw$0),
               ((iterate
                   ([str_yar, str_xno, str_dca$0] >-> (subtree(str_veo))))
                  'str_ndz
                  'str_ixg
                |->
                {}),
               { str_rcu, str_yws, str_dik, str_epb, str_xha, str_ouo,
                 str_wee, str_vpw, str_wrj, str_kcc
                 |
                 not((NAT1 ; (NATURAL , str_imc)'str_aqc) <= TRUE) }
                 'str_wkh)
          END
        ELSIF
          { str_ebo, str_pws
            |
            #(str_zgi, str_edn, str_sld, str_tvd, str_feb).({} /<: NAT) } /=
          rec
            (str_frf: (str_iho[INTER(str_klk). (str_gxt <= []| str_rlk)]),
             str_ubk: str_vmt$0,
             str_fne: str_jqj$0)
            'str_yjl
        THEN
          str_qow, str_zxs, str_bpc, str_omk, str_nis
          ::
          max
            (bool
               (#
                  (str_grk, str_ebj, str_jet, str_qzz, str_uiw, str_qpw,
                   str_bsg, str_lkw, str_otd).
                (#
                   (str_wea, str_sky, str_uvh, str_vae, str_pah, str_vmt,
                    str_scm, str_mol).
                 (#
                    (str_hxt, str_awu, str_fet, str_npg, str_lya, str_mhb,
                     str_uut, str_tyd).
                  (str_qir$0 /: str_hll &
                   (str_yhb$0 <<: str_jkx$0 & str_qxu >= str_jqu$0))))))
        ELSIF
          struct
            (str_uqh:
             INTER(str_mky, str_hor, str_sez, str_xws, str_cie, str_rcp).
             ({} > str_tfq$0| str_avz),
             str_ssi: str_fuy,
             str_hdm: str_aoi$0,
             str_cjo: "str_azk",
             str_aht: NATURAL,
             str_lvb: str_yzq,
             str_mny: str_mmj$0,
             str_jcu: {}) >
          TRUE -->>
          rec
            (str_gtm: str_ykc,
             str_oyh: str_pul$0,
             str_rrf: str_qta,
             str_ybi:
             %(str_vhm, str_lfk, str_bag, str_lid, str_rds, str_swt, str_wkc).
             (str_hyc$0 /<: str_ihg| str_opy),
             str_pjp: NAT1,
             str_hrp: struct(str_hkr: str_emz$0),
             str_mzl: [],
             str_dut: str_xlk)
        THEN
          str_xht, str_ojv, str_fum, str_imh, str_wbj, str_mzh, str_gpl,
          str_mye, str_hgr, str_hou :(
            #(str_jyz, str_suz, str_fkr, str_nzd).
            (not
               (rec
                  (str_oct:
                   UNION(str_fgv, str_obn, str_tpb).
                   (STRING : str_joz$0| NAT1),
                   str_mwz: str_npm$0,
                   str_tky: str_njn) /<:
                bool(NAT1 >= str_exo & NAT : str_dwe)))
          )
        ELSE
          skip
        END
      WHEN
        !(str_mqh, str_bfp, str_axn, str_awp, str_rtq, str_exh).
        (bool(str_fet$0 <<: str_qsy$0 or str_vun$0 <<: str_rpd$0) : MAXINT &
         not(not(str_mkj /<<: NAT)))
      THEN
        str_gya'str_uff
        :=
        mirror
          ([str_lvl$0,
            MAXINT,
            [str_mkg, str_ggu],
            (rec(str_ruj: bool(str_zwt$0 = FALSE), str_ysz: INTEGER)
               (NATURAL1)),
            struct(str_lyg: NATURAL),
            str_xja,
            str_myv$0,
            str_usk$0])
      END
    END
  END

VARIABLES
  str_gnq, str_lvs, str_sza, str_iiq, str_kdb, str_kkt, str_pus

CONCRETE_VARIABLES
  str_agk, str_aii, str_pot, str_mdb, str_iez

ABSTRACT_CONSTANTS
  str_frt, str_sue, str_gxt, str_niz, str_slm, str_fbc, str_kfu, str_bfa

CONSTANTS
  str_lfi, str_pjm, str_zpw, str_jxx, str_tbn, str_ndq, str_svh

USES
  str_cqx, str_xst, str_xng, str_mnl, str_fet, str_dyb, str_qzn, str_qbg,
  str_xrz

EXTENDS
  str_fxc (
    [(struct(str_lri: str_okb, str_klo: str_ijj) mod str_kpu),
     (str_bvl$0 -->> {}),
     BOOL,
     bool
       (!(str_dcl, str_bdc, str_tpu).(NATURAL < str_fpr$0) or
        str_xvo$0 /= str_skb$0),
     str_gec$0,
     str_rip$0]
  ),
  str_cox (
    struct
      (str_evb:
       ({BOOL, str_keg$0, str_hkk, str_mhw, MININT, INT}
          [(NAT1 |-> str_rsc)
             (INTER(str_eqz). (str_ylz$0 /<<: str_mbb| str_npz) <-> NAT)]))
  ),
  str_zvh (
    { str_wir, str_ktl, str_yrj, str_lms, str_hfj, str_mso, str_cou
      |
      not
        ((str_lpj$0 \/ str_ooo)
           ({NAT1,
             (str_bde$0 /|\ MAXINT),
             INT,
             str_hhx$0,
             str_sob$0,
             BOOL,
             NATURAL,
             str_qjq}) /=
         str_pzd) }
  ),
  str_pjc (
    { str_nlx, str_oqb, str_wuz
      |
      !
        (str_ody, str_ufz, str_sew, str_dkq, str_czi, str_ysv, str_uny,
         str_fmu).
      (!
         (str_zuv, str_bgb, str_fkw, str_cnw, str_yzq, str_sca, str_vgh,
          str_xmz).
       (not
          (!
             (str_ifm, str_dwl, str_vjr, str_tut, str_ogc, str_vpq, str_uyb,
              str_yut, str_gvy, str_jtd).
           (!(str_yez, str_vrw).(TRUE /: str_wde$0) or {} /<: NAT1)))) }
  ),
  str_srt,
  str_idl (
    rec
      (str_ekf: NATURAL1,
       str_gop:
       (left
          ([struct(str_aeu: str_qcf$0, str_mpl: str_aoo$0, str_tdn: NAT),
            str_weu,
            (left(str_mob)),
            str_fau$0,
            (str_igd$0(str_lcy$0)),
            str_ayi,
            str_pyf$0]
           ,
           str_bzg$0)),
       str_dxm: NATURAL1,
       str_xvn: str_fkp$0,
       str_ojd: NAT1),
    {(str_qxa -
      struct
        (str_ptr: str_wyy, str_kaj: INT, str_nsx: INTEGER, str_vha: str_tji$0)),
     {str_blv,
      { str_bja, str_hcu, str_uxj, str_rye, str_lum, str_los, str_ldo,
        str_bah, str_glc
        |
        str_otc <= INTEGER },
      str_vgv$0,
      [],
      119,
      str_tcz},
     str_uen'str_qru,
     struct(str_rvo: str_dqs)}
  ),
  str_nik (
    %(str_uio, str_cui, str_eaj, str_tri, str_gta, str_pto).
    (str_anu$0 /= str_cwr$0|
     struct
       (str_ejr: (str_qgc <+ str_zyg),
        str_lyp: str_mqa,
        str_jmq:
        (UNION(str_edl, str_hgy, str_pza). (str_pri$0 = str_jbw| str_slq$0)
           (str_qdr$0))))
      'str_zrb
      'str_dzn,
    PI(str_eaw, str_oyl, str_nzz, str_sqa, str_lbh).
    (not
       (#
          (str_ibl, str_kno, str_sij, str_fec, str_dhu, str_fzi, str_lpy,
           str_rub, str_nyb, str_hag, str_vdq).
        (!
           (str_yyj, str_tfg, str_ulb, str_xcj, str_dyn, str_ivk, str_smv,
            str_llq, str_qgs, str_cbk, str_wci).
         (str_gvh$0 > str_zfg$0 or str_rgb /: str_gks$0)))|
     str_pqc$0 - str_hfg$0)
      'str_uqd,
    {((POW(str_rap)) |-> str_eij)'str_ijl,
     rec
       (str_vha: bool(str_osc$0 < str_obp$0),
        str_sgh: (str_zuh |-> str_sfx$0),
        str_vha: FALSE,
        str_xis: "str_rjv"),
     str_lvn}
  ),
  str_nqw,
  str_bwj (
    rec
      (str_cbz:
       bool
         (!
            (str_qru, str_ycy, str_qdt, str_oir, str_own, str_vtu, str_hrp,
             str_wbk, str_lnv).
          (str_oaf$0 <: MAXINT <=>
           #(str_ndc, str_acf, str_jiy, str_wqf).(not(str_lxi$0 /<<: BOOL))))),
    [{ str_uxn, str_tgj, str_tmr, str_oak, str_xnw, str_caz, str_trr,
       str_jmo, str_pwm, str_wib
       |
       str_ypu >=
       rec
         (str_trw: str_duy,
          str_ehq: str_ahc,
          str_ryw: str_gxf,
          str_zoo: str_plb,
          str_pkd: BOOL,
          str_wnz: INT,
          str_dxv: str_kll$0,
          str_ikd: []) <=>
       (str_kbw /: str_qxn & (str_xag /= MININT or str_rgz >= str_aze$0)) }],
    [rec
       (str_blb: bool(str_nkf < str_jno$0),
        str_wwg: str_jot,
        str_adp: str_oyg,
        str_elf: str_pim$0,
        str_uta: str_fjp$0,
        str_cku: str_tzc),
     str_rju$0,
     str_drz$0,
     TRUE,
     str_eqv$0,
     str_nsr,
     [{str_bgs$0, str_gqz$0, FALSE, MAXINT, INT, str_kqc, str_lry},
      [str_tqh$0, INT, str_avd, str_uyn$0, str_zkd$0],
      FALSE,
      str_edt,
      (str_haz$0 |-> str_rcm),
      FALSE]]
  )

PROMOTES
  str_hqm, str_lmc, str_esd, str_dyr, str_nzf, str_wuz, str_oyt, str_bqm,
  str_hon, str_prv

INCLUDES
  str_yda (
    ({FALSE, NATURAL1, str_mpv$0}
       (%(str_dqa). (str_nbo$0 >= str_cyx$0| str_uce$0) >->
        (str_fbt |-> FALSE'str_acw)'str_kgg))
  ),
  str_rip

SEES
  str_ndk, str_fnr, str_pvs

CONSTRAINTS
  not
    (not(NATURAL /: str_bdb => not(!(str_sgd, str_loo).(str_huj > NATURAL1))) &
     !(str_lyb, str_bwe).(str_whc$0 < str_ecw$0))

END 