MACHINE
  str_ade

INITIALISATION
  VAR
    str_qxs, str_rcp, str_lxn, str_qqs, str_zel, str_jif
  IN
    str_axo, str_kcb, str_kwh
    :=
    (BOOL , (BOOL <<| (str_sfu$0 , str_ngk$0)))
    ,
    (postfix
       (rec
          (str_qte: INTEGER,
           str_kvj: str_rzz,
           str_dxl: str_nmy,
           str_dcb: str_wzp)
          'str_wsj)) ||
    ASSERT
      not(not(#(str_rbr, str_irs, str_jyq, str_bph).(str_nfi$0 >= FALSE))) or
      #
        (str_acj, str_jmf, str_xhr, str_dvq, str_xcd, str_bkh, str_kjd,
         str_yjw, str_rkp).
      (NATURAL > { str_dkn | str_wfv /<: str_rbj$0 })
    THEN
      LET
        str_dlp, str_jei, str_whw, str_zrh, str_zny
      BE
        str_qll
        =
        { str_bik
          |
          not(NATURAL1 <: MAXINT) =>
          #
            (str_gmm, str_tvf, str_pyh, str_abf, str_tmb, str_byr, str_kwd,
             str_zmx, str_sze, str_nas).
          (!(str_rtf, str_mer, str_uht, str_det, str_tkt).
           (str_rzi$0 <<: str_tzp$0 =>
            #
              (str_nuy, str_yjc, str_jof, str_mox, str_mjo, str_hfl, str_lut,
               str_bko, str_ozo).
            (str_hfx$0 /<<: str_dty$0))) }&
        str_qtu
        =
        UNION(str_hdt, str_tnp, str_eyx, str_siw, str_ddl).
        (#(str_qsr, str_uif).
         (not(!(str_zpk, str_vhu, str_pbk).(INTEGER <= str_ihf)))|
         struct
           (str_rru: str_swz$0,
            str_wur: str_vou$0,
            str_sod: NATURAL,
            str_fna: str_ygv,
            str_aew: INT,
            str_una: NAT1) +
         bool([] /<: str_vdt))&
        str_nqx
        =
        { str_bok
          |
          !(str_lff, str_tvi, str_gcm, str_ene, str_gxa).
          (NAT1 <<: NAT <=>
           not
             (!
                (str_abb, str_spz, str_lrw, str_drw, str_yvc, str_dfa, str_nlo).
              (str_dak > str_rcx or not(str_qeq > str_vrc)))) }&
        str_qyb
        =
        { str_jny, str_boz, str_wrk, str_hqv, str_nvj, str_gcy, str_bqd,
          str_ymt, str_dkq
          |
          INT >->> ((({}(str_mhr)) mod str_ekz$0) |-> (sizet(str_myx$0))) <:
          str_fed }&
        str_pfy
        =
        {(str_mql$0(str_hcv$0))}
        |->
        bool
          (MAXINT <<: NAT1 or
           !(str_zsx, str_lxa, str_hmz, str_pjc, str_vlc).
           (!
              (str_ozg, str_pcx, str_zbk, str_dsb, str_lgq, str_xro, str_dzp,
               str_vyd).
            (NAT /= str_drk$0)))
      IN
        PRE
          #(str_hvf, str_dmv, str_lnn, str_txr).
          (not
             (!
                (str_dol, str_chw, str_ofg, str_uui, str_muk, str_bui,
                 str_ddf, str_gpi, str_hvk, str_heq, str_nfw).
              (not
                 (not
                    (#
                       (str_kvk, str_ktd, str_gub, str_ccs, str_dvi, str_hag,
                        str_fjs, str_xvo, str_fma).
                     (not(str_qfb$0 /<: str_mep)))))))
        THEN
          str_qpg, str_vix
          :=
          { str_tjs, str_kbb, str_dlg, str_wxc, str_xbu, str_pns, str_tmt,
            str_sci, str_eqs, str_fse
            |
            not
              (#(str_ayw).
               (bool(!(str_qwb, str_joz).(STRING = str_msu$0)) = str_avb$0)) }
            'str_crx
        END
      END
    END ||
    WHILE
      #(str_qfm, str_ulc, str_msf).
      (!
         (str_pmt, str_awe, str_jck, str_jwo, str_ctt, str_ywx, str_xuq,
          str_xbg, str_eif, str_dij, str_vzi).
       (#
          (str_fby, str_ogz, str_tvz, str_wjc, str_gdi, str_iam, str_lsb,
           str_qbs).
        (str_wqs$0 /<<: str_ldz) <=>
        !(str_zpz, str_wfg, str_hko, str_szc, str_ish).
        (not
           (#
              (str_fwu, str_uic, str_lag, str_yiw, str_czc, str_cmo, str_elm,
               str_srt, str_odx).
            (str_tph < str_xhc)))))
    DO
      str_opq
        (bool
           (#(str_jvi, str_bqj).
            (!(str_ovq, str_diu, str_auk, str_wjk, str_rdw).
             (str_nfo$0 = str_kyx)) &
            #
              (str_pim, str_afd, str_oyv, str_spv, str_mlb, str_sri, str_uhl,
               str_euz).
            (#(str_oao, str_oyo, str_hop, str_uqm, str_rlx).
             (str_ivf$0 : str_dsh))),
         rec
           (str_gri: [NATURAL, NAT1],
            str_agq: "str_dpx",
            str_gly: ((str_lus ^ str_ttx) |> str_ucc$0)'str_jkn,
            str_ken: str_uwy$0,
            str_qam: (str_qlg'str_jgh |-> {})),
         struct
           (str_yvq: str_cjd,
            str_dgp:
            {str_avh,
             [],
             (str_xti$0(rec(str_wss: NAT)'str_uam)),
             str_czb,
             (tree("str_zzm"'str_ykg))},
            str_ulz: str_stn,
            str_qbu: str_ufo$0),
         ({ str_oxe, str_iig, str_nbq
            |
            { str_tow, str_qvn, str_muh, str_akr, str_ogy, str_tgf, str_ghk
              |
              STRING /: str_ain$0 & NAT1 <<: "str_xjo" } <<:
            str_koe$0'str_cjv }
          ,
          { str_vnw, str_onh, str_dmg, str_kzx, str_pgo
            |
            str_fpa >= str_tea$0 }))
    INVARIANT
      (str_ged$0 = str_wyy$0 <=>
       #(str_fds, str_nky, str_wrc, str_fic, str_cad, str_fjo).
       (#(str_dxa, str_glm, str_vln, str_ihy, str_mew).(str_ukz$0 = NAT1))) =>
      str_gaj$0 =
      [str_ese$0, NAT1, MININT, str_hoj, str_qqy, str_por, str_qgf$0, str_vis]
      ,
      str_eid
    VARIANT
      struct
        (str_tnc: str_bdc,
         str_hga: [str_zmr'str_lkt],
         str_xmh:
         ((str_rcm ;
           PI
             (str_qna, str_qcv, str_lri, str_xek, str_trm, str_tsj, str_nmj,
              str_vvd).
           (str_xlt : str_ywa$0| str_tsy$0))),
         str_dkj: str_dbj'str_pfe,
         str_ysz: bool(str_cai : str_dun$0),
         str_evr: str_ncb$0,
         str_vjq: FALSE)
    END
  END

ASSERTIONS
  STRING <<:
  PI(str_nrj).
  (!(str_uua, str_klj).(INTEGER /= MAXINT) => str_any <: bool(567 /: str_cjv)|
   str_dct$0)
  ,
  str_kim;
  (str_ngg$0 <<: TRUE &
   rec(str_ans: str_cra$0, str_rmq: str_sml$0, str_noa: str_oxe$0) /<<:
   str_rrs$0
     (rec
        (str_ysk: str_ied,
         str_zjn: [],
         str_knh: BOOL,
         str_qwf: [],
         str_xuu: str_xix$0,
         str_ynp: (str_pzc$0 /|\ INT),
         str_uzz: str_lyh$0))) =>
  [] >= FALSE;
  not
    (#
       (str_rgu, str_vzx, str_cfn, str_hdn, str_ler, str_fxg, str_jel, str_mop).
     (not
        (not
           (!
              (str_ksf, str_wds, str_vrj, str_owa, str_glh, str_kxf, str_tuo,
               str_fmj, str_qgu, str_inh).
            (#(str_lok, str_pfd, str_urz, str_uws, str_yyp, str_qjf, str_txf).
             (!
                (str_txw, str_vtz, str_zfe, str_lod, str_gxc, str_pxp,
                 str_fwx, str_pqy, str_ydi, str_cxt).
              (str_kfy <: NAT1)))))));
  #
    (str_uby, str_srq, str_wck, str_dgb, str_byw, str_gxf, str_yju, str_ejv,
     str_alz, str_ugn).
  (struct(str_gyp: str_juo$0, str_rdo: str_xyb$0, str_hfy: str_akv$0) -
   str_umh :
   [{}, INT, str_fnq, str_ntg$0, NATURAL, str_rbp$0, NATURAL1, str_unr]
   ,
   (str_mgr +-> str_ovx));
  not
    (#
       (str_utk, str_vyn, str_ekw, str_lov, str_oqw, str_zhb, str_ppz, str_usc).
     (BOOL /<: str_czq$0'str_izz) &
     not
       (#(str_rze, str_qmr, str_enj, str_rui, str_ete, str_omu, str_nus).
        (str_qfm < str_azz)));
  not
    (str_yss$0 /= str_zsn$0 =>
     not
       (const(str_fct(str_pwr$0)) =
        rec
          (str_bgz: str_bzs$0,
           str_avd: str_xsv,
           str_kou: NATURAL1,
           str_pyd: INTEGER,
           str_gdm: str_dmv$0)));
  not
    (!(str_ncd, str_wbu, str_coq, str_wbx).
     (!(str_nad, str_cwp, str_gql, str_cyx).
      (str_tvl : str_ftz <=>
       !(str_ufn, str_bbx, str_nou, str_avj, str_plb).
       (not(str_usi$0 <= str_ckx$0)))))

INVARIANT
  #(str_uhz, str_iln, str_zqp, str_ima, str_wmx, str_oxl, str_ndk).
  (#(str_nxo, str_dln).
   (#(str_szq).(str_cif$0 /= str_gly & str_ouu$0 = str_lxl) <=>
    str_exo$0 /<<: str_qhc$0))

VARIABLES
  str_dej, str_irl, str_eao, str_oqq, str_myu, str_tfm, str_gpu, str_gpz

CONCRETE_VARIABLES
  str_qif, str_hjo, str_ayf, str_qkr

CONSTANTS
  str_kkt, str_mmn, str_rjr, str_hqh, str_aqb, str_blc, str_zxn, str_ued,
  str_ogh, str_spe

SETS
  
    str_pge
    =
    {
      str_bja, str_jyk, str_xlh, str_hrm, str_pgv, str_ugk, str_pmg, str_pxg,
      str_xgl, str_hio
    }
  

USES
  str_xqp, str_bvh, str_nbp, str_lnv, str_bih, str_bci, str_rrj, str_ivx,
  str_wxc

EXTENDS
  str_lhh (
    ([NAT1, MAXINT, bool(not(not(BOOL = str_tsd))), str_jua$0, INTEGER, BOOL] <|
     struct
       (str_yqs:
        [str_hlz, str_dnq, str_prs, str_nnz$0, str_xzt$0, str_rzi$0, FALSE]))
  ),
  str_vbp,
  str_txe (
    ({{},
      SIGMA
        (str_zxo, str_fps, str_mit, str_pqe, str_ewd, str_jqg, str_yum,
         str_sud, str_hjt, str_wzy, str_qcp).
      (str_ujr /= str_lzg| {}),
      INTEGER,
      {},
      str_uap$0,
      (str_cxg$0 --> rec(str_lfq: STRING, str_tqv: BOOL))'str_jry,
      FALSE} /\
     rec
       (str_ntr: str_vnd,
        str_mro: TRUE,
        str_lrj: str_cbx,
        str_pwb: str_bwe$0,
        str_gxt: TRUE,
        str_dag: str_ivd$0)),
    rec
      (str_wsr: str_vvd$0,
       str_ctm: str_sbb,
       str_cha: str_ifu,
       str_aeg:
       ({TRUE,
         str_mgn,
         [str_gtn$0, BOOL, str_pvq, str_lgt, MAXINT, TRUE, str_zdp, TRUE]
           'str_mej,
         str_vwh,
         ("str_jxs" >->> str_jxq),
         (str_uxj(str_yno$0))}
          (str_qen$0)),
       str_yad: STRING,
       str_nlt: str_pri$0,
       str_rsq: str_mna),
    ((struct(str_rmu: TRUE, str_ddx: (rev([])), str_klc: STRING) ;
      (bool
         (#
            (str_liq, str_lpo, str_bdt, str_rki, str_nsl, str_fyk, str_zuj,
             str_qok, str_lpt).
          (MININT /: str_tim$0))
       |->
       str_djb$0)))
  ),
  str_zds (
    PI(str_dps, str_azr, str_tuf, str_jhe, str_xxp).
    (#(str_djg, str_zge, str_ytz, str_svf, str_ndg, str_ozr, str_gms).
     (!
        (str_flf, str_jrc, str_qlv, str_ilb, str_yqu, str_ubg, str_hyf,
         str_cgu).
      (str_yxc$0 : str_hdr$0))|
     UNION(str_rua, str_qfa, str_pyd, str_tzz).
     (!
        (str_xlg, str_lcw, str_oyo, str_tiu, str_hfs, str_pqm, str_wga,
         str_ejg, str_xuu, str_swe, str_gjb).
      (str_mme /: TRUE)|
      (str_pim |-> str_edu$0) <| []))
  ),
  str_wqb,
  str_jdx (
    {struct
       (str_rtq:
        [MAXINT,
         %
           (str_zyv, str_xcg, str_qvh, str_psu, str_enu, str_jdi, str_xij,
            str_btq).
         (str_fpx$0 >= 5| NAT)],
        str_ciy: INTEGER,
        str_mje: str_ugs,
        str_xcc: str_dfp'str_wll,
        str_pcn: str_ern),
     rec
       (str_ufa: str_itd,
        str_vgf: str_nmv,
        str_hdl: NAT,
        str_riu: str_jir$0,
        str_njq: INTEGER),
     str_erg,
     (STRING >< str_dpv)},
    ((min
        ({str_axx,
          ((rank(str_ngp)) mod str_vfx)'str_icd,
          str_jrm$0,
          str_jrv$0,
          str_vkp$0,
          FALSE,
          str_rgi$0,
          str_pzf}))
       (bool(str_dam /: str_swi))),
    INTER
      (str_gcg, str_qyd, str_wrz, str_aqu, str_dcx, str_vqe, str_irx,
       str_stf, str_gyz, str_mjs, str_nta).
    (not
       (not
          (not
             (NAT1 =
              {str_hfg, str_gyn, str_lhc, INTEGER, str_ioy$0} <-> str_sqv)))|
     str_xcu$0)
  )

PROMOTES
  str_qdn, str_etb, str_jef, str_tnn, str_jgw, str_vkf, str_hun, str_qer,
  str_vgk, str_oft

INCLUDES
  str_xca,
  str_atd (
    rec
      (str_nfv:
       rec
         (str_jom: MININT,
          str_msy: str_wme,
          str_hfw: str_kzb,
          str_vor: [],
          str_mwv:
          rec
            (str_uze: MININT,
             str_bvs: "str_uvv",
             str_xxp: str_hog$0,
             str_vqw:
             {str_fky, NATURAL, str_gak$0, str_oav, str_fus, str_fiv$0,
              str_scj, str_wli},
             str_xsv: BOOL,
             str_kul: str_wmr,
             str_nbh: str_pmu)),
       str_bwb: NAT,
       str_xal: (str_fgv |-> NATURAL),
       str_kib: INTEGER,
       str_zpz: (first({ str_ykg | str_gzv$0 /<<: str_lkx$0 })),
       str_ibd: str_ywi)
  ),
  str_aij (
    bool
      (!(str_jzq, str_ymq, str_wnj, str_hhu, str_rha).(str_awg <= str_nke) <=>
       (!(str_gog, str_gyq, str_enx, str_cjy, str_ucg, str_ekq, str_qdw).
        (str_kbe$0 >= str_pcg) or
        #(str_bke, str_fcc).([] <: FALSE)))
      'str_xay,
    (closure1
       (bool
          (#
             (str_brx, str_faw, str_bun, str_omf, str_yfd, str_jli, str_vxx,
              str_cbc, str_tbd).
           (BOOL : str_dun$0 or (str_nri$0 < str_dgk => str_vby = str_wbq)))))
      'str_zvc
      'str_ncb
  ),
  str_nkz,
  str_lfc

CONSTRAINTS
  !(str_fzx, str_mtw, str_nsd, str_psp).
  (#(str_xaa, str_kqi, str_lph, str_crq, str_nmo, str_lha, str_myo, str_kqy).
   (str_wet : str_tim$0)) &
  not
    (!(str_qva, str_jxq, str_suc, str_gbt, str_mhy).
     (str_gfc /: str_byp$0 & str_yul /<<: str_eln))

END 